### ISSUE TITLE
Runtime recipes are not fully invariants

### ISSUE THREAD

**Issue by Orygeunik** [AztechMC/Modern-Industrialization#100]
I found one specific problem
Bronze tank have only one type of bronze plate for craft
![image](https://user-images.githubusercontent.com/6960655/129744687-6ce1c50c-3604-4487-8de5-6887a5ebb416.png)
But runtime type is correct (`#c:bronze_plates`)
![image](https://user-images.githubusercontent.com/6960655/129745119-ddf55075-8fcf-457a-bb9c-2e19a000e30d.png)

For example static (like as \src\main\resources\data\modern_industrialization\easy_mode\recipes\steam_age\bronze\boiler_asbl.json) recipe work correct with invarian bronze plates
![image](https://user-images.githubusercontent.com/6960655/129745781-cf12afd8-50d5-4575-88f4-1be84e4f638a.png)
And uses same type (`#c:bronze_plates`)
![image](https://user-images.githubusercontent.com/6960655/129749812-68314141-9417-42d6-a3e4-32467a6e1bc6.png)

In static recipes uses this tag
``` json
    "#": {
      "tag": "c:bronze_plates"
    },
```

I seen into source and found in StandardRecipes.java uses this code for generate runtime recipe
``` Java
  new ShapedRecipeBuilder(ctx, TANK, 1, "tank", "###", "#G#", "###").addPart('#', PLATE).addInput('G', "minecraft:glass")
                    .exportToAssembler();
```

So i think the problem in is order of loading mods, when this method build recipe another mods have not loaded and registered their types yet

I have mods:
- Modern Industrialization -0.5.8;
- TechReborn 5.0.6-beta;
- Industrial Revolution 1.10.0-alpha.12;

**Comment by Technici4n** [comment]
Actually you have correctly identified the issue, it should be `addTaggedPart` and not `addPart`.
The tag that you see is the tag of the item itself, not of the recipe. That's why you see it even though the recipe hard-codes our bronze plates.

**Comment by Azercoco** [comment]
It has been fixed

**Comment by Orygeunik** [comment]
@Azercoco  what about lines:
https://github.com/AztechMC/Modern-Industrialization/blob/17be7a3279453c027e03904d6c1591f89efd3ed1/src/main/java/aztech/modern_industrialization/materials/recipe/StandardRecipes.java#L72
https://github.com/AztechMC/Modern-Industrialization/blob/17be7a3279453c027e03904d6c1591f89efd3ed1/src/main/java/aztech/modern_industrialization/materials/recipe/StandardRecipes.java#L75
And
https://github.com/AztechMC/Modern-Industrialization/blob/17be7a3279453c027e03904d6c1591f89efd3ed1/src/main/java/aztech/modern_industrialization/materials/recipe/StandardRecipes.java#L79

And maybe 
https://github.com/AztechMC/Modern-Industrialization/blob/17be7a3279453c027e03904d6c1591f89efd3ed1/src/main/java/aztech/modern_industrialization/materials/recipe/StandardRecipes.java#L50

here specially used `.addPart`?

**Comment by Azercoco** [comment]
-Large plate are not tagged by purpose (because MI is the only mod using them)
- The gear should indeed be tagged (will do it in a couple of minutes)
- There is no specific tag for the deepslate variant of ores. The ores and deeplsate are both tagged under #c:%s_ores. (Maybe we should add it but I don't see the purpose)

**Comment by Orygeunik** [comment]
@Azercoco  @Technici4n big thank for you. You are very responsive and humanable!
Thanks for quick and comprehensive answers!

**Comment by Azercoco** [comment]
The gear tag has been added ... but I don't think any mod add gears since astromine was discontinued.
Thank you too for reporting this issue. Finding forgotten tag can be a real pain.
