### ISSUE TITLE
[BUG] Steam Quarry entry in book has no instructions

### ISSUE THREAD

**Issue by Xlaits** [AztechMC/Modern-Industrialization#101]
The Steam Quarry entry in the book has no instructions other than "it's a multiblock structure."

**Comment by TrueCP6** [comment]
Seems fine to me on the latest commit
![image](https://user-images.githubusercontent.com/39642832/129853007-59f29a46-2c24-4c66-9997-61c6f891ba07.png)

**Comment by Technici4n** [comment]
As you can see on the right of the picture, you should read the coke oven entry to understand how to view the shape of multiblocks and which blocks are required.
