### ISSUE TITLE
Machines Don't Respond to Levers?

### ISSUE THREAD

**Issue by Raavea** [AztechMC/Modern-Industrialization#108]
Hiya,
   So far I am super loving the mod! I've just started working with the polarizer and assembler, and I wanted to be able to switch them off with a lever, but it doesn't seem like they respond to lever position at all.

  Is this an intentional part of the mod, or just not something you'd considered? 
  
  _Essentially I have a box with a lot of ingredients and I have connected it to both of the aforementioned machines; but the polarizer eats all the steel rods before they get into the assembler, so I thought I'd add a lever and switch it off - but that doesn't seem to work with either._

**Comment by Technici4n** [comment]
Glad to hear you are enjoying the mod!

No redstone control or output has been implemented for the moment. We have some plans, but nothing short-term. One thing you can do (in 1.17) is changing the capacity of some slots. So for example you could limit the number of steel rods that go into the polarizer by adjusting the capacity of the input slot.

**Comment by Raavea** [comment]
That's what I've ended up doing so far. Glad it's not a bug, as so far the mod works splendidly. :)

I'm just inching towards the electric blast furnace now. Really great work on the mod, if I wasn't currently unemployed I'd drop you guys a tip. It's really been keeping my attention off my anxieties, so big love for it <3
