### ISSUE TITLE
Steel Barrel

### ISSUE THREAD

**Issue by JFMillerUSA** [AztechMC/Modern-Industrialization#110]
How to use?

**Comment by guest256** [comment]
you need to use item pipes for input and output

**Comment by Azercoco** [comment]
You can interact with them with pipe, hopper or can you use them in your inventory like a bundle.

**Comment by JFMillerUSA** [comment]
They do not work with any kind of pipes?

**Comment by Azercoco** [comment]
Yes they do

**Comment by JFMillerUSA** [comment]
Is it because I'm trying  to transfer from a Charm:crate
