### ISSUE TITLE
Crash when left clicking a tank onto an output fluid hatch

### ISSUE THREAD

**Issue by duncanwebb** [AztechMC/Modern-Industrialization#124]
Modern-Industrialization-0.4.0-alpha.10
fabric-api-0.34.6+1.16

I was trying to prime an output hatch on the drilling rig with shale oil and when clicking the tank containing shale oil on the fluid symbol in the output hatch, the game crashes.

The idea was to define which route the output from the drilling rig went, crude oil coming from one output hatch and shale oil from another. More important with the distillation tower and its eleven outputs.

Upgrading the all of fabric pack from 2.8.3 to 2.8.5, but this version wouldn't play my world (might be caused by Windows 7, I can only play AoF3 hen it is started immediately after a reboot)

Another behaviour that is most like caused by AE2, it that the mixer allows items in when the interface is set to blocking mode. Making more than 64 n-doped or p-doped silicon, the silicon plates go into the first slot, the tiny dust into the second slot and a single silicon plate into the third slot, when the recipe completes, there is a single tiny dust in the storage. I'll can test the blocking behaviour against a chest. I'm only asking about this here in case you already know of this behaviour.

**Comment by Technici4n** [comment]
Can you provide the crash log?

Regarding blocking mode, it's not reliable at all and we (AE2 team) are looking into a better way of doing it.

**Comment by duncanwebb** [comment]
No problem.
[crash-2021-09-08_16.55.33-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/7130515/crash-2021-09-08_16.55.33-client.txt)

**Comment by duncanwebb** [comment]
Maybe with AE2, it should not insert a recipe until the complete recipe can be inserted, which would work well with modern industrialization. The only recipes that cause problems is stainless-steel and Invar, and the stainless-steel recipe can be reliable is iron and nickel are inserted last.

A problem for me to test any changes is that with newer versions of the pack after 2.8.3 is that the world load to 100% but does not join the world.

**Comment by Technici4n** [comment]
This looks like a bug with the fluid handling in 1.16. Unfortunately we don't provide support 1.16 anymore.

Regarding blocking mode: that will be possible with the new item handling in 1.17 fabric. Maybe I will implement it that way, but for now I am busy with other things. :P
