### ISSUE TITLE
How to use the Heat Exchanger

### ISSUE THREAD

**Issue by duncanwebb** [AztechMC/Modern-Industrialization#125]
How do you use the Heat Exchanger? The manual is a bit vague about how it is used.

I have this setup and cannot see where the heat exchanger is used.

![2021-09-08_18 28 01](https://user-images.githubusercontent.com/4198031/132550188-81829ca9-b71e-4d5d-9927-81379f23053c.png)

**Comment by Technici4n** [comment]
This is a crafting machine like all others. You just need to place the required hatches in the correct locations. (Highlighted when you hold a hatch)

**Comment by duncanwebb** [comment]
The manual says that the large stream turbine does not give back HP water, and the heat exchanger should be used to recover some of this. I'm trying to figure out where to extract the heat, the turbine does not accept fluid output hatches.

Is this something that should be between the boiler and pressurizer?

**Comment by Technici4n** [comment]
You can use the heat exchanger to turn HP steam into regular steam before feeding that to the large steam turbine. Otherwise the energy cost of producing HP water is too high.

**Comment by duncanwebb** [comment]
Thanks.
