### ISSUE TITLE
Cannot convert MV Energy Input Hatch to Output

### ISSUE THREAD

**Issue by duncanwebb** [AztechMC/Modern-Industrialization#126]
Most fluid, item and energy hatches can be placed in a crafting grid and converted from input to output and visa versa.

The MV energy hatches cannot be converted this way.

![image](https://user-images.githubusercontent.com/4198031/132834115-edac39ba-d7e2-429f-a07a-3647a4836803.png)

Also crafting transformers always gives higher to lower voltage versions, i.e. MV-HV and HV-MV always gives MV-HV.

![image](https://user-images.githubusercontent.com/4198031/132833841-23911bcc-8661-4b33-8898-e2627cf3e430.png)

![image](https://user-images.githubusercontent.com/4198031/132833927-3bdc8fc9-ac7f-475f-8dbb-5b46acd8a9da.png)

I've checked the closed issues and the changelog to see if this is fixed.

**Comment by Technici4n** [comment]
Fixed in 1.17 :P

**Comment by duncanwebb** [comment]
Great, sorry for reporting the error.
