### ISSUE TITLE
Client crash when using hammer on Copper ingots for Copper Plates

### ISSUE THREAD

**Issue by Lionexx** [AztechMC/Modern-Industrialization#127]
When using a hammer+copper ingots in a crafting table to make copper plates, the client crashes. 

Here is the crash report

https://paste.ee/p/zIbMB

**Comment by Lionexx** [comment]
Not the largest issue as you can just use the forge hammer, but making note about it.

**Comment by Technici4n** [comment]
Industrial Revolution issue, MI doesn't have crafting tools.
