### ISSUE TITLE
Crash trying to use the 3x3 mining drill

### ISSUE THREAD

**Issue by alexmozaidze** [AztechMC/Modern-Industrialization#128]
Whenever I have that thing in my hands, the outline of blocks appears in a wrong spot (and doesn't work with custom block outlines, but it crashes without it anyway), whenever I try to use it, it freezes for some time and crashes. I'm on 1.17.1, with mods such as Sodium 0.3.2 and Indium 1.0.0, the crash happens both with the actions build version and modrinth version of MI

**Comment by Technici4n** [comment]
Crash log?

**Comment by alexmozaidze** [comment]
Here's the crash log and a screenshot of the hitbox
https://drive.google.com/file/d/11MmYz78pd_m_1GImf4djwf3AK6h8m4I9/view?usp=sharing
![2021-09-16_14 01 03](https://user-images.githubusercontent.com/51371527/133594309-f4b255fa-15e7-4de3-816d-5acdcc89f367.png)

**Comment by Technici4n** [comment]
Apparently this is an error in paradox slabs. I suggest you uninstall that.
