### ISSUE TITLE
Large Steam Turbine (Could just be unclear wording in the guide)

### ISSUE THREAD

**Issue by Skid-Inc** [AztechMC/Modern-Industrialization#129]
The wording in the book implies the large steam turbine is meant to output water (just not HP water) "However it will not give you back (HP) water.". If it just doesn't give back water of any sort, the (HP) isn't needed, if it does, then the multi-block currently doesn't seem accept Fluid Outputs of any sort in any position meaning you can't get water back from it.

I have checked this in the most recent version.

**Comment by Technici4n** [comment]
The water -> HP water conversion is very expensive, so you should use an heat exchanger to make the turbine void water and not HP water.

**Comment by Skid-Inc** [comment]
I know how it works, my point is as follows.

No other steam turbine gives you back water of any kind, nor do they mention that they don't. Yet the guide explicitly calls out that the Large Steam Turbine doesn't give back **"(HP)"** water. The fact HP is explicitly called out leaves open the inference that it does give back normal water, regardless as to if you give it HP steam or normal steam, and this is how GregTech's turbines worked, to let you create a closed loop system. I made this inference myself because of those 2 facts, this mod is inspired by GregTech, and the fact that rather then just saying "However it will not give you back water.", it calls HP water explicitly.

Which leads back to my original post, either the text in the guide is unclear and open to interpretation, or the multi-block wasn't working correctly. Your response indicates it was the former.

**Comment by Technici4n** [comment]
Oh. I meant to say "However it will not give you back water nor HP water". I'll make this clearer soon, please leave the issue open in the meanwhile! :)
