### ISSUE TITLE
Fluids don't render in containers on "Fabulous!" graphics

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [AztechMC/Modern-Industrialization#135]
**MC** 1.17.1
**Fabric API** fabric-api-0.40.8+1.17
**MI** Modern-Industrialization-0.6.0-alpha.02
**REI** RoughlyEnoughItems-6.0.287-alpha
**Architectury API** architectury-2.5.32

1. Place any tank down
2. Fill it with fluid by any means (I did with buckets)

Expected result: fluids render inside tanks

Actual result: tanks appear empty

Latest.log: [latest.log](https://github.com/AztechMC/Modern-Industrialization/files/7350715/latest.log)

Originally detected the issue with Industrial Revolution [here](https://github.com/GabrielOlvH/Industrial-Revolution/issues/330) then discovered that it happens with all industrial mods I use. In case of Industrial Revolution, only lava renders inside fluid containers. In case of Modern Industrialization, no fluids render at all. Tested all mods separately to exclude the possibility of an incompatibility between them.

**Comment by Technici4n** [comment]
Tbh this is never going to be fixed. Fabulous mode is very badly implemented and causes all sorts of issues with mods.
