### ISSUE TITLE
Crash when someone placed a pipe near me.

### ISSUE THREAD

**Issue by lilrichy** [AztechMC/Modern-Industrialization#137]
On a server with Mod pack "All of Fabric 4" my teammate placed a pipe and my game crashed to desktop with following crash log.

 #https://gist.github.com/lilrichy/95b90a9ceb82b85497a84d912b850b76

He did not crash only me. He also says that everything seems to appear fine on his end. When logging back into server it insta crashed again over and over same crash log just different POS of pipes "line 8" until he broke all the pipes in the area.
After logging in pipes from "Industrial Revolution, and Fluix Cables from Applied Energistics 2" had textures unconnected and a lot of blocks were not rendered "looked see through"  f3+a fixed the see through blocks but the pipes are still randomly unconnected. This only seemed to affect pipes/cables in and around the same chunk as the pipes that caused the crash.

![Screenshot 2021-10-16 041611](https://user-images.githubusercontent.com/8129775/137580206-56c4a961-0048-4190-b409-96859fe98f8a.png)
![Screenshot 2021-10-16 041833](https://user-images.githubusercontent.com/8129775/137580224-0d1e44cb-dc67-412f-9eb9-06de687f125e.png)
![Screenshot 2021-10-16 041931](https://user-images.githubusercontent.com/8129775/137580259-23a00130-4e87-478a-8730-6c84f66f5f2e.png)
![Screenshot 2021-10-16 042014](https://user-images.githubusercontent.com/8129775/137580286-0c7a797a-5942-4265-a9db-78b934d69dc0.png)
![Screenshot 2021-10-16 042943](https://user-images.githubusercontent.com/8129775/137580534-94a1168e-2d9e-47a0-bd00-d2efbfd24e4c.png)
![Screenshot 2021-10-16 043254](https://user-images.githubusercontent.com/8129775/137580610-36be76e6-895f-4111-a0e4-8438a5259ea2.png)

So idk if this is a mod conflict or if this is a bug from this mod since this is what seemed to crash the game.

**Comment by fwolle30** [comment]
Well it is what the server sends to the client (in this case a null), but because the pipe blocks got destroyed, there is still an entry in ``modern_industrialization_pipe_networks.dat``, wich leads to an error like this:


![](https://user-images.githubusercontent.com/8129775/137580286-0c7a797a-5942-4265-a9db-78b934d69dc0.png)

**Comment by Technici4n** [comment]
Well yes, but destroying the pipe blocks wasn't necessary I think?
