### ISSUE TITLE
Include block state information files

### ISSUE THREAD

**Issue by dragonmaus** [AztechMC/Modern-Industrialization#14]
Would it be possible to include proper block state files in `<jar>/assets`?

Specifically, this is needed in order for [BlueMap](https://github.com/BlueMap-Minecraft/BlueMap) to be able to render MI's blocks.

More information can be found [here](https://minecraft.gamepedia.com/Model#Block_states), [here](https://fabricmc.net/wiki/tutorial:blockstate#adding_models_for_your_blockstates), and [here](https://github.com/BlueMap-Minecraft/BlueMap/wiki/Configuring-mods#infos-for-modders).

**Comment by Technici4n** [comment]
Does it have support for fabric's rendering API ?

**Comment by Technici4n** [comment]
I'd say probably not, so it's useless considering it wouldn't render pipes and machines correctly.
