### ISSUE TITLE
Game crashes after moving into certain area of world

### ISSUE THREAD

**Issue by PollyPlayz** [AztechMC/Modern-Industrialization#140]
Playing the [All of Fabric 4](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-4) modpack and after i walked into a certain area of the world on the server, my game crashes and every time i try to get on the server it crashes

[crash-2021-10-21_19.10.10-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/7391988/crash-2021-10-21_19.10.10-client.txt)

Here is a crash report

**Comment by Technici4n** [comment]
Install indium, or uninstall sodium/iris.
