### ISSUE TITLE
REI Indication of hatch level required for recipe

### ISSUE THREAD

**Issue by KekNite** [AztechMC/Modern-Industrialization#141]
as the title says, the recipe exists but it does smelt the alloy dust.

**Comment by ImUrX** [comment]
By steel tier you mean the electric one, right? Can you fix the REI recipe that says it can be done with the normal one?

**Comment by Technici4n** [comment]
> Can you fix the REI recipe that says it can be done with the normal one?

I'm going to add a warning saying that it needs at least one non-bronze hatch, good idea thanks.

**Comment by cfsf444dw** [comment]
HI, i have the same problem with the SBF, i have 2 inlet fluid hatch and 1 output fluid hatch empty, but putting the soldering alloy dust the SBF doesn't start... please check

**Comment by Rakkis157** [comment]
> HI, i have the same problem with the SBF, i have 2 inlet fluid hatch and 1 output fluid hatch empty, but putting the soldering alloy dust the SBF doesn't start... please check

Are any of those hatches Steel Hatches?

**Comment by cfsf444dw** [comment]
> > HI, i have the same problem with the SBF, i have 2 inlet fluid hatch and 1 output fluid hatch empty, but putting the soldering alloy dust the SBF doesn't start... please check
> 
> Are any of those hatches Steel Hatches?

NO... i will update it immeditely.. sorry.. i've understund just now the previus comment
