### ISSUE TITLE
Funky Ui when Texture Packs makes it Transparent

### ISSUE THREAD

**Issue by JiroCab** [AztechMC/Modern-Industrialization#147]
**Mc**: 1.17.1
**Fabric Api**: 0.41.0
**Mi**: 0.6.0
**Rei**: 6.0.279
**architectury**: 2.6.35
**Texture pack**: [Bleached-Fabric-v1-2_Custom.zip](https://github.com/AztechMC/Modern-Industrialization/files/7421398/Bleached-Fabrir-v1-2_Custom.zip)

Steps to reproduce
1.  Open minecraft with provided Texture pack enbled
2.  Open pretty much any Ui from the mod

_Note: screenshoots are taken with nothing but mods above, so Sodium is ruled out & I doubled check that everything is textured properly and it is_
![2021-10-27_04 17 58](https://user-images.githubusercontent.com/57391931/138957426-01eb9240-a5d2-4c88-9c8b-e3a1e0783575.png)
![2021-10-27_04 17 20](https://user-images.githubusercontent.com/57391931/138957436-6f4c4153-a41c-4274-9f62-377635801ae3.png)
![2021-10-27_04 17 33](https://user-images.githubusercontent.com/57391931/138957438-a87f0e26-a526-4e4b-a677-3c989c292b3c.png)
![2021-10-27_04 17 35](https://user-images.githubusercontent.com/57391931/138957442-522a80af-c7ab-4d32-8552-3bb32ee399e3.png)
![2021-10-27_04 17 36](https://user-images.githubusercontent.com/57391931/138957447-8c5b7622-f29f-44f7-961d-7db049b95b3a.png)
![2021-10-27_04 17 54](https://user-images.githubusercontent.com/57391931/138957449-a910aac1-76ef-4a05-b71e-19e687506390.png)

**Comment by Technici4n** [comment]
Finally fixed this, sorry about the delay!
