### ISSUE TITLE
Item Pipe Rendering

### ISSUE THREAD

**Issue by ProfTechnology** [AztechMC/Modern-Industrialization#150]
Here are the information to that:

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 31/10/2021, 15:42
Description: Tesselating block in world - Indigo Renderer

java.lang.NullPointerException: Null attachment for pipe rendering! This is not supposed to happen!
Pos: class_2339{x=1064, y=64, z=1054}
State: Block{modern_industrialization:pipe}
	at aztech.modern_industrialization.pipes.impl.PipeModel.emitBlockQuads(PipeModel.java:102)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:105)
	at net.minecraft.class_846$class_851$class_4578.redirect$zzg000$hookChunkBuildTesselate(class_846.java:723)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:524)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:447)
	at net.minecraft.class_846$class_851.method_22781(class_846.java:412)
	at net.minecraft.class_846.method_3627(class_846.java:189)
	at net.minecraft.class_761.method_3273(class_761.java:918)
	at net.minecraft.class_761.method_22710(class_761.java:1142)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at aztech.modern_industrialization.pipes.impl.PipeModel.emitBlockQuads(PipeModel.java:102)

-- Block being tesselated --
Details:
	Block: Block{modern_industrialization:pipe}
	Block location: World: (1064,64,1054), Section: (at 8,0,14 in 66,4,65; chunk contains blocks 1056,0,1040 to 1071,255,1055), Region: (2,2; contains chunks 64,64 to 95,95, blocks 1024,0,1024 to 1535,255,1535)
Stacktrace:
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:105)
	at net.minecraft.class_846$class_851$class_4578.redirect$zzg000$hookChunkBuildTesselate(class_846.java:723)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:524)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:447)
	at net.minecraft.class_846$class_851.method_22781(class_846.java:412)
	at net.minecraft.class_846.method_3627(class_846.java:189)
	at net.minecraft.class_761.method_3273(class_761.java:918)
	at net.minecraft.class_761.method_22710(class_761.java:1142)
	at net.minecraft.class_757.method_3188(class_757.java:1026)

-- Affected level --
Details:
	All players: 1 total; [class_746['Xeo7mer'/6546, l='ClientLevel', x=1068.56, y=63.00, z=1057.12]]
	Chunk stats: 729, 239
	Level dimension: minecraft:overworld
	Level spawn location: World: (187,70,-16), Section: (at 11,6,0 in 11,4,-1; chunk contains blocks 176,0,-16 to 191,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 41154675 game time, 43877774 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, linkedstorage/enderstorage, Unity-1.17.X-Dark-0.7.0.zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.14.14-arch1-1
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 742500496 bytes (708 MiB) / 1929379840 bytes (1840 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen Threadripper 2920X 12-Core Processor
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): -0,00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 24
	Graphics card #0 name: GP106 [GeForce GTX 1060 6GB]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288,00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
	Graphics card #1 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #1 VRAM (MB): 258,00
	Graphics card #1 deviceId: 0x731f
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 32391,36
	Virtual memory used (MB): 4921,90
	Swap memory total (MB): 16383,00
	Swap memory used (MB): 0,00
	JVM Flags: 2 total; -Xms512m -Xmx10240m
	Fabric Mods: 
		adorn: Adorn 2.2.0+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.10
		advancednbttooltip: Advanced NBT Tooltips 1.6.0+build.4-1.17
		advancementinfo: AdvancementInfo 1.17.1-fabric0.36.1-1.2.1
		ae2wtlib: AE2WTLib ${version}
		agape_space: Space Dimensions 0.3.4
		alloy_forgery: Alloy Forgery 2.0.3
		appliedenergistics2: Applied Energistics 2 9.0.0-alpha.8
		architectury: Architectury 2.5.32
		artofalchemy: Art of Alchemy: Memoriam 1.2.0+1.17.1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		blockshifter: Blockshifter 1.4.0+fabric-1.17.1
		cardinal-components-base: Cardinal Components API (base) 3.0.1
		cardinal-components-entity: Cardinal Components API (entities) 3.0.1
		cardinal-components-item: Cardinal Components API (items) 3.0.1
		carrier: Carrier 1.8.0
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		colorutility: ColorUtility 2.0.1
		com_madgag_animated-gif-lib: animated-gif-lib 1.4
		completeconfig: CompleteConfig 1.1.0
		croptopia: Croptopia 1.6.1
		customportalapi: Custom Portal Api 0.0.1-beta45-1.17
		customsplashscreen: Custom Splash Screen 1.1.0
		dankstorage: Dank Storage 2.2.1-1.17.1
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		emagnet: E Magnet 1.2.3
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		enhanced_quarries: Enhanced Quarries 1.2.0_RC7
		environmentalcreepers: Environmental Creepers 1.6.0
		fabric: Fabric API 0.41.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.0+57bef5a318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-furnaces: Fabric Furnaces 2.0.1-1.17
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.11+7931163218
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+7931163218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+7931163218
		fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+7931163218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+7931163218
		fabrichomes: FabricHomes 2.0.0
		fabricloader: Fabric Loader 0.11.6
		fabrictailor: Fabric Tailor 1.7.1
		fallingtree: FallingTree 2.12.1
		fancymenu: FancyMenu 2.3.2
		fasttransferlib: Fast Transfer Lib 0.5.6
		ferritecore: FerriteCore 3.0.3
		fiber: fiber 0.23.0-2
		fluidtank: Fluid Tank 17.1.2-fabric
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.9
		gearreborn: Gear Reborn 1.17-0.1.10
		geckolib3: Geckolib 3.0.19
		glassdoor: Glass Doors 1.5.0-1.16
		hctm-base: HCTM Base 3.6.2
		hologram-api: Hologram API 0.2.1+1.17.1
		holographic_renders: Holographic Renders 1.0.1
		illuminations: Illuminations 1.7
		improved-stations: Improved Stations 2.0.7
		inmis: Inmis 2.3.2-1.17.1
		inspecio: Inspecio 1.1.0+1.17
		iron-jetpacks: Iron Jetpacks 0.4.1
		ironchest: Iron Chests 1.2.0+fabric-1.17.1
		itemmodelfix: Item Model Fix 1.0.2+1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 16
		kibe: Kibe 1.9.3-BETA+1.17
		konkrete: Konkrete 1.3.0
		lazydfu: LazyDFU 0.1.2
		lchunkloader: Literally Chunk Loader 2.0.3
		libaddict: libaddict 0.3.0
		libblockattributes: LibBlockAttributes 0.9.2
		libblockattributes_core: LibBlockAttributes (Core) 0.9.2
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.2
		libblockattributes_items: LibBlockAttributes (Items) 0.9.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.7+1.17.1
		liblib-albedo: LibrarianLib: Albedo 5.0.0-alpha.10
		liblib-core: LibrarianLib: Core 5.0.0-alpha.10
		liblib-courier: LibrarianLib: Courier 5.0.0-alpha.10
		liblib-etcetera: LibrarianLib: Etcetera 5.0.0-alpha.10
		liblib-facade: LibrarianLib: Facade 5.0.0-alpha.10
		liblib-glitter: LibrarianLib: Glitter 5.0.0-alpha.10
		liblib-mosaic: LibrarianLib: Mosaic 5.0.0-alpha.10
		liblib-scribe: LibrarianLib: Scribe 5.0.0-alpha.10
		libmultipart: LibMultiPart 0.6.0
		libnetworkstack: Lib Network Stack 0.5.0
		libninepatch: LibNinePatch 1.1.0
		librarianlib: LibrarianLib 5.0.0-alpha.10
		lifts: Lifts 1.3-BETA+1.17
		lightestlamp: Lightest Lamps 0.9.3
		lightningprevention: Lightning Prevention 1.0.0
		lightoverlay: Light Overlay 6.0.1
		linkedstorage: Linked Storage 1.3.13-1.17
		lithium: Lithium 0.7.4
		magna: Magna 1.5.5-1.17-pre4
		megane: megane 5.5.0
		megane-applied-energistics-2: megane-applied-energistics-2 5.5.0+9.0.0-alpha.2
		megane-base: megane-base 5.5.0
		megane-fabric-transfer: megane-fabric-transfer 5.5.0+1.3.0-fc40aa9d18
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.5.0+0.5.7
		megane-kibe: megane-kibe 5.5.0+1.9.1-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.5.0+0.9.0
		megane-modern-industrialization: megane-modern-industrialization 5.5.0+0.5.12
		megane-reborn-core: megane-reborn-core 5.5.0+5.0.8-beta-build.111
		megane-runtime: megane-runtime 5.5.0
		megane-team-reborn-energy: megane-team-reborn-energy 5.5.0+2.0.0-beta1
		megane-tech-reborn: megane-tech-reborn 5.5.0+5.0.8-beta-build.111
		megane-vanilla: megane-vanilla 5.5.0+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.5.0+1.3.0
		minecraft: Minecraft 1.17.1
		mining_dims: Mining Dimensions 1.1.13
		mo_glass: Mo Glass 1.5-MC1.17.1
		modern_industrialization: Modern Industrialization 0.6.0
		modmenu: Mod Menu 2.0.14
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		myron: Myron 1.6.1-1.17.1
		omega-config: OmegaConfig 1.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_msgpack_msgpack-core: msgpack-core 0.8.16
		owo: OwO 0.1
		packet_tweaker: Packet Tweaker 0.2.0+1.17.1
		patchouli: Patchouli 1.17.1-56-FABRIC
		pipe: Pipe 1.4.0
		placeholder-api: Placeholder API 1.1.2+1.17.1
		platforms: Platforms 1.1.1
		player-data-api: Player Data API 0.1.0+1.17.1
		playerabilitylib: Pal 1.3.0
		polymer: Polymer 0.1.8+1.17.1
		qcommon-cfg-core: qcommon-cfg-core 3.3.0
		qcommon-croco: Croco 2.1.1
		quarrymod: Industial Quarry Mod 0.5.0
		quartzelv: Quartz Elevator 1.2.5
		reborncore: Reborn Core 5.0.8-beta+build.111
		rightclickharvest: Right Click Harvest 1.4.0
		roughlyenoughitems: Roughly Enough Items 6.0.306-alpha
		rswires: RSWires 4.11.2
		server_translations_api: Server Translations API 1.4.6+1.17
		sgui: SGui 1.0.0-rc4+1.17.1
		shetiphiancore: ShetiPhianCore 1.1.1
		silk: Silk API 1.2.4-43
		simple_pipes: SimplePipeTest 0.6.1
		simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.6.1
		spatialharvesters: Spatial Harvesters 0.11.12c
		stockpile: Stockpile 1.1.5+1.17.1
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.0.9-beta+build.131
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		traverse: Traverse 4.0.0-beta.2
		trinkets: Trinkets 3.0.4
		universal-graves: Universal Graves 1.1.3+1.17.1
		waystones: Waystones 2.1.1
		wirelessnetworks: Wireless Networks 1.1.2
		woods_and_mires: Woods and Mires 1.1.1+1.17
		worldmesher: Worldmesher 0.1
		wthit: wthit 3.10.0
		xaerominimap: Xaero's Minimap 21.20.0
		xaeroworldmap: Xaero's World Map 1.18.0
		xp_storage: XP Storage 1.4.2+1.17.1
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon RX 5700 XT (NAVI10, DRM 3.42.0, 5.14.14-arch1-1, LLVM 12.0.1) GL version 4.6 (Core Profile) Mesa 21.2.4, AMD
	Window size: 2558x1437
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, linkedstorage/enderstorage, file/Unity-1.17.X-Dark-0.7.0.zip
	Current Language: English (US)
	CPU: 24x AMD Ryzen Threadripper 2920X 12-Core Processor
#@!@# Game crashed! Crash report saved to: #@!@# /home/paul_althaus/.local/share/multimc/instances/1.17.1/.minecraft/crash-reports/crash-2021-10-31_15.42.23-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Der Prozess wurde mit Status 255 beendet.

**Comment by Technici4n** [comment]
Hello, could you please provide your full log?
