### ISSUE TITLE
Changes for easier texture creation

### ISSUE THREAD

**Issue by Falkory220** [AztechMC/Modern-Industrialization#153]
List of things that if changed would make making textures far easier:
-Have different overlays for the same machine in different tiers or at least let me change colours on them
-Separate "side" overlay into "left", "right", "back"
-Casings taking from the "textures/blocks/casings" file instead of just machines
-Change textures if they are part of a multiblock
-being able to make parts of textures emissive so they glow in the dark
I'll update this list if i run into any other issues

**Comment by Technici4n** [comment]
We will implement what's still missing as we work on incorporating the new textures.
