### ISSUE TITLE
[Suggestion] Config to reverse required sneaking status interacting with MI barrels

### ISSUE THREAD

**Issue by ChromaPIE** [AztechMC/Modern-Industrialization#156]
Now by default the barrel gives a single item per click when sneaking and a whole stack when not. So is it possible to introduce a config to reverse it so that players get a stack when sneaking and one item when not, just like Storage Drawers drawers' default behavior?

**Comment by Technici4n** [comment]
We can consider changing the behavior altogether, no need for config in that case.

**Comment by ChromaPIE** [comment]
That'd be good too

**Comment by Technici4n** [comment]
Apparently the current behavior is already the right one... Not sure what happened, but it seems fixed on master, so closing.
