### ISSUE TITLE
[0.7.0-alpha.01] Having a Steam Mining Drill in a player's inventory corrupts player data and kicks the player

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [AztechMC/Modern-Industrialization#161]
**MC** 1.17.1
**MO** 0.7.0-alpha.01
**Fabric** loader 0.12.5; API 0.43.0

To reproduce:

1. Connect to a server (the world can be either newly generated or an old one)
2. Give yourself a Steam Mining Drill
3. Get kicked, try to join back - get kicked again; repeats indefinitely unless the player's data is deleted or manually edited to remove the drill

Rolling back to 0.6.1 helps. The bug doesn't happen in single-player worlds.

Logs: https://gist.github.com/Footage2-Amply-Pounce/314c5ab94c7d3a7ae4558e78cc1f03ea

**Comment by Technici4n** [comment]
Will be in alpha 2 in a few minutes, thanks!
