### ISSUE TITLE
Advancement to prevent people using AE2

### ISSUE THREAD

**Issue by Technici4n** [AztechMC/Modern-Industrialization#163]
We should add an advancement for when you place a pattern provider on an MI electric machine saying "don't do that". Otherwise people will complain that recipes take forever, but that's just because they try to autocraft them.

**Comment by bindwkill** [comment]
I haven't noticed this issue with the pattern providers, but I think an advancement is needed for FE p2p tunnels as it is impossible to convert the power back for MI machines.

**Comment by Technici4n** [comment]
That's how it goes with any energy cable from other mods though, not sure this is specific to p2p tunnels. Whereas people are just used to setting up autocrafting to solve every single problem.

**Comment by KaneHart** [comment]
Honestly I don't think we should be Bloating MI with other Mods Features like that. This would end up becoming something might need to be adjusted / fixed down the road and heading down the road of adding tons of unneeded bloat haha.
