### ISSUE TITLE
Forge Hammer rework

### ISSUE THREAD

**Issue by Technici4n** [AztechMC/Modern-Industrialization#166]
To reduce early game microcrafting and suboptimal part ratios before machines, we are planning on reworking the forge hammer. Crafting or machine recipes should not be affected.

- Turn the forge hammer into a block similar to the stone cutter: you place ingots, and you pick which output you want to craft. This means that even complex parts like gears could be crafted in one click.
- To mitigate the bad ratio you get in the forge hammer, you will have the option to place a tool in the forge hammer that will get damaged, but in exchange yield a much better conversion ratio.

This will come some time after the initial 1.0 release for 1.18.

**Comment by Azercoco** [comment]
Closes with 5d9568091fa992e9cb09f7d5075a8830c0356f3e
