### ISSUE TITLE
Agriculture system

### ISSUE THREAD

**Issue by Technici4n** [AztechMC/Modern-Industrialization#169]
There have been a few requests for an agriculture system. We don't want to go for something similar to MFR. If you want that, you can install Indrev and power it with MI generators.

The idea would instead be to introduce a crop breeding system similar to IC2's, and a machine to harvest crops. There would also be some way to accelerate crop growth through fertilizer. I have never played with IC2's crop system though, so I only know very little about it.

**Comment by Casmin7** [comment]
Can we have a sprinkler that stays flush with water fluid pipes to speed up growth?

**Comment by Technici4n** [comment]
I don't think that would be particularly interesting gameplay-wise. Would probably be a better fit for a mod like Kibe.

**Comment by Casmin7** [comment]
That is when it is relesed

**Comment by Casmin7** [comment]
Also whould love for a agricultury craft system.

**Comment by Rakkis157** [comment]
I wonder how practical it would be to have the farming stations, or at least the higher tier machines, be multiblock structures. I've always wanted to build a functional combine harvester in Minecraft.

**Comment by Rakkis157** [comment]
Haven't played IC2 styled farming myself. Only experience I have with it is from watching Etho's Project Ozone playthrough, where he had a location for developing new crops, a location for getting the crops to max level, and a location for the actual farming. The last two used separate machines.

That said, the machine used in that playthrough was the Ender IO farming station with an addon that lets it make use of cropsticks.

**Comment by KaneHart** [comment]
A Mix of IC2 Crops and AgiCrops to me is quite a Must especially if it offers customization for ModPack Makers. That being said as much as I grew up on IC2 Crops I did not like the Chaos of them as much... I also was never a big fan of the cheated resources as much... GTNH did it more Interesting in recent times instead you got sort of items to mix in with say Iron to give a higher yield vs just a Iron Plant.

I also have a big thing for Green Houses something I did not get to enjoy too much mostly playing in 1.7.10 was the Forestry Green Houses. It be really nice to power Green Houses and change Climate and not Punish the user for living in a Snow Biome vs having to live 120 Blocks above a Swamp LOL

**Comment by Technici4n** [comment]
> you got sort of items to mix in with say Iron to give a higher yield

that's kinda useless in MI since you might as well overclock your quarry, unless we make the plant ratios so absurd (like x5 or x10) that they are more interesting than spending the extra energy on the quarry
