### ISSUE TITLE
Pipe Block, Report This

### ISSUE THREAD

**Issue by SirKnightBJ** [AztechMC/Modern-Industrialization#171]
One of the player's on my server found this fun little oddity.

No Matter what I do, all surrounding tin cables try to connect to this invisible block. I can destroy it, but the cables still try to connect to it. When ever I try to lay a tin cable in those spaces, the empty little cube shows back up. I've tried to remove it with worldedit //set air I've also tried to use /setblock x y z air but no matter how i try to remove or replace the data that is in those blocks, the tin cables still try to connect. Any idea how to fix this?

![2021-11-30_00 47 32](https://user-images.githubusercontent.com/1690932/143999805-4190a45e-3d1c-4782-ae9d-0895f8be2453.png)

**Comment by Technici4n** [comment]
Check your client and server logs for some MI error, this is weird. It means that you don't receive the data for the pipe at that position for some reason.

**Comment by SirKnightBJ** [comment]
Well there sure is an MI error in the log lol. Although, I'm not quite sure what to do about it. But right after I rebooted the server last night, I started messing with the pipe again as you will see near the end of the log, the error pops up quite a few times.

https://pastebin.com/295ghzDj

**Comment by Technici4n** [comment]
Hi @SirKnightBJ, I just added a command that should fix this. Can you try to run the `/mi pipes <x> <y> <z> clear` command with this build after enabling MI debug commands? You might have to enable debug commands on the client and the server. It should remove any pipe (including ghost pipes) at the target location.

If you can make a backup before just in case, that's even better.

https://github.com/AztechMC/Modern-Industrialization/actions/runs/1522401652
(the jar can be found in the build artifact at the bottom)

**Comment by SirKnightBJ** [comment]
Awesome Thank you! Work is kind of chaos atm, so I don't think I'll have time to troubleshoot this tonight. Maybe tomorrow ¯\_(ツ)_/¯. If you're on the edge of your seat about the feedback, I can send you the full multi-craft backup. It should only be like 6GB. Let me know! Thanks again!

**Comment by Technici4n** [comment]
It's ok, it can wait for tomorrow! I've released the fix in MI 0.7.3, so updating should be enough to have access to the new command without the need to grab a build from github.

**Comment by Technici4n** [comment]
@SirKnightBJ any update?

**Comment by Technici4n** [comment]
Assuming it's ok, I'm closing this.

**Comment by SirKnightBJ** [comment]
I'm sorry. This month became quite overwhelming at work and I forgot to update you. The update worked great. Thanks for your hard work on these projects! I appreciate all you do for the community.
