### ISSUE TITLE
Upgrade Large Tank

### ISSUE THREAD

**Issue by ExodusR** [AztechMC/Modern-Industrialization#176]
Hello,

With Friends we are playing on All Of Fabric 4 in 1.17.1, and we construct the Large Tank but we dont understand oh we can upgrade the tank ? 
Thank's for you'r responses !

**Comment by Azercoco** [comment]
Just increase the size of the tank (max 7x7x7) without destroying the controller or you will loose its content.

**Comment by ExodusR** [comment]
We have construct the 5x5x5 but it doesn't work we don't understand why

**Comment by Azercoco** [comment]
Could you provide a screen or something that could help us understand where the problem is ?

**Comment by Azercoco** [comment]
Closing it. Reopen if needed
