### ISSUE TITLE
GameCrash with Bronze Item Input Hatch

### ISSUE THREAD

**Issue by DrummerMC** [AztechMC/Modern-Industrialization#180]
The game crash when putting an Bonze Item Input Hatch with Auto-Insertion enabled on an Applied Energistics 2 Interface that contains items and fluids. After the crash the world can't be loaded without a game crash.

Crash-Report:
https://pastebin.com/nBTwtubM

**Comment by Azercoco** [comment]
This seems to be caused by AE2. I would advice to remove the block with world edit while waiting the bug to be fixed.

**Comment by Technici4n** [comment]
The issue was indeed in AE2, I fixed it there. Thanks for your report @DrummerMC. Really cool to see you play with AE2 again, and with MI too. :)
