### ISSUE TITLE
Cutting machine gets stuck on first recipe used

### ISSUE THREAD

**Issue by ZenithAstralis** [AztechMC/Modern-Industrialization#181]
Once a recipe has first been selected for the bronze cutting machine it can't be cleared, which kills the machine for any other type of work unless it's broken and replaced, which deletes the contents.

mod version: 1.0.0
Minecraft version: 1.18.1
modpack: Another Quality Modpack 2 (AQM2-1.18.1-1.3.1.zip)

**Comment by Technici4n** [comment]
If you hit the lock button you can then click on the slots to unlock them. You can also drag the items from REI to lock the slots to something else.
