### ISSUE TITLE
Steam Mining Drill not acceping fuel

### ISSUE THREAD

**Issue by Thraann** [AztechMC/Modern-Industrialization#182]
Hello,

Just playing the mod on single player and just started and build the Steam Mining Drill, I have it filled with water but no matter what fuel I try it doesn't seem to work. Tried Regular Coal, Lignite Coal, and the fuel from the Gobber mod. I have right clicked on the fuel with the Drill, right clicked the Drill with the fuel and tried to right click the drill with the fuel next to it on the hotbar and I am not sure what the issue is. 

Can list mods if necessary, playing on the newest version of the mod.

**Comment by Technici4n** [comment]
I will check but I am pretty sure this works fine with MI alone or even on AOF5. So this has to be a mod conflict. Which mods are you playing with?

**Comment by starhobbit** [comment]
Have the same problem, tried new game without any mods except MI & fabric (last curse versions) and dependencies, that curse client installs. It mine coal and don't consume any water and fuel

**Comment by starhobbit** [comment]
ps. MC 1.18.1

**Comment by starhobbit** [comment]
Is there any info about clicking on fuel, when drill is selected to put fuel into drill? I just find this in source code :) Then problem fixed

**Comment by Technici4n** [comment]
This is how you can put fuel in the drill:
https://user-images.githubusercontent.com/13494793/145802998-c14107c5-f029-476f-a6c8-00416f9012f0.mp4

Explanation in the guidebook:
![image](https://user-images.githubusercontent.com/13494793/145803090-08840984-3307-4de1-a461-863205dcac0d.png)

**Comment by starhobbit** [comment]
> This is how you can put fuel in the drill: https://user-images.githubusercontent.com/13494793/145802998-c14107c5-f029-476f-a6c8-00416f9012f0.mp4
> 
> Explanation in the guidebook: ![image](https://user-images.githubusercontent.com/13494793/145803090-08840984-3307-4de1-a461-863205dcac0d.png)

my fault - i didn't read carefuly

**Comment by Thraann** [comment]
architectury
bclib
better nether
cloth config
fabric api
fabric language scala
fallingtree
gobber2
ironchests
ironfurnaces
largefluidtank
libblockattributes
modern industrialization
mouse tweaks
origins
oxidized
roughlyenoughitems
rpgstats
silk touch spawners
wraith waystones
WTHIT
xaero's minimap and world map
you're in grave danger

This is my list of mods

**Comment by Thraann** [comment]
I figured it out, one of the config settings with Mouse Tweaks was making it not work, I changed the setting and was able to put fuel into the Drill. Thank you for the assistance.

**Comment by Technici4n** [comment]
Np! BTW, I strongly recommend playing with megane for nicer WTHIT displays.
