### ISSUE TITLE
Hammer Durability Costs way too high

### ISSUE THREAD

**Issue by Derpford** [AztechMC/Modern-Industrialization#186]
Based on what I've seen thus far, iron hammers take way too much durability damage to be useful.
For example, one iron hammer only has enough durability to make plates for four more hammers. Having to stop and craft new hammers every 12 plates is absurd, but the alternative is doubling the cost of plates. Even worse, one hammer can only process FIVE ores before breaking! You would need a whopping *13* hammers to process one stack of ores. It also costs a whole iron hammer to create *one* gear.

In other words, to craft one machine, I need to make two hammers--one for the gear, and one for the 8 plates (and another 3 plates so I can have a spare hammer). This is exactly what I was worried about when hammers were introduced--we're drifting back into GregTech-style repetitive tool crafting, which is exactly what this mod was meant to avoid.

There's a couple ways to fix this.
1. Switch to a probability-based system for eating durability. Instead of eating a set amount of durability with each crafting recipe, the hammer has a percentage chance to take durability loss. This would drastically increase the lifetime of the hammer.
2. Just scale all the numbers down, hard. Right now the hammer eats between 10 and 30 durability for each part crafting recipe (depending on how many steps are involved--ingot-to-rod takes 10, but ingot-to-bolts takes 30, 10 for the rod and 10 for each pair of bolts). It also eats 25 durability per ore processed, making ore processing with a hammer nigh-useless for anything but bronze production. If it instead ate 1 durability per part crafting operation and 2 durability per ore processing operation, that would *also* drastically increase the lifetime of the hammer.
3. Remove durability from the hammer entirely, and have it function as an upgrade of sorts. Instead of granting guaranteed high-efficiency recipes for a durability cost, each tier of hammer gives you a percentage chance of getting extra ingredients out, much like macerating ore chunks.
4. Drastically increase both the cost and durability of the hammers, so that you consume the same amount of resources over a much longer time period. For instance, you could make the hammers take dense plates instead, and quadruple the durability of the hammer--thus the amount of iron consumed per operation is technically the same, but I don't have to spend nearly as much time crafting four hammers at a time just to process the rest of this stack of tin.

**Comment by Derpford** [comment]
The steel hammer processes 13 blocks of ore, and the diamond hammer processes half a stack--but you can't get the Steel Hammer until you have a Blast Furnace, and there's no reason not to have the entire suite of Bronze machines at that point, so the Steel Hammer doesn't really have a use unless you just haven't crafted the Cutting Machine or Compressor for whatever reason. Similarly, the diamond hammer can't be crafted at all unless you have a compressor! And even the Netherite hammer can't process a whole stack of ores.

**Comment by Rakkis157** [comment]
Alternatively, having the hammer require blocks, but last 9 times longer could work as well. That would also make the diamond hammer more useful, since someone who wants to enter MI after already establishing themselves beforehand could simply burn 27 diamonds to use it, which when combined with enchanting the hammer would last them a very long while.

**Comment by KaneHart** [comment]
I like the idea of blocks and 9 times longer, but it feels and I'm sure would look "ugly" when crafting it. Honestly I think some fine tuning the durability is not a bad thing. Punishing the Player for being a bit lazy is going make next to no dent in middle / later game honestly. If they want to be lazy and do things by hand I say let them at a bit of a reduce cost.

**Comment by jecowa** [comment]
Hammers breaking quickly was motivation for me to create more machines to make hammers less needed. That's why I built a Compressor and tried to figure out the Cutting Machine. I think it's good to have motivation to minimize use of the Forge Hammer.

**Comment by Derpford** [comment]
We had a motivation for that before--the leaps and bounds in crafting efficiency from making new machines. Sadly, that's no longer feasible due to the recipe changes.

The problem is that the hammers add multiple extra steps to crafting stuff using the Forge Hammer. The resource cost isn't really an issue--that's why I'm fine with the above suggestions of having hammers cost way more in exchange for more durability. 

The issue is that every time my hammer runs low, I need to craft a set of plates, exit the Forge Hammer, grab a couple sticks, find a crafting table, craft a fresh hammer, and then return to what I was doing. Ideally, I'll do three or four spare hammers at a time, but that still means having to shift-click in a new hammer for every gear's worth of parts I craft. All that extra context-switching and item moving makes hammers feel way more costly and tedious than they are from a resource standpoint.

And this goes directly against one of the stated design goals of MI, which is to *avoid* GregTech's unwieldy tool-crafting system. Using tool durability as an additional cost in crafting is a great idea on paper, but GT's implementation mostly just annoyed me, especially since it broke shift-clicking--and the MI implementation isn't much better.

**Comment by Azercoco** [comment]
Closed with #68abf2

**Comment by Azercoco** [comment]
Closed with 68abf21b73bc7e6f921191da8f46f7951bca0e23
