### ISSUE TITLE
Cannot remove bucket from mining drill

### ISSUE THREAD

**Issue by red2blue** [AztechMC/Modern-Industrialization#189]
Latest version of MI on 1.18.1 fabric, using 0.12.11 loader

Players are reporting that they are unable to remove Buckets from Steam Mining Drills. This is reported from players using my modpack, Another Quality Modpack 2. 

![image](https://user-images.githubusercontent.com/35115304/146606409-a7b025d6-72f3-471d-8f3d-f6ebfed97b28.png)

![image](https://user-images.githubusercontent.com/35115304/146606428-445ab0e2-1c84-4007-a40f-01cc69cdae6e.png)

**Comment by Technici4n** [comment]
Just right click with the drill in hand on an empty slot.
