### ISSUE TITLE
Pipe not working on server

### ISSUE THREAD

**Issue by Nggo** [AztechMC/Modern-Industrialization#191]
Hello, I tried to install a Minecraft Server with Fabric and the Modpack "Benchmark 2"
https://www.curseforge.com/minecraft/modpacks/benchmark-ii

But the pipes in Modern Industrialization doesn't work. In my single player world is everything fine.
![image](https://user-images.githubusercontent.com/94854289/146634806-061fdabd-56f5-475a-98ef-ee394811b557.png)

Can someone help me?

**Comment by Technici4n** [comment]
Please send the full client and server logs.

**Comment by Nggo** [comment]
[logs-server.zip](https://github.com/AztechMC/Modern-Industrialization/files/7738980/logs-server.zip)
[logs-client.zip](https://github.com/AztechMC/Modern-Industrialization/files/7738981/logs-client.zip)

**Comment by Technici4n** [comment]
Hmmm, I don't see anything in the logs. Could you try reinstalling indium maybe? That was the fix for a similar issue apparently (AppliedEnergistics/Applied-Energistics-2#5793).

**Comment by Chuunkyz** [comment]
also, i noticed a lot of people have this issue so as you can see i removed the server packs atm for 0.3.4...
what in singleplayer worlds ?

**Comment by Nggo** [comment]
> also, i noticed a lot of people have this issue so as you can see i removed the server packs atm for 0.3.4... what in singleplayer worlds ?

in Singleplayer Worlds work everything fine, I see all the pipes.

**Comment by Chuunkyz** [comment]
fixed in 0.3.5, just released on curseforge !
