### ISSUE TITLE
Bronze Boiler, coal usage way to low?

### ISSUE THREAD

**Issue by AtPMonster** [AztechMC/Modern-Industrialization#192]
Hey guys,

in my eyes the bronze boiler is using about 0 coal if you place it inside. Feels like 1 coal runs for 50 Buckets or something around that, which is a HUGE amount for a simple piece of coal.

Might be interesting to increase the coal usage :)

Greets,

AtP

**Comment by Rakkis157** [comment]
Hmm... as an option you can have on, maybe, but going into the late game things start to get more and more expensive power-wise, where you start burning through coal. Besides, you already have to invest a lot of resources getting started with the mod without needing to also have to deal with power consumption.

**Comment by AtPMonster** [comment]
Yes, I agree. But as you might see, right now 1 coal drops 50 buckets of Steam? Like cmon... Thats insane.

**Comment by Technici4n** [comment]
It will use more if you consume the steam from the boiler. The amount of steam that is produced should match what the EU tooltip says, and yes it's intended that steam is vastly more efficient than making direct use of fuel.

**Comment by KaneHart** [comment]
I wanted to say coming from GT, IC2, GTNH, etc it feels strange and your going find electricity even more crazy with the overclocking on base machines. That being said it's kind of the unique charm of this pack. I'm already running 4 Steel Boilers and eating through coal more now. Starting work on the Multi Block Bronze one now. The best way it's been explained to me is this is Factorio. I bet your 100% your current design has hardly anything automated and if it does I'm assuming it's multi use / shared machines. But the design this pack is actually to have each machine do it's own recipe / function. Once you figure this out and start to scale you will notice how fast Power is not as easy...

I think a lot of the Balance will also work out to fuel items vs quarried out.

Anyways keep at it might feel easy, but I doubt you will find it that way weeks from now hehe :)
