### ISSUE TITLE
[1.18.1] Crash when hovering over steam mining drill in crafting table or in manual 

### ISSUE THREAD

**Issue by thecow275** [AztechMC/Modern-Industrialization#195]
Crashing when hovering over steam mining drill in crafting table or in the ingame MI manual however hovering in REI doesnt cause crash.

Here is the log file for the crash: https://paste.ee/p/1yn8h

**Comment by Technici4n** [comment]
It's a LevelZ bug, please report to them. Thanks!

**Comment by thecow275** [comment]
I have now gone and given them the logfile and will temporarily disable levelz on my modpack as it seems other mods i have are having similiar incompatibilities when looking through their issues.
