### ISSUE TITLE
Block of Coke Coal has a wrong burn Value

### ISSUE THREAD

**Issue by KaneHart** [AztechMC/Modern-Industrialization#196]
![image](https://user-images.githubusercontent.com/425853/146872178-cac75a2a-43da-442c-862a-e514d9591fe5.png)

Might not be able to be fixed LOL I see this in the code:

`addFuel("coke_block", Short.MAX_VALUE); // F*** YOU VANILLA ! (Should be 6400*9 but it overflows ...)`

https://github.com/AztechMC/Modern-Industrialization/blob/5d9568091fa992e9cb09f7d5075a8830c0356f3e/src/main/java/aztech/modern_industrialization/ModernIndustrialization.java#L255

**Comment by Technici4n** [comment]
Indeed, there is nothing that we can do about this. :P

**Comment by KaneHart** [comment]
Thanks for confirming. I was not sure if it was a hack to get pass it that failed or not haha. Sadly I don't understand most of the code.
