### ISSUE TITLE
Machine Texture Mapping

### ISSUE THREAD

**Issue by Afrocntrik** [AztechMC/Modern-Industrialization#2]
![2020-09-07_17 22 31](https://user-images.githubusercontent.com/11052983/92417177-e5896d80-f12e-11ea-8f56-5b4d1ed743cc.png)
Here's how they appear in REI however they appear that way in block form as well
![2020-09-07_17 22 50](https://user-images.githubusercontent.com/11052983/92417195-00f47880-f12f-11ea-9539-e53f5c0922ad.png)

**Comment by Afrocntrik** [comment]
Using a custom resource pack
[Unity 1.16.X Fabric.zip](https://github.com/AztechMC/Modern-Industrialization/files/5184939/Unity.1.16.X.Fabric.zip)

**Comment by Technici4n** [comment]
Thanks a lot for the report, will be fixed in the next release! For now, the solution is to restart the game after switching texture packs.
Nice textures by the way, where did you find them?

**Comment by Technici4n** [comment]
Oh ok, very cool! You may want to fix that when you stack double ingots, the stack count and the 2 on the texture conflict. ;-)
