### ISSUE TITLE
Current update throwing TechReborn Comp. issues

### ISSUE THREAD

**Issue by DraLUSAD** [AztechMC/Modern-Industrialization#206]
[latest.log](https://github.com/AztechMC/Modern-Industrialization/files/7779523/latest.log)
Your recent updates are throwing these issues.

**Comment by Technici4n** [comment]
Damn, thanks. Will be fixed soon. You can safely ignore those in the meanwhile.

**Comment by DraLUSAD** [comment]
no problem, seems like it doesn't like those curved recipes
