### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Romz24** [AztechMC/Modern-Industrialization#21]
I set the pipes to the ground, when I tried to break them, I got a crash and can no longer enter the world because the game constantly crashes.

**Minecraft version:** 1.16.3
**Mod version:** 0.3.0
**Fabric API:** 0.24.1+build.412-1.16
**Fabric loader:** 0.10.3+build.211

[crash-2020-10-25_17.43.48-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/5434937/crash-2020-10-25_17.43.48-client.txt)
[crash-2020-10-25_17.49.36-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/5434935/crash-2020-10-25_17.49.36-client.txt)
[crash-2020-10-25_17.51.08-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/5434936/crash-2020-10-25_17.51.08-client.txt)

**Comment by Technici4n** [comment]
OptiFine doesn't support Fabric natively.

If you are willing to try alternatives, and don't need shaders, please look at this list:
https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

If, however, you really really want OptiFine and shaders,
please know first OptiFine can cause heavy incompabilities that are, in some cases, not easy to fix.

OptiFabric is a mod that allows OptiFine to run on Fabric but be aware that some mods will not bother to provide compatibility for it, so use it at your own risk:
https://www.curseforge.com/minecraft/mc-mods/optifabric

**Comment by Technici4n** [comment]
Yes this is an optifine rendering crash...
