### ISSUE TITLE
Put a lava bucket in the Steam Mining Drill, and can'

### ISSUE THREAD

**Issue by jacquesco07** [AztechMC/Modern-Industrialization#211]
So I thought I was being smart by putting in a lava bucket in the mining drill, but now I can't get it out. I'm sure I'm just being dumb though. How do I get it out?

**Comment by tino7902** [comment]
did the same, right click on an empty slot of your inventory

**Comment by Azercoco** [comment]
Just right click with the drill in hand on an empty slot.

**Comment by jacquesco07** [comment]
Thanks! lol
