### ISSUE TITLE
Question about Energy Cables

### ISSUE THREAD

**Issue by DraLUSAD** [AztechMC/Modern-Industrialization#212]
So I've been experimenting with "Modern Industrialization" cables with other mods stuff, sadly, it made me sad a bit, here is why.

Fluid: ;)
I'm able to input/output fluids from "Tech Reborn" Drains, and input fluids to "Extra Generators" Scalding Generator, seems good, BUT.

Items:
With anything and everything :)

Power: :(
I'm able to Input power to "Tech Reborn" Battery Box, "Industrial Revolution" Lazuli Flux Container", but I'm unable to withdraw power from those devices, also, I'm unable to withdraw power from "Extra Generators" scaling generator.

is it possible to add compatibilities, or is it just not possible with how the cables handle output power?

**Comment by Rakkis157** [comment]
Being able to power other mod's stuff with MI's power, but not being able to power MI stuff with power from other mods is intentional.

**Comment by DraLUSAD** [comment]
as an optional feature maybe?

**Comment by Technici4n** [comment]
Not gonna happen. This is intended, for balance reasons.
