### ISSUE TITLE
Please add Name Tooltip to Barrels.

### ISSUE THREAD

**Issue by KaneHart** [AztechMC/Modern-Industrialization#213]
Could you please add the name of whatever I'm looking at when it comes to barrels please.

Example:
![image](https://user-images.githubusercontent.com/425853/147844820-fcd3c997-3547-44ad-9c01-d6b32df99f96.png)

right now it's this:
![image](https://user-images.githubusercontent.com/425853/147844826-d9e4aad9-e132-434b-9298-59c5eae3fdbd.png)

**Comment by Azercoco** [comment]
WTHIT tooltips are implemented by Megane, so its a Megane issue.

**Comment by KaneHart** [comment]
Thank you for the reply. Please close this if it's the final answer. I did put that request into the developer who makes Megane and they had no Interest in it. 

Do you guys do any tooltips at all with WTHIT? Or another Mod? I'm happy to switch If you guys support a another hover over tooltip system.

**Comment by Azercoco** [comment]
The problem is that megane decided to implement it itself without asking if we wanted to. If we reimplemented it ourselves, it would cause issue because nearly everyone playing MI also uses megane. I'm not happy with this situation (exactly for this reason : we have no control over the WTHIT plugin) but the alternative would cause more problems.

**Comment by Technici4n** [comment]
Not much we can do, unless we agree with @deirn to move that part of megane into MI, which I wouldn't be opposed to. :)

**Comment by deirn** [comment]
I won't add special tooltip for only one mod to megane, since it's designed to be generic.

---

> Not much we can do, unless we agree with @deirn to move that part of megane into MI, which I wouldn't be opposed to. :)

What do you mean by this? Moving the megane MI module here? I'll need to refactor the megane API before I'm happy to do so (it's pretty messy right now) :P

**Comment by Technici4n** [comment]
> Moving the megane MI module here?

Yes, that would be the idea, so that we can maintain it ourselves and expand it when necessary (without having to bug you when one of the mixins breaks 😅). But there is no rush of course!
