### ISSUE TITLE
Bronze to Steel Upgrade

### ISSUE THREAD

**Issue by bwpikaard** [AztechMC/Modern-Industrialization#214]
According to the guide book, you can craft a Steel Upgrade to upgrade Bronze Machines to Steel. Using that Steel Upgrade, put it in a Smithing Table to upgrade. 

![image](https://user-images.githubusercontent.com/19532144/147885501-c426e06b-19b7-4d70-bf9b-03f6e135947e.png)

I tried this, and it doesn't work with the Furnace or Boiler. Looking at the recipe for a Steel Boiler in REI, it doesn't have anything indicating a Bronze Boiler, Steel Upgrade, and Smithing Table. 

![image](https://user-images.githubusercontent.com/19532144/147885520-64e32ed5-e20b-40f9-8fa3-c48dada53e5b.png)

Fabric 0.12.12
Minecraft 1.18.1
MI 1.0.3

**Comment by Technici4n** [comment]
We could add these recipes, but isn't the upgrade more expensive than crafting the boiler/furnace directly?

**Comment by Azercoco** [comment]
The upgrades are only usable on steam crafting machine, which neither the boiler or the furnace are.

**Comment by bwpikaard** [comment]
Is there somewhere is states that it only works on crafting machines? The guide makes it seem as though it works for any bronze machine.

**Comment by Technici4n** [comment]
You can view the recipes for the steel furnace & boiler in REI.

**Comment by bwpikaard** [comment]
You may want to update the guide for its actual use so new players don't get confused. It makes it seem like this is the next step after just getting steel and that they're used for any bronze machine.

**Comment by jecowa** [comment]
> We could add these recipes, but isn't the upgrade more expensive than crafting the boiler/furnace directly?

Imo, please don't add recipes that would give us the option to do very inefficient things.

**Comment by mnsnownutt** [comment]
I thought this was a bug, but now realize it is just poorly worded in the manual.  So, why in the section of the guide regarding steel upgrades, it states "A steel boiler will produce twice as much steam as a bronze one."  The infers you can upgrade it using a steel upgrade.

I am fairly new to MI and thought it meant you can upgrade bronze machines to steel using the upgrades.  Even references bronze hatches in the upgrade section as well.  Confusing.  I had made several of these steel upgrades that are now worthless.

**Comment by CommanderTso** [comment]
Same.  I spent hours tonight crafting things and trying to figure out why the upgrades don't work.  It would be great if you updated the in-game guide.
