### ISSUE TITLE
Visual Glitch

### ISSUE THREAD

**Issue by Rakkis157** [AztechMC/Modern-Industrialization#217]
The working animation for the mixer covers up the port.

![image](https://user-images.githubusercontent.com/41505541/148100543-4f6b28c1-ff28-44e1-9840-812f09c097e8.png)
![image](https://user-images.githubusercontent.com/41505541/148099328-bf366707-f586-4f59-bb7a-8f83ae446649.png)

**Comment by Rakkis157** [comment]
Did some testing. Seems like the glitch only effects the east, south and top facing sides.

![image](https://user-images.githubusercontent.com/41505541/148102530-49194ea1-9f48-4a93-8da1-5b84f5bfacbb.png)
![image](https://user-images.githubusercontent.com/41505541/148102681-0fe9ce33-cab6-4c25-89f5-d00e963af21e.png)
![image](https://user-images.githubusercontent.com/41505541/148102635-a74888bd-e2e2-4483-9dc8-65fd2c5f8bd4.png)

![image](https://user-images.githubusercontent.com/41505541/148102926-a391f518-9edf-4bba-8a43-5ed8aed39917.png)
![image](https://user-images.githubusercontent.com/41505541/148102733-71052317-5c12-41ce-bbe8-61dbd239f0e5.png)
![image](https://user-images.githubusercontent.com/41505541/148102897-c6baa3af-b045-437e-98d3-42ffd7cbcb3d.png)

**Comment by Technici4n** [comment]
Can't reproduce in dev. :/
