### ISSUE TITLE
Iron ingots not able to be made into plates on bronze compressor

### ISSUE THREAD

**Issue by dailyrider** [AztechMC/Modern-Industrialization#219]
Playing "all of fabric 5" java 1.18 with version 1.04 of Modern-Industrialization and I can insert iron ingots (from minecraft), there is a recipe for it in the interface and will pull from inventory to fill slot of the bronze compressor, but it will not make the plates.

**Comment by Azercoco** [comment]
I'm sorry but I don't understand your problem. Could you explain it more perhaps with more details and some screen of your setup ?

**Comment by Technici4n** [comment]
You probably forgot to put steam in the bronze compressor?
