### ISSUE TITLE
Incompatible with inspecio? Crash while searching in REI - 1.18.1

### ISSUE THREAD

**Issue by SpigotDE** [AztechMC/Modern-Industrialization#220]
Everytime i search in REI the game crashes client side.

[crash-2022-01-09_11.41.20-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/7834883/crash-2022-01-09_11.41.20-client.txt)
[latest.log](https://github.com/AztechMC/Modern-Industrialization/files/7834884/latest.log)

**Comment by Technici4n** [comment]
This issue happens with Industrial Revolution, not us. But from the looks of it, it's an Inspectio issue.
