### ISSUE TITLE
[1.18.1] Liquid Storage Tanks crash

### ISSUE THREAD

**Issue by itsdinkd** [AztechMC/Modern-Industrialization#221]
https://github.com/itsdinkd/AQM2/issues/39

As reported by a player of my modpack, there are crashing issues that occur related to Liquid Storage Tanks

To Reproduce

    Build a large steam boiler
    place a fluid tank and connect it to the boiler
    let the boiler run and fill the tank
    See error

https://paste.corebot.dev/xokalozixi.coffeescript

**Comment by Technici4n** [comment]
Not an MI issue, please check the crash more carefully. It's from another tank mod.

**Comment by Technici4n** [comment]
Note: the mod causing the crash is https://github.com/Kotori316/FluidTank.

PS: I don't really get the point of that mod when you have MI already. :P

**Comment by itsdinkd** [comment]
Honestly, I haven't even tried MI yet I've been so focused on maintaining and building. I will see about removing FluidTank mod
