### ISSUE TITLE
Ores do not generate in Terralith Biomes

### ISSUE THREAD

**Issue by Miku0Sama** [AztechMC/Modern-Industrialization#222]
Ores simply do not generate in Terralith biomes. I contacted Terralith devs about it and they said the easiest way was for you to add datapack biome support. So I thought I would just open this issue here to bring it to your attention.
![oregen](https://user-images.githubusercontent.com/14240640/148702059-ebefa366-416f-4980-99d1-9e58b307cbe1.PNG)

**Comment by Technici4n** [comment]
We use standard Fabric's Biome Modifications API, if that doesn't work then I'm afraid there is nothing we can do about it: https://github.com/AztechMC/Modern-Industrialization/blob/2f00826b7d7d30238f82b9a2314cc4f46e0ac397/src/main/java/aztech/modern_industrialization/materials/part/OrePart.java#L161.
