### ISSUE TITLE
Invisible pipe

### ISSUE THREAD

**Issue by Hemptet** [AztechMC/Modern-Industrialization#228]
Got this message. I'm just following directions 
![2022-01-13_12 00 01](https://user-images.githubusercontent.com/49766106/149384704-3ac3b3c9-4a31-4dab-bf52-ff67e633cdc1.png)

**Comment by Technici4n** [comment]
How did this happen?

**Comment by Hemptet** [comment]
I have no idea, but it won't let me place a pipe block in its place. You can actually get the breaking animation of that invisible block but it immediately reappears.  I'm playing on AQM2, it happened when I upgraded from mod v 1.5.2a to 1.6.

**Comment by Technici4n** [comment]
To remove it, you can enable debug commands on the server in the `modern_industrialization.toml` config file, and then run `/mi pipes clear <x> <y> <z>` if my memory is correct.
