### ISSUE TITLE
Rendering Crash - Patchouli Book - Steam Age page 1.18.1

### ISSUE THREAD

**Issue by SpigotDE** [AztechMC/Modern-Industrialization#229]
Maybe the crash is on your side?

Crashes while looking through Steam Age Page with the Mining Drill

seems like : 
- Diesel Tool
- Steam Drill

[Modpack i use](https://www.curseforge.com/minecraft/modpacks/the-progressor)

[latest.log](https://gist.github.com/SpigotDE/f8abf1ee0aaa177dfb8f30b48af4e430)

**Comment by Technici4n** [comment]
The crash seems to be in a "kiwi" mod, whatever that is.

**Comment by SpigotDE** [comment]
updated kiwi mod to 5.2.3 -> still crashes

kiwi mod owner looked over it and update the mod (fix with not enough crashes)

You got any idea which mod causes the crash?

**Comment by SpigotDE** [comment]
`<script src="https://gist.github.com/SpigotDE/0369b0f0741cc8e61593c65e59fc2ed9.js"></script>`

**Comment by Technici4n** [comment]
It's LevelZ now.
