### ISSUE TITLE
[Suggestion] Add no of fluid pipes/ transfer limit in a network on Fluid pipe gui

### ISSUE THREAD

**Issue by k3nw4y** [AztechMC/Modern-Industrialization#232]
Add no of fluid pipes in a network, so that we can calculate/ find out the transfer speed/t

**Comment by Technici4n** [comment]
Will be in the next release. :wink:

![image](https://user-images.githubusercontent.com/13494793/192162937-141fcf63-ceef-4171-bd0d-7fbda2a838cd.png)
