### ISSUE TITLE
broze pipe crashed minecraft and im unable to join the world again

### ISSUE THREAD

**Issue by KlaraChaos** [AztechMC/Modern-Industrialization#233]
it commpley crashed minecraft wen i placed the broze pipe and now im unable to join the world again 

[crash-2022-01-16_20.42.33-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/7877827/crash-2022-01-16_20.42.33-client.txt)

**Comment by Technici4n** [comment]
Install indium.
