### ISSUE TITLE
MV to LV transformer has wrong number of in- and outputs

### ISSUE THREAD

**Issue by passivagressiv** [AztechMC/Modern-Industrialization#234]
Describe the bug:
the MV to LV transformer from modern industrialization has 5 inputs for MV cabels and only 1 output for LV cabels

1. place MV to LV transformer
2. lshift + right click with wrench on a side to set the output side
3. place a LV cabel (tin/copper/silver) at the output and it will automatically conncet
4. all other sides connect automatically to MV cabels (cupronickel/electrum) - they will not accept LV ones

Expected behavior:
as the MV to LV transformer is supposed to convert MV energy 1024 EU per tick to LV energy 256 EU per tick it should have one input and 4 outputs, the transformer converts MV to LV energy as intened but has the wrong number of in- and outputs

Screenshots:
![transformer](https://user-images.githubusercontent.com/97842896/149779565-6414666b-7f37-479d-8ab4-4ef263f7e467.PNG)
![MV_input](https://user-images.githubusercontent.com/97842896/149779575-8b396c0a-64bc-4166-a08e-be86e0a18a78.PNG)
![LV_output](https://user-images.githubusercontent.com/97842896/149779580-d4651ad4-4cf5-439d-9a32-b73436d8dc18.PNG)

**Comment by Technici4n** [comment]
Good point. This will likely have to wait for 1.19 to be changed.
