### ISSUE TITLE
No way to get Tungsten Ingots

### ISSUE THREAD

**Issue by Hemptet** [AztechMC/Modern-Industrialization#235]
So I'm playing MI on Another Quality Modpack 2, they asked me to report this here. There is no way to get tungsten ingots without the implosion compressor. The only way to build an implosion compressor is with tungsten ingots. So tungsten is quite the issue. You cannot turn tungsten into ingots by smelting dust or raw ore.

**Comment by ramidzkh** [comment]
You have to use the compressor with tungsten dust tiny piles to get nuggets which you can make into ingots for the implosion compressor

**Comment by Hemptet** [comment]
Oh that worked thank you so much, I've spent hours trying to figure that out
