### ISSUE TITLE
multi-block structures conflict with multithread mods

### ISSUE THREAD

**Issue by scarf005** [AztechMC/Modern-Industrialization#237]
currently modern-industrialization mod conflicts with multithread utilization mods such as [DimensionalThreading](https://github.com/WearBlackAllDay/DimensionalThreading). judging by the crashlog looks like because multi-blocks requires to be on single thread. there's [also same issue on the mod's page](https://github.com/WearBlackAllDay/DimensionalThreading/issues/40)

maybe multi-blocks could use other form of checking method?

[crash-2022-01-21_01.28.07-server.txt](https://github.com/AztechMC/Modern-Industrialization/files/7907033/crash-2022-01-21_01.28.07-server.txt)

**Comment by Technici4n** [comment]
Ticking multiple things in parallel is fundamentally not going to work, sorry. Think about an ender chest.

**Comment by scarf005** [comment]
oh, didn't think about that, sorry.
thank you for quick response.
