### ISSUE TITLE
Wrench adjusts machine orientation causing crash

### ISSUE THREAD

**Issue by w7iche** [AztechMC/Modern-Industrialization#238]
When I try to tune the steam turbine generator, it comes up with two heads, then after a few seconds the game crashes reporting that the server is lost.
Maybe a rollback will do the trick, but my archive backup is five days ago and I've done a lot of work during that time.

**Comment by Azercoco** [comment]
Please give a crash report

**Comment by w7iche** [comment]
[crash-2022-01-22_20.22.23-server.txt](https://github.com/AztechMC/Modern-Industrialization/files/7918319/crash-2022-01-22_20.22.23-server.txt)

**Comment by Azercoco** [comment]
Could you please provie a picture/video of how to reproduce the crash ?

**Comment by w7iche** [comment]
as you can see, happened here modpack"Another Quality Modpack 2".
![Snipaste_2022-01-23_09-11-28](https://user-images.githubusercontent.com/96696414/150661066-37518c3b-6a5d-47d2-92e5-b032b993f3a1.png)
![Snipaste_2022-01-23_09-18-23](https://user-images.githubusercontent.com/96696414/150661067-be1d430f-b840-4e15-a4fc-24fc473b9844.png)

**Comment by Technici4n** [comment]
Looks like it's an instance of https://github.com/P03W/RPGStats/issues/94. Doesn't seem related to MI though.
