### ISSUE TITLE
Clearer large tank upgrade instructions

### ISSUE THREAD

**Issue by jeslinmx** [AztechMC/Modern-Industrialization#242]
Arguably, from both personal experience and the existence of issues #226 and #176 , the guidebook's current description of how to make larger Large Tanks is ambiguous:

> You will only see a preview of the smallest shape, but you can add layers on the top, the back and the sides of the tank.  The front face must remain horizontally symmetrical.

This, for reference, is the correct way to build a 5x5x5 tank. Steel machine casings along the edges, glass on the faces, large tank controller above the middle of the bottom edge:

![image](https://user-images.githubusercontent.com/1007894/150672874-61f691a6-0c4f-47f2-98a6-1b209ed08f5d.png)

I only learnt this method through watching a let's play of someone who figured it out. Now, a gallery of all the wrong ways to interpret the instructions:

![image](https://user-images.githubusercontent.com/1007894/150672939-867b1491-a070-4e03-9527-33743d41dd20.png)

(added layers on the top, back, and sides of the tank)

![image](https://user-images.githubusercontent.com/1007894/150672972-e25818de-c9e3-4b2b-bd24-6523b18cc248.png)

(oh, that didn't work? maybe it needs to be rectangular)

![image](https://user-images.githubusercontent.com/1007894/150673064-1cbdec9d-679f-486b-98d0-79f9853eb8c6.png)

(maybe the front face needs to be symmetrical vertically too?)

I think the most palatable way to fix this would be to simply drop in a reference image of a larger tank, same as what we currently have for the Coke Oven. Just as the Coke Oven is the first multiblock in the game and requires a more thorough explanation, the Large Tank is a somewhat unique multiblock in that

1. It is the first multiblock with multiple shapes, and in fact behaves differently from the others as it is completely dynamic (can grow as big as it wants, instead of fixed configurations which are switched through the Screwdriver)
2. We can't even count on the Wrench to guide us because the 3x3x3 Large Tank layout clashes with larger configurations:

![image](https://user-images.githubusercontent.com/1007894/150673304-ffc5a341-b5d4-41db-90f9-604fc5e425c6.png)

**Comment by jeslinmx** [comment]
I've taken some relatively neutral screenshots which could work as inclusions in the guidebook.

A angle similar to what we use for the Coke Oven:

![image](https://user-images.githubusercontent.com/1007894/150673436-59f55bf5-a0e9-432b-be56-28e6bf730b7c.png)

a more angled view:

![image](https://user-images.githubusercontent.com/1007894/150673475-17abde79-882d-4659-aea1-fe4024021af0.png)

same angles, but with a 3x4x5 tank to show various possibilities:

![image](https://user-images.githubusercontent.com/1007894/150673609-8c5abec5-fe3e-4964-b8ea-db4ff727bf7a.png)


![image](https://user-images.githubusercontent.com/1007894/150673585-05524d93-b599-408c-ac97-1fca23753afb.png)

**Comment by Technici4n** [comment]
Shape selection is now done in the GUI directly in 1.19, as implemented in de8610c011244016fd5bd2bb699297248f176719.

**Comment by jeslinmx** [comment]
I have no idea what that means, but I look forward to seeing it!

**Comment by Technici4n** [comment]
Here is a little demo :)

https://user-images.githubusercontent.com/13494793/176996867-575bfdb6-920b-4b28-98fe-efbd2585b4c8.mp4
