### ISSUE TITLE
suggestion - helium plasma energy fix, wireless network support

### ISSUE THREAD

**Issue by Azruine** [AztechMC/Modern-Industrialization#245]
1. He plasma energy consumption is 16.00kEU/t in REI.
I've tested with large steam turbine, and no energy stored in fusion reactor while processing. Consumption should be 16.384kEU/t then, right?

2. wireless network support
So, you said that MI machines can not accept energy from fabric energy api. But I want use wireless network mod with MI :/
I can provide steam with entangled tank, but throuput is really bad. One entangled tank can't sustain one large steam turbine.
Messing up with bunch of cables is.. so painful.
Or can you add wireless transfer in quatum tier? Like tesseract.

**Comment by Technici4n** [comment]
1) Consumption is exactly `16000`, but it will increase if the fusion reactor overclocks.
2) You can use fluid fuels such as diesel for higher throughput. We might look into making it easier for wireless networks to support MI energy alongside TR energy, but that is probably not going to happen for a while.
