### ISSUE TITLE
Incompatibility issue with Improved Stations

### ISSUE THREAD

**Issue by Wolfy8198** [AztechMC/Modern-Industrialization#246]
There seems to be a compatibility issue with between Improved Stations 2.0,8 and Modern Industrialization 1.0.4 for 1.18. Textures are broken, and some blocks aren't rendering. I have sodium and Indium installed, and Improved Stations is installed only on my client because I'm planning to add it to my modpack. (screenshots taken on my server because my fps is too low in singleplayer
![Screenshot 2022-01-27 190208](https://user-images.githubusercontent.com/64490202/151463887-6b5f620e-58c9-4ecc-8083-673d7b17582e.png)
![Screenshot 2022-01-27 190056](https://user-images.githubusercontent.com/64490202/151463889-511224b1-378a-4997-9378-4e225e41e6cf.png)
)

**Comment by Technici4n** [comment]
Try installing it on the server too. If it still fails then that mod must be broken, I don't know how it can cause such failures but it's certainly not MI's fault.

**Comment by k3nw4y** [comment]
Improved Stations v 2.0.8 and Modern Industrialization 1.0.4 in minecraft 1.18.1, i cant reproduce it, client and server has improved stations installed
![image](https://user-images.githubusercontent.com/46229190/151503524-2b56de1b-8813-4129-b5c4-2e696f2b626b.png)

**Comment by Wolfy8198** [comment]
> Try installing it on the server too. If it still fails then that mod must be broken, I don't know how it can cause such failures but it's certainly not MI's fault.

I made an issue report on the github for improved stations at the same time as I made this one, I'm waiting for a reply. I added the mod to my server, and now I just have to wait until I get out of school to log on and see if it was fixed
