### ISSUE TITLE
[1.18.1 bug] Stall on Restart/Shutdown

### ISSUE THREAD

**Issue by itsdinkd** [AztechMC/Modern-Industrialization#249]
Every time i try to restart dedicated servers, I am shown in console

`[23:41:51] [Server thread/WARN] (Modern Industrialization) ChunkEventListeners#listeners is not empty at server stop! Active worlds: 1` 
after chunks save, and then nothing else. the server stalls, requiring me to Terminate it.

This is on 1.18.1, last 2 versions of MI has been doing this

**Comment by yorii** [comment]
sorry stupid question perhaps but do you use the stop command or ctrl-c to stop the server?

**Comment by itsdinkd** [comment]
its through a web console, not ssh.

**Comment by Technici4n** [comment]
I'll fix this, but it's harmless and can be ignored. It certainly has nothing to do with a hang.
