### ISSUE TITLE
[1.16.3] Difficulty logging in to a dedicated server after update - Unknown item tag c:lunum_ingots

### ISSUE THREAD

**Issue by ProsperCraft** [AztechMC/Modern-Industrialization#25]
![2020-11-05_20 06 22](https://user-images.githubusercontent.com/4427684/98321532-92069500-1fa2-11eb-859c-5224a6657757.png)

Log-
https://gist.github.com/ProsperCraft/41a963b44f682dc3a5a9581d70d1283b

Updated to  Modern-Industrialization-0.3.4

Workaround- 
Log in to a single player world, then log out without rebooting and log in to a multiplayer world.

**Comment by Technici4n** [comment]
Thanks a lot for reporting, that's a nasty bug indeed! It is fixed in 0.3.5, and the fix is needed both on the client and the server.
