### ISSUE TITLE
MI machines don't accept power from TR generators

### ISSUE THREAD

**Issue by Jackthe3rd** [AztechMC/Modern-Industrialization#26]
MI machinery doesn't accept power from TR, but TR machinery does accept power from MI generator
![2020-11-06_12 57 01](https://user-images.githubusercontent.com/58362788/98331921-2f5bda80-2030-11eb-8409-ab1b1be55fea.png)
![2020-11-06_12 57 25](https://user-images.githubusercontent.com/58362788/98331926-32ef6180-2030-11eb-959e-1cca23d1b715.png)
![2020-11-06_12 57 19](https://user-images.githubusercontent.com/58362788/98331928-3387f800-2030-11eb-9cc2-14732aaeb1a6.png)

**Comment by Neubulae** [comment]
This is working as intended, as TR machines could quickly screw up progression

**Comment by Jackthe3rd** [comment]
This makes sense. But what about battery boxes and MFEs? They don't produce power.

**Comment by Neubulae** [comment]
> This makes sense. But what about battery boxes and MFEs? They don't produce power.

You may use them as a medium to transmit power to MI machines, thus unusable. Tho you can probably make a MI battery or something

**Comment by Technici4n** [comment]
Yes, this is intended. Only MI generators and cables can convert EU into TR's Energy, and it can't be done the other way around.
