### ISSUE TITLE
Cant get steam in heat exchanger

### ISSUE THREAD

**Issue by maxutka99** [AztechMC/Modern-Industrialization#260]
cant get steam from lava and water in heat exchanger
![изображение](https://user-images.githubusercontent.com/43550690/154795403-948a2282-8ace-461b-a341-b1a3af7ea78f.png)
![изображение](https://user-images.githubusercontent.com/43550690/154795413-e2f1ab62-d1f0-41c8-9e8d-417949f94066.png)

**Comment by k3nw4y** [comment]
try large hatches

**Comment by maxutka99** [comment]
> try large hatches

thanks
