### ISSUE TITLE
Can you add material id for Tools - LevelZ support [1.18.1]

### ISSUE THREAD

**Issue by SpigotDE** [AztechMC/Modern-Industrialization#263]
I wanna add your Tools like:

Chainsaw
Jetpack
Mining Drill
Hammer
Quantum Armor & Sword

in different Categories in LevelZ

so for example:
Hammer -> Smithing
Mining Drill -> Mining
Chainsaw -> Farming 

in LevelZ i need a material for the datapack so for Quantum Armor it may look like this:

{
    "replace": true,
    "skill": "defense",
    "level": 12,
    "item": "minecraft:armor",
    "material": "quantum"
}

or for the chainsaw maybe:

{
    "replace": true,
    "skill": "farming",
    "level": 6,
    "item": "minecraft:axe",
    "material": "diesel"
}

**Comment by Azercoco** [comment]
I'm not sure to understand the issue ... It seems that LevelZ allow adding restriction on an item directly so why don't use this ?

**Comment by SpigotDE** [comment]
Yeah hey mentioned it in the Wiki but for Tools / Axes / Hoes / Swords / Armor it doesn't work. 

I found in the mod "DragonLoot" that the author made an extra LevelZ Compat ( found at the bottom of the following link )

https://github.com/GitPois1x/DragonLoot/blob/7183a6ef6880d2f249d3dc8232c30c07a550bf08/src/main/java/net/dragonloot/item/DragonToolMaterial.java#L54

I have no clue in programming but maybe this helps. 

LevelZ gets the material used from the items, but the method mentioned in the levelz wiki with "custom_item" and "object" only gets the name of the item , but doesnt block the item from use

Sry my english issnt that good

**Comment by Technici4n** [comment]
I implemented it for the armor items and the forge tools, however I was unable to implement it for the chainsaw and the 2 mining drills since they are "dynamic" tools.
