### ISSUE TITLE
Shale oil in large tank fills from the top - 1.18.1

### ISSUE THREAD

**Issue by mnsnownutt** [AztechMC/Modern-Industrialization#269]
Looks like a visual glitch, but when putting shale oil in a large tank, it fills in from the top down, instead of the bottom up, defying gravity.

Pastebin with relevant mod info and screenshot showing the magical fluid called shale oil.

https://pastebin.com/r672cXuQ

![2022-03-09_21 23 35](https://user-images.githubusercontent.com/31514693/157582686-6d22bce9-ad00-4952-a028-eb34c892befd.png)
.

**Comment by Rakkis157** [comment]
Not a visual glitch. Shale Oil was set as a gas in the code when it shouldn't be. An easy fix.
