### ISSUE TITLE
Can bypass replicator tag check by Nbt-attached blocks (block entity)

### ISSUE THREAD

**Issue by aria1th** [AztechMC/Modern-Industrialization#270]
Chests with NBT data, or other machine / items that contains item data can bypass replicator blacklist.

**Comment by Technici4n** [comment]
I don't really see what can be done in that case tbh, but it is semi-intended that the replicator can most likely duplicate items contained by other items.

**Comment by yorii** [comment]
Pack creators can add whichever item tags they want to the replicator blacklist using KubeJS.

**Comment by Technici4n** [comment]
Going to close this as "works as intended" :P
