### ISSUE TITLE
Modern Industrialization Bronze Boiler is Crashing my Server

### ISSUE THREAD

**Issue by garglez** [AztechMC/Modern-Industrialization#271]
My fam and I playing on a fabric server that has Modern Industrialization in it. It has had multiple crashes because of a "ticking block" error. When I look in the crash report, the error is noted to be caused by a bronze boiler. I upload a backup to play again (cause at this point it crashes on startup), but then after placing the block it gives the same issue.

Is there a way to fix this and continue using the boiler? Or do I just need to stop using that block? It also might be worth noting that there are 5 in the world in use, but the crash reports only cite 1 specific one (connected to a quarry) as the issue.

[crash-2022-03-19_18.47.25-server.txt](https://github.com/AztechMC/Modern-Industrialization/files/8310464/crash-2022-03-19_18.47.25-server.txt)

**Comment by Technici4n** [comment]
Looks like the problem is what the boiler is adjacent to?
