### ISSUE TITLE
Increase inventory size of packer/unpacker

### ISSUE THREAD

**Issue by Azruine** [AztechMC/Modern-Industrialization#273]
packer can not sustain full overclock with MI pipe network since wire requires 6 rubber sheets for single crafting

**Comment by jeslinmx** [comment]
By full overclock, you mean 1 cable/tick = 20 cable/sec? That would require capacity for 3 * 6 * 20 (item pipe push period * number of sheets as input * number of crafts per second) = 360 sheets = 6 slots (plus one more for the metal wire). This might make the packer/unpacker interfacing confusing as it has almost as many slots as an assembler just to support a mid/late-game use case.

I recommend, as a workaround if you need that much capacity, using a configurable chest with output pointing into the packer/unpacker as an input slot buffer.

**Comment by Technici4n** [comment]
Yeah, buffer configurable chests are the way to go. :)
