### ISSUE TITLE
Power tools don't work as expected

### ISSUE THREAD

**Issue by KydZombie** [AztechMC/Modern-Industrialization#276]
Both the diesel and the steam mining drills are ineffective on stone. The steam mining drill mines slower than a wooden pickaxe and the diesel mining drill mines faster than a netherite pickaxe. Both don't drop the stone/ore you mined, and do not mine a 3x3. They do however work on grass, dirt, gravel, etc. with no issue, and give silk touch. The chainsaw is also completely unable to mine leaves, making the silk touch on it useless. All tools tested were given diesel or fuel and water respectively.

**Comment by Metal-666** [comment]
I'm also facing this problem

**Comment by Foresteam** [comment]
The same problem. I even thought the steam drill a joke, but seems it should work. Well, it doesn't.

**Comment by Technici4n** [comment]
Will have a look soon.

**Comment by Technici4n** [comment]
Works fine for me? It looks like another mod might be interfering.
![image](https://user-images.githubusercontent.com/13494793/163485539-258f404d-09d5-43f5-9cc8-563964cdca7a.png)

**Comment by Foresteam** [comment]
I turned off everything except the needed to run, that didn't help. Here are the versions:
* architectury-4.1.41
* cloth-config-6.2.57-fabric
* fabric-api-0.48.0+1.18.2
* Modern-Industrialization-1.1.0-alpha.01
* RoughlyEnoughItems-8.0.442

**Comment by FavoritoHJS** [comment]
works for me, but I have a newer version of:
* Architectury (4.1.44 instead of 4.1.41)
* Fabric API (0.50.0 instead of 0.48.0)
   Seems like 0.50.0 changed how mining levels work. That might be the problem?
* RoughlyEnoughItems (8.0.441 instead of 8.0.442)

**Comment by Foresteam** [comment]
Yes, the problem was outdated Fabric API.

**Comment by FavoritoHJS** [comment]
bingo, Fabric API Pull Request 2090 might be what fixed the issue
I'm thinking the mixin is applying... to an unused method, thus efectively failing silently.

**Comment by Technici4n** [comment]
Yes, MI included code from said PR, I assume for some reason it wasn't working? Closing as it's fixed.

**Comment by TheSergioEduP** [comment]
This issue exists with Quilted Fabric API 1.0.0-beta.20+0.55.1-1.18.2 (works with the exact same set of mods but with Fabric API 0.55.1+1.18.2 instead of Quilted), looks like Quilt has been merging pretty much everything from Fabric, could there be a small change that is preventing this from working?

**Comment by Technici4n** [comment]
Probably something to report to the quilt team. We only support fabric.
