### ISSUE TITLE
Cannot enrich uranium 

### ISSUE THREAD

**Issue by rafter613** [AztechMC/Modern-Industrialization#278]
Version 1.0.5 for 1.18.1

Centrifuge will not spin uranium dust into 235 and 238. The machine does not use up any energy, and the recipe just doesn't proceed. 
Tried: -Adding recipe from JEI, using lock editing
-Upgrading centrifuge to MV electricity with advanced hull
-Supplying MV electricity directly via MV turbine
-Using creative battery as supply
-Attaching fluid and item outputs
-Breaking and replacing the centrifuge, in a different place

Thanks!

**Comment by Azruine** [comment]
Is recipe consuming over 32 eu/t? Then you should apply overclock upgrades like advanced upgrade or something to ensure machine can consume more than 32 eu/t

**Comment by rafter613** [comment]
Looks like that's the issue, yeah, you need to upgrade it with overclocking. Thanks.
