### ISSUE TITLE
1x1 drill is very laggy when playing on a server

### ISSUE THREAD

**Issue by liquidev** [AztechMC/Modern-Industrialization#280]
Here's a video demonstrating the issue.

https://user-images.githubusercontent.com/16415678/164499064-5a07ab68-18d2-4ffe-8a46-8eafab465129.mp4

As can be seen, 3x3 (default) mode works fine, but when sneaking to destroy a single block, there's a noticable amount of lag between the block particles appearing and the block actually getting removed. Apart from this, if you let go of the sneak button before the block gets destroyed, the drill will sometimes mine out a 3x3 area instead of the desired single block, which is mildly infuriating. On top of that, some blocks sometimes cannot be mined in single block mode, namely those that are insta-mined (like dirt), although I was unable to consistently reproduce this.

As the video shows, this only applies to single block destruction; 3x3 mining works fine.

**Comment by Technici4n** [comment]
I suspect it might be a modpack issue. Can you reproduce the issue in singleplayer, or is it only this server? And does it happen with only MI installed?

**Comment by liquidev** [comment]
As noted in the title, this issue only affects multiplayer; singleplayer works fine. I set up a minimal server on my local machine, with the following mods, as reported by Fabric on startup:
```
	- advanced_runtime_resource_pack 0.5.7 via modern_industrialization
	- architectury 4.2.49
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- fabric 0.50.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+40c91ec860 via fabric
	- fabricloader 0.13.3
	- fiber 0.23.0-2 via patchouli
	- java 18
	- magna 1.7.0-1.18-pre1 via modern_industrialization
	- minecraft 1.18.2
	- modern_industrialization 1.1.0-alpha.01
	- omega-config 1.0.8 via magna
	- patchouli 1.18.2-66-FABRIC-SNAPSHOT via modern_industrialization
	- playerabilitylib 1.5.0 via modern_industrialization
	- roughlyenoughitems 8.1.449
	- team_reborn_energy 2.2.0 via modern_industrialization
```
This was enough to reproduce the issue. As a minimal test case, you can use the following steps:
1. Give yourself a steam mining drill.
2. Give yourself some fuel.
3. Load the drill up with water.
4. Try mining a single block of stone.

**Comment by 123FLO321** [comment]
Can confirm. Also having this issue on a server. 
i suspect the problem here, since it takes exactly the same time it would to break a block when not sneaking as it does when sneaking. 
https://github.com/AztechMC/Modern-Industrialization/blob/c0217842e6d0b8dae5d5596e56e511d36141f67b/src/main/java/aztech/modern_industrialization/items/SteamDrillItem.java#L122
