### ISSUE TITLE
Minecraft refuses to launch when mod is installed: Exit code 1

### ISSUE THREAD

**Issue by qwerty4967** [AztechMC/Modern-Industrialization#283]
When Trying to launch Minecraft with these mods:
![image](https://user-images.githubusercontent.com/20099889/166074814-435e6a6c-a34e-4cbe-a6dc-f46a867c0bb3.png)
Minecraft fails to open, and produces this error message:
![image](https://user-images.githubusercontent.com/20099889/166074915-b734eb2e-5ba2-41ed-902c-0cf4fd565422.png)
If I remove Modern industrialization, minecraft opens and REI complains that it does not have the required dependencies.
If I remove REI or Fabric API, a Minecraft opens with a fabric mod loader screen opens and complains that Modern Industrialization requires them.
If I add the required dependencies for REI without Modern Industrialization, the mod works correctly. If I then add Modern Industrialization, I get the same Exit code 1 error.
I am able to run several fabric mods together with no issues, but If I add Modern industrialization, I get this error.

Minecraft Generates no crash log when this happens.

I attempted to install alternate versions of Java to fix the error: JDK 16, 17, and 18 (the latest version so far as I can tell), but they did not work.
16 opened with a fabric mod loader screen, complaining that the version of java was too old, and 17 and 18 still gave exit code 1.

I'm running windows 10, if that effects things.

Am I doing something wrong here, or is this a bug? Is there some experimental JDK 19 that I need or something?

**Comment by Technici4n** [comment]
You need java 17 at least. And you also need cloth-config but we forgot to put it in the dependencies for that version -_-.

**Comment by qwerty4967** [comment]
I installed cloth config and the dependencies required for Roughly enough items
my mod list now looks like this:
![image](https://user-images.githubusercontent.com/20099889/166078146-b16a4465-b370-48fd-8346-d31b1722feb5.png)

I still get the same error.
I also tried to install other mods listed as dependencies on curseforge, but they had no effect.

I downloaded a pre release of JDK 19, but it did not fix the issue either.
Neither the mod, nor fabric, nor even Minecraft seem to catch whatever is going wrong - no Minecraft window opens and it fails to generate a crash report.

**Comment by Technici4n** [comment]
Isn't there even something in the `logs` folder? That looks really strange.

**Comment by qwerty4967** [comment]
I didn't know about the logs folder, sorry
looks like there is a stacktrace there
https://pastebin.com/9YzELjVq

**Comment by Technici4n** [comment]
Ho, you're on minecraft 1.18.2 so you should be using this version instead: https://www.curseforge.com/minecraft/mc-mods/modern-industrialization/files/3718118. It's very stable even though it's marked as alpha, so we'll probably publish a release in a few days.

**Comment by qwerty4967** [comment]
ooh, alright
thanks for all the help!
