### ISSUE TITLE
[Crash] Error while initialising

### ISSUE THREAD

**Issue by snotknobbel** [AztechMC/Modern-Industrialization#284]
crash while loading custom modpack

https://logpaste.com/YkIy178k 
crash report

https://logpaste.com/BvZ383DL
log

**Comment by squillwah** [comment]
I'm also experiencing this with the latest release. The crash seems to persist even only with MI and it's dependencies, so I don't think it's a mod conflict issue. Falling back to the previous release (1.1.0-alpha.01) "fixed" the crash for me.

**Comment by itsdinkd** [comment]
same

**Comment by HacoKavanah** [comment]
Same crash occured with me!
