### ISSUE TITLE
Modern industrialisation causes arcanus mana to break.

### ISSUE THREAD

**Issue by netcore10** [AztechMC/Modern-Industrialization#285]
I have no idea why, but they've said that they wont be fixing it. 

arcanus mod below.
https://www.curseforge.com/minecraft/mc-mods/arcanus 

Can you help in any way?

**Comment by Technici4n** [comment]
I don't know how that mod works, please explain what "Modern industrialisation causes arcanus mana to break" means.

**Comment by netcore10** [comment]
It's a magic mod which impliments the magic like systems from wyncraft, The mana bar becomes empty or reverses for some reason when modern industrialisation is installed.

**Comment by Technici4n** [comment]
Have you tried this with **ONLY** MI, Arcanus and their dependencies?

**Comment by netcore10** [comment]
indeed.

**Comment by netcore10** [comment]
Believe me, i'm probably as confused as you are.

**Comment by Technici4n** [comment]
So, what was the issue?

**Comment by netcore10** [comment]
It was a server side problem (even lan), i still haven't quite figured it out. I had to delete everything and restart.
