### ISSUE TITLE
[Bug 1.18.2] ComputerCraft turtle Extraction deletes items

### ISSUE THREAD

**Issue by itsdinkd** [AztechMC/Modern-Industrialization#287]
Extracting items from a turtle using Modern Industrialization pipes causes the items to disappear and to never be extracted.

MC Version: 1.18.2
CC:Restitched: 1.100.5
Fabric: 0.51.1
Loader: 0.13.3

**Comment by Technici4n** [comment]
100% a computercraft issue since pipes work fine with literally every other modded inventory, please report it to them.
