### ISSUE TITLE
Night vision doesn't do anything.

### ISSUE THREAD

**Issue by ProsperCraft** [AztechMC/Modern-Industrialization#29]
![2020-11-11_23 11 44](https://user-images.githubusercontent.com/4427684/98902645-5f154300-2473-11eb-934f-a3ce95a642a0.png)
![2020-11-11_23 11 48](https://user-images.githubusercontent.com/4427684/98902647-60df0680-2473-11eb-90fb-8e70c0a25a10.png)
![2020-11-11_23 11 50](https://user-images.githubusercontent.com/4427684/98902654-62103380-2473-11eb-9727-8ba045ec8e69.png)
![2020-11-11_23 11 52](https://user-images.githubusercontent.com/4427684/98902657-63416080-2473-11eb-9e03-ebc23a3c747a.png)

**Comment by ProsperCraft** [comment]
I disabled the true darkness mod, and it still isn't very bright, it is the same with and without the helm.
![Uploading 2020-11-11_23.18.56.png…]()

**Comment by Technici4n** [comment]
Hi, I don't think this is an issue with Modern Industrialization. Can you copy the world, remove the mod and try again, please ?

**Comment by ProsperCraft** [comment]
Sorry, wrong github
