### ISSUE TITLE
Infinite Lignite

### ISSUE THREAD

**Issue by DarianLStephens** [AztechMC/Modern-Industrialization#291]
1 Lignite makes 1 Lignite Block.
1 Lignite Block turns in to 9 Lignite.

![2022-05-08_13 37 45](https://user-images.githubusercontent.com/15375876/167280708-ec5a3286-ffa4-4b1e-ab2d-e9a344e430cf.png)
![2022-05-08_13 37 48](https://user-images.githubusercontent.com/15375876/167280712-098b941c-8ebc-4448-8bd2-9bb1d6faf5c9.png)

**Comment by Azercoco** [comment]
Fixed with 937aab2956fbca1a02f86fdbe1e4dddf6111d994.
