### ISSUE TITLE
Crafter may stop when server reload

### ISSUE THREAD

**Issue by aria1th** [AztechMC/Modern-Industrialization#292]
![2022-05-11_00 18 27](https://user-images.githubusercontent.com/35677394/167664593-c6c6cc4b-d0ef-4b89-9c32-2b2342cfb60f.png)
![2022-05-11_00 18 46](https://user-images.githubusercontent.com/35677394/167664603-360ff6fb-9aba-4f48-b0db-3131591b2608.png)
![2022-05-11_00 18 31](https://user-images.githubusercontent.com/35677394/167664609-b10c7d81-c3c9-4d72-a8e1-42455a842db6.png)

It says it has active recipe in terminal, but it does not craft anything, it does not do anything, it can't use energy, it can't decrease efficiency tick too. but it has active recipe, means tickRecipe() method is never called in this crafter somehow.

It only happens for multiblocks : EBF, Vacuum freezer, etc. so it means allowNormalOperation var is always set to false.

Its fixed when multiblock shape is invalidated : which means shapeMatcher.needsRematch() returned false.

.... as an conclusion, the code should change:
```    protected final void link() {
        if (shapeMatcher == null) {
            shapeMatcher = new ShapeMatcher(level, worldPosition, orientation.facingDirection, getActiveShape());
            shapeMatcher.registerListeners(level);
        }
        if (shapeMatcher.needsRematch()) {
            allowNormalOperation = false;
            shapeValid.shapeValid = false;
            shapeMatcher.rematch(level);

            if (shapeMatcher.isMatchSuccessful()) {
                inventory.rebuild(shapeMatcher);

                onSuccessfulMatch(shapeMatcher);
                shapeValid.shapeValid = true;

                // If there was an active recipe, we have to make sure the output fits, and lock
                // the hatches.
            }

            if (shapeValid.update()) {
                sync(false);
            }
        }
		if (shapeValid.shapeValid){
			if (crafter.tryContinueRecipe()) {
				allowNormalOperation = true;
			}
		}
    }```

**Comment by Technici4n** [comment]
Hello, I can't reproduce this issue in singleplayer with an EBF turning uncooked steel into steel. Do you have more insight? (Sorry for the delay)

**Comment by Technici4n** [comment]
Can you provide reproduction steps?

**Comment by aria1th** [comment]
It only happens when server reboots : and any other tech* mods are not responsible for this, it happened with very large forceloaded area + very many crafters (multiblocks, machines... in total 2500+)
It didn't happen when there were only small amount of it.
I suspect if it could be lithium / chunk access fault, somehow...

**Comment by Technici4n** [comment]
If anyone encounters the issue again, I will need some reproduction steps. For now I don't really want to deal with it, sorry. 😅
