### ISSUE TITLE
Textures in "textures/blocks" instead of "textures/block"

### ISSUE THREAD

**Issue by lukebemish** [AztechMC/Modern-Industrialization#295]
The vanilla convention is for block textures to end up in `textures/block`, not `textures/blocks`. As MI doesn't follow this convention, unexpected behavior can result when combined with other mods that might have this expectation. See lukebemish/excavated_variants#44.

**Comment by Technici4n** [comment]
We'll probably fix some of these as we work on more datagen (soon TM), but it would be easier for you to check blocks/ than for us to change everything. Especially since it's reasonable for us to assume that we place these textures in whatever folder we prefer.

**Comment by lukebemish** [comment]
Yes, I understand this; however, I will only check the vanilla convention places, as for the most part I *don't* actually check this; it's a bit of an edge case already. I rely on blockstate files instead. However, as modern industrialization uses neither blockstate files nor block models, my mod is forced to guess at the texture location.

**Comment by Technici4n** [comment]
We do actually use blockstate files but they are generated via arrp for the moment. That will be solved soon.

**Comment by lukebemish** [comment]
Yes, that makes sense; since my mod uses arrp as well, it can't see files generated by arrp by other mods.

**Comment by Technici4n** [comment]
Ah I see, should be resolved soon yeah. I'll reopen this just to remember, actually.

**Comment by Azercoco** [comment]
Fixed with  #300.
