### ISSUE TITLE
Feature: Ctrl-click to copy items from REI to Item Pipe filter

### ISSUE THREAD

**Issue by todofixthis** [AztechMC/Modern-Industrialization#297]
I was delighted to discover that I can use REI to quickly configure Assemblers (ctrl-click on an item in REI to set+lock inputs and outputs) 😻  This is a huge timesaver, so that I don't have to go hunt down the items in my base that I want my Assebler to use (and then figure out how to inject them back into the system when I'm done).

Similarly, it would be awesome if the same trick could be used to configure an Item Pipe's whitelist/blacklist filter — i.e., ctrl-click on an item in REI to add that item to the item pipe's filter.

**Comment by Technici4n** [comment]
Thanks for the idea. Not sure about that feature, that seems a bit unintuitive to me. But I'm open for discussion.

Note that you can already drag items from REI to the filter slots for quick and easy configuration. ;)

**Comment by todofixthis** [comment]
> Note that you can already drag items from REI to the filter slots for quick and easy configuration. ;)

Ooh, I did not know that I could do this 😅  Will try this out, thanks!

**Comment by todofixthis** [comment]
Just tried this out, and it works a treat.  Gonna close this feature request, as it's already implemented 😸
