### ISSUE TITLE
Changing a machine's locked inventory slots is super difficult when the machine has connected item pipes

### ISSUE THREAD

**Issue by todofixthis** [AztechMC/Modern-Industrialization#298]
Sometimes I need to reconfigure a machine's inventory, e.g. changing the locked inputs for an Assembler, or swapping out locked items in a Configurable Chest.  When the machine in question is already installed and part of my base's network, this can be very tricky to do.

Currently, I would need to unlock the slot, remove the item stack currently in that slot, and then quickly lock it to air, so that the connected item pipes don't feed more items into the slot I just emptied.  Sometimes this takes multiple tries, as I'm not that fast with a mouse 😓

Alternatively, I could use my Wrench to disconnect any pipes currently inputting items.  This works OK for fluid pipes, but for item pipes I then have to manually restore its filter items when I want to reconnect it to the machine later, which can be quite a pain, especially if the item pipe had a lot of items in its filter before I disconnected it.

It would be super helpful if there were some way to temporarily prevent a machine from taking items from connected item pipes, so that I can reconfigure the machine at my own pace, and then turn inputs back on when I am finished.

**Comment by Technici4n** [comment]
Interesting suggestion! But maybe something like "empty slot to inventory, and lock the slot to air" would work for you? Then you could drag the new items from REI.

**Comment by todofixthis** [comment]
> Interesting suggestion! But maybe something like "empty slot to inventory, and lock the slot to air" would work for you? Then you could drag the new items from REI.

Good call; I think that would solve the problem quite neatly.

**Comment by Shylie** [comment]
> Interesting suggestion! But maybe something like "empty slot to inventory, and lock the slot to air" would work for you? Then you could drag the new items from REI.

Personally I have had issues with this approach-- since it's already connected to the item pipe network, it sometimes gets more items before you can lock it to air.

**Comment by todofixthis** [comment]
> > Interesting suggestion! But maybe something like "empty slot to inventory, and lock the slot to air" would work for you? Then you could drag the new items from REI.
> 
> Personally I have had issues with this approach-- since it's already connected to the item pipe network, it sometimes gets more items before you can lock it to air.

Ahh, I misunderstood @Technici4n's response; I thought that they were suggesting to add a feature to do both in one click.  Yes, I agree with you @Shylie it can be really hard to time this right, even for a player who is fast with the mouse (I'm not 😅).

**Comment by todofixthis** [comment]
I'm also going to change the title/description for this issue, as I see that I have fallen victim to [the xy problem](https://xyproblem.info/) 😅

**Comment by todofixthis** [comment]
Whilst rewriting my OP to focus on the problem rather than potential solutions, I thought of another workaround ([see, I told you 😹](https://xyproblem.info/)), which is to use the wrench to disconnect 2 item pipes somewhere in the middle, so that the item pipe's connection to the machine is still intact, but there's no longer a path for items to reach it.

E.g.,:

```
Chest >---------> Machine
           ^    ^
           |    |
           |    Don't disconnect here
           |
           Disconnect here instead
```

Even if this works I'd still recommend implementing something to make this easier or more intuitive — it took some lateral thinking to get here, and only after pondering the problem for a lot longer than I think most players would bother to 😇

**Comment by Technici4n** [comment]
My idea was indeed to add a feature to do both in one click.

**Comment by Technici4n** [comment]
Will be in the next release. First time is without shift, second time is with shift:
https://user-images.githubusercontent.com/13494793/172058929-b86effc5-8e80-4ce4-b8d2-714da6f5e15a.mp4
