### ISSUE TITLE
Strange boiler behavior whin bamboo

### ISSUE THREAD

**Issue by trlolo** [AztechMC/Modern-Industrialization#314]
Boiler dont heat to maximum temperature when low energy density fuel like bamboo is used.
1)Bamboo
![2022-06-03_17 26 07](https://user-images.githubusercontent.com/43910955/171873952-fa81a27d-3c43-4d45-b9d5-f3ba923546fa.png)
![2022-06-03_17 26 09](https://user-images.githubusercontent.com/43910955/171873974-6f7e1438-1a80-4fa5-9686-660f4ce28fe4.png)
2)Dried kelp
![2022-06-03_17 29 09](https://user-images.githubusercontent.com/43910955/171874545-943c9954-87a6-4519-abed-c54d6f2fa6b4.png)
![2022-06-03_17 29 07](https://user-images.githubusercontent.com/43910955/171874567-a5723a07-24ec-4500-9659-ed316fca860c.png)
3)Coke
![2022-06-03_17 31 17](https://user-images.githubusercontent.com/43910955/171874928-7ed179ef-af2f-4b30-a492-68acf7e4df17.png)
![2022-06-03_17 31 14](https://user-images.githubusercontent.com/43910955/171874944-cc5b87c8-826d-49eb-bb0a-bfa042414dbd.png)
Reproduction
1) Build advanced high presure boiler like on image
![2022-06-03_17 23 24](https://user-images.githubusercontent.com/43910955/171873405-22a1d911-849d-446c-aa2b-48bb378d4820.png)
2) Supply water and bamboo (AE chest and export bus used for bamboo suply only)
![2022-06-03_17 21 11](https://user-images.githubusercontent.com/43910955/171872955-e1f19c42-bd39-4201-9883-5f97fb22cd2c.png)
3) Look on temperature of boiler
![2022-06-03_17 24 09](https://user-images.githubusercontent.com/43910955/171873548-adba00f2-7ea5-497d-a0c0-b7216b32f240.png)
![2022-06-03_17 24 14](https://user-images.githubusercontent.com/43910955/171873560-4ce7a3b9-bf93-4624-af3f-f50e6e612189.png)

**Comment by Azercoco** [comment]
This a feature, because the boiler can only burn one item per tick and because 1 bamboo per tick is nout enough to reach its maximum output, the temperature doesn't therefore reach its maximum (the output is proportional to the temperature).
