### ISSUE TITLE
Render bug ores

### ISSUE THREAD

**Issue by Romz24** [AztechMC/Modern-Industrialization#32]
After some update, all ores from this mod are no longer displayed correctly. If you try to put any block in their place, they appear. This was not the case before, I do not know when this bug appeared. Can I fix this somehow?

https://youtu.be/J2-BlMhQC7w

**Comment by Technici4n** [comment]
Hey, which version of MI are you using? If it's 0.3.8, please revert to 0.3.7, as 0.3.8 is buggy and was removed from Curseforge!

**Comment by Romz24** [comment]
I rolled back to version 0.3.7, this version really has no problems with ore display. I'm waiting for the next update.

**Comment by Technici4n** [comment]
Good! Next update is going to take a while...
