### ISSUE TITLE
Visual bug when opening modern industrialization manual book

### ISSUE THREAD

**Issue by Azzmikaelson** [AztechMC/Modern-Industrialization#322]

**Comment by Technici4n** [comment]
Could you provide a screenshot and more info (what you expect instead)?

**Comment by Azzmikaelson** [comment]
![image](https://user-images.githubusercontent.com/104194329/173033178-12864bd7-4b7e-48f3-962f-5ab94b3ad3bf.png)

**Comment by Azercoco** [comment]
Fixed by e504671adda5c4a2edeab14743875f391f8a3180.
