### ISSUE TITLE
Animations don`t work with Sodium+Indium

### ISSUE THREAD

**Issue by belkinPNG** [AztechMC/Modern-Industrialization#323]
Vanilla
![Base Profile 2022 06 09 - 09 23 48 03](https://user-images.githubusercontent.com/106972489/172780420-7aae6788-bef4-4ae5-ad77-8e2455fd7a3c.gif)

With Sodium+Indium(all the mods latest versions)
![Base Profile 2022 06 09 - 09 27 05 04](https://user-images.githubusercontent.com/106972489/172780598-2a1afa2b-bc13-4c19-8fbc-426d0911f2cd.gif)

Don`t works all animations in the mod.

**Comment by Technici4n** [comment]
That's a sodium issue, I'm afraid there's nothing I can do about it. In general, please don't report sodium-specific issues.

**Comment by Technici4n** [comment]
I did check on the sodium discord server, and it seems that this should actually be fixable on MI's side.

**Comment by Desempregago** [comment]
This can be temporarily solved by unticking `Animate Only Visible Textures`
