### ISSUE TITLE
Dedicated server crash - java.lang.IllegalArgumentException: Empty Fluid Volume's must have an amount of 0!

### ISSUE THREAD

**Issue by ProsperCraft** [AztechMC/Modern-Industrialization#33]
https://gist.github.com/ProsperCraft/b70891223a956ea7c7beffed9ca3b8ea

Player had the pipe in a nomad book, which worked fine deploying over and over, however he got hit with a bad explosion, and picked up what was left of the nomad book(mobile base) and when he was in the overworld and deployed it, it crashed the server.

**Comment by Technici4n** [comment]
Thanks for reporting! It should be fixed in the next version, of which you will be able to download a nightly build [here](https://github.com/AztechMC/Modern-Industrialization/actions/runs/366975908) in about 10 minutes... Please re-open if that doesn't fix it
