### ISSUE TITLE
New version notification even though im on a newer version?

### ISSUE THREAD

**Issue by Trnrr** [AztechMC/Modern-Industrialization#333]
Am I missing something or is this a bug? I downloaded the version of modrinth.
![image](https://user-images.githubusercontent.com/20446954/174689970-c41c2318-1251-48da-a2a4-918b96ab9aca.png)
![image](https://user-images.githubusercontent.com/20446954/174689996-23cc05cf-01b5-4f38-9fde-0eb1d8fb886f.png)
![image](https://user-images.githubusercontent.com/20446954/174690053-e6a2bfe1-fe32-4906-94d4-343311056698.png)

**Comment by Azercoco** [comment]
Did it still happen today ? It could be that the Curseforge API took some time for update the new version ...

**Comment by Trnrr** [comment]
Must have been that. I got it later that night but I don't see the message today. Must have been curseforge being slow
