### ISSUE TITLE
Copper Plates

### ISSUE THREAD

**Issue by Vizaria** [AztechMC/Modern-Industrialization#344]
How come your mod doesn't have a means of making copper plates in the compressor like it used too meanwhile it still uses copper in recipes that require copper plates. using the other mod is super inconvenient when I should just be able to put copper in the compressor like every other item from your mod

**Comment by Azercoco** [comment]
The Compressor works fine. The issue comes from your custom datapack.
![image](https://user-images.githubusercontent.com/20425137/175371080-95753d29-61ed-45ce-9eb5-cbc7bce2601c.png)

**Comment by Azercoco** [comment]
Yours does.

**Comment by Vizaria** [comment]
well this pack used to have those recipes and now it doesn't and all i did was update the pack so im not sure how that happened but alright thanks i guess

**Comment by FederAndInk** [comment]
I am having this issue, where on servers it is working but not in single players, with the same config and kubejs scripts.
Can you tell me which pack it is?

**Comment by Vizaria** [comment]
The pack i was using was called "Another Quality Mod pack 2" but this issue was never truely resolved the mod developer just marked it as closed like a douche and swept it under the rug so i cant really help. Sorry

**Comment by FederAndInk** [comment]
> The pack i was using was called "Another Quality Mod pack 2" but this issue was never truely resolved the mod developer just marked it as closed like a douche and swept it under the rug so i cant really help. Sorry

No problem, I am on the AQM2 team, we are looking into this issue right now, being tracked here: https://github.com/itsdinkd/AQM2/issues/74

And we found out what's causing it: kubejs script loading order

**Comment by Technici4n** [comment]
> the mod developer just marked it as closed like a douche and swept it under the rug

Please understand that we have limited time, and that we only control MI. If a modpack or another mod changes recipes in MI, there is nothing we can do about it, and we'd rather work on MI than debug who caused such issues.
