### ISSUE TITLE
Textures bugged on 1.19 with JourneyMap

### ISSUE THREAD

**Issue by rdrpenguin04** [AztechMC/Modern-Industrialization#348]
So, this is something I didn't expect.

```
[12:03:56] [JM-task-20/ERROR]: Unexpected error during getSprites(): modern_industrialization:lignite_coal_ore - java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.method_12832()" because the return value of "net.minecraft.class_1058.method_4598()" is null
	at journeymap.client.mod.vanilla.VanillaBlockSpriteProxy.getSprites(VanillaBlockSpriteProxy.java:115)
```

This error repeats for every block in the game, so almost every block shows up as a default texture. Meanwhile, the book looks like corrupted garbage, which I'd assume is related.

No other mods I have installed are having issues. I understand that the current version is unfinished, I just felt I should communicate this issue. Thank you all so much for your work on this awesome mod; let me know if there's any way I can help!

**Comment by Technici4n** [comment]
There is no released build for 1.19 yet?

Also please provide the full exception stack trace.

**Comment by rdrpenguin04** [comment]
This is a self-built version; I understand that it's unfinished. Also, that is the full stack trace I'm getting in the log; let me know if there's something else I should be doing, but that is as far as it goes before it hits another message, and no other error of the same type goes any farther either.

Reading a bit closer, this may just straight-up be a JourneyMap error, but I'm guessing it's still caused by MI breaking somewhere else. I'll make a full game log, gimme a sec.

**Comment by rdrpenguin04** [comment]
After disabling some mods to isolate the problem, the book is no longer corrupted; it's also a default texture. Something in the Sodium-Indium-Iris chain must not have been expecting a null texture or something like that.

The log is spammed with `FileNotFoundException`s; I'm assuming I built the mod incorrectly. Will do further research.

**Comment by rdrpenguin04** [comment]
Okay; JourneyMap is not an issue. I'm still experiencing some bugs potentially; I'll open a new issue if I find a root cause.
