### ISSUE TITLE
[BUG] Crushed Ore sometimes gets stuck in Steam Macerator

### ISSUE THREAD

**Issue by RolanDecoy** [AztechMC/Modern-Industrialization#35]
As described in the title.

Running v0.3.7, used vanilla hopper to insert several stacks of various ores into the macerator. It loads the stacks correctly into the machine, begins processing. Sometimes the item doesn't disappear from the input slot, but the proces (bar) is running. It will give no output. The situation can be resolved by removing the item from the input slot manually. Re-inserting said item will not proces it for some reason. This happens once every 5 ~ 10 stacks or so. I have only experienced this with Crushed Ore as input item. This MAY be a skipped update / hickup or some such, since I have other mods running, but thought I'd mention it in any case.

**Comment by Technici4n** [comment]
Unfortunately, nobody was ever able to reproduce this issue, and we have reworked the machine code since then. Please open a new issue if you can reproduce this in newer versions.
