### ISSUE TITLE
[Suggestion] More uses for Lubricant in the early game + Coolant idea using Antimony

### ISSUE THREAD

**Issue by Desempregago** [AztechMC/Modern-Industrialization#355]
These are my main ideas:

• **_More uses for Lubricant_** - Processing machines like Macerators, Compressors and Cutting Machines could consume 1mb of Lubricant every 10 ticks when working for more than 5 seconds. Suggesting this because Lubricant has way too few uses outside of speeding up overclock progress in electric machines and as "fuel" for Cutting Machines.

• **_Synthetic Coolant_** - Made with 4x Antimony Dust, 250mb of either Raw or Synthetic Oil and 2x Lapis Dust in a Mixer. Used to cool down machines that are prone to heating due to constant friction of its parts, like Macerators and Cutting Machines, maybe Compressors too. Suggesting it because machines usually are set and forget, specially in the early game and I want them to require a little bit more of infrastructure before starting to lay them out in the processing lines. Also makes more use of Antimony outside of making Battery Alloy and RAM Sticks

*thanks to Inventory Tabs, UI is messed up.*
![image](https://user-images.githubusercontent.com/14002834/176953646-733100c7-6684-4a57-98e4-1c36e980ff68.png)

![image](https://user-images.githubusercontent.com/14002834/176954651-c1d0a0c9-3c33-4962-8ef0-5a72c2e9afe3.png)

**Comment by Desempregago** [comment]
Probably tiny dusts instead of regular dusts, since my idea also affects electric machines, so alongside energy consumption, you'll need to worry about lubricant and coolant production/throughput

**Comment by Technici4n** [comment]
I don't like the idea of adding more required fluids for machines. This is a particularity of the cutting machine, and shouldn't be generalized. I think we will use lubricant when we introduce more early-game gear options... We'll see when we get to it. ;)
