### ISSUE TITLE
(Suggestion) Remove REI dependency?

### ISSUE THREAD

**Issue by jimmytrouser** [AztechMC/Modern-Industrialization#356]
Is it possible to remove the REI dependency so I can use test EMI instead?

Love the mod thanks for sharing.

**Comment by Technici4n** [comment]
Please see #326 for an explanation of why it will not be done, and what the consequences might be. On Fabric, you can use loader dependency overrides to remove the dependency. Otherwise, removing the dependency from the `fabric.mod.json` is always an option.
