### ISSUE TITLE
[1.19] Startup crash in combination with Applied Energistics 2

### ISSUE THREAD

**Issue by Geartwo** [AztechMC/Modern-Industrialization#357]
AE2-Version: 12.0.1-alpha
MI-Version:  1.3.0-beta
Fabric-API: 0.57.0

The crash appears in an AE2 modul after MI trys to inject a custom P2P tunnel.
"aztech.modern_industrialization.compat.ae2.MIAEAddon.onAe2Initialized(MIAEAddon.java:51)"

Crash report:
https://pastebin.com/ar9mTDuj

**Comment by TheCherry** [comment]
The game crashs now then the enableAe2Integration is on false and Ae2 is installed.
Just as info, its a bit strange.

**Comment by Technici4n** [comment]
Please provide the crash log.
