### ISSUE TITLE
quantum armor fly mode floats upwards in space dimensions worlds

### ISSUE THREAD

**Issue by warior456** [AztechMC/Modern-Industrialization#360]
when in space dimensions mod (fabric) the quantum armor makes you float upwards when in "creative flight" mode (this doesn't happen with actual creative flight)

**Comment by Technici4n** [comment]
Please give proper information: what behavior you noticed, what you expected, etc...

**Comment by Technici4n** [comment]
Looks like an issue with how the space dimensions mod handles flying? We're only enabling the ability for the player to fly using PlayerAbilityLib, nothing we can really do about this.
