### ISSUE TITLE
1.19 crashes when trying to update mod

### ISSUE THREAD

**Issue by jacketkid323** [AztechMC/Modern-Industrialization#361]
i tried to update the mod to a newer version of mi from an older 1.19 version of the mod here is the crash log:
[crash-2022-07-17_17.59.01-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/9127497/crash-2022-07-17_17.59.01-client.txt)

**Comment by Technici4n** [comment]
I don't see how MI is related to this crash.
