### ISSUE TITLE
Where to get EU energy?

### ISSUE THREAD

**Issue by ZiSXD** [AztechMC/Modern-Industrialization#364]
I do not see a single block in the mod that generates energy, there are other mods (AOF5), but there are other energy units that do not interact with pipes and blocks from Modern Industrialization.
   
*************Written with the help of a translator**********

**Comment by ZiSXD** [comment]
I forgot to clarify, I don't see blocks that don't use steam for energy.

**Comment by Technici4n** [comment]
You can for example use a boiler to produce steam, and a steam turbine to turn that into EU. Check the guidebook for more information.
