### ISSUE TITLE
Crash on 1.18.2 when right clicking a compressor (few other machines too)

### ISSUE THREAD

**Issue by overfriended** [AztechMC/Modern-Industrialization#365]
I've removed several mods related to rendering to see if that was the cause, but I have not figured out why this is happening. Is there a mod causing this I can't see? Singleplayer and multiplayer
https://pastebin.com/raw/1NG4h4nh

**Comment by overfriended** [comment]
I've confirmed it works without my mods, but I want to know which mod it is.

**Comment by Technici4n** [comment]
Unfortunately the crash doesn't say which mod causes this. Somehow there is an issue with how steam is rendered, but I don't see why another mod would influence steam rendering.

**Comment by overfriended** [comment]
@Technici4n The cause was Colormatic.
