### ISSUE TITLE
[Feature] Replicator Blacklist

### ISSUE THREAD

**Issue by TheCherry** [AztechMC/Modern-Industrialization#366]
It would be nice if we can get a blacklist in the config for the replicator.
Else I have to disable the replicator on our dedicated server.

**Comment by TheCherry** [comment]
Even better would be, if we can set the amount of UU-Matter for a item / block and if a item have -1 or none as value its not "replicatable".

**Comment by Technici4n** [comment]
For now we will keep a fixed amount of UU-Matter per replica. The blacklist is configured via the `#modern_industrialization:replicator_blacklist` tag: https://github.com/AztechMC/Modern-Industrialization/blob/master/src/generated/resources/data/modern_industrialization/tags/items/replicator_blacklist.json.

**Comment by TheCherry** [comment]
thx, so I have to implement a datapack for that? I played mc for a few years not.
Is it not easier within the json config file, as a simple array? For me as a server owner would that be a bit better at last.

**Comment by Technici4n** [comment]
You can use datapacks, yes. It takes a bit to get used to it but it's a powerful tool. You can find more info online, most likely.
