### ISSUE TITLE
compatibility issue with supplementaries | fabric 1.19 

### ISSUE THREAD

**Issue by Surpos0** [AztechMC/Modern-Industrialization#370]
I have problem when i open my inventory and i use Roughly enough items to check items from  my game crash.
When i use this mods separate they work fine, but together they crash game.

 

---- Minecraft Crash Report ----
Time: 8/3/22, 9:19 PMDescription: Rendering entry
java.lang.NullPointerException: Cannot read field "itemOutputs" because "this.recipe" is null at aztech.modern_industrialization.compat.rei.machines.MachineRecipeDisplay.getItemOutputs(MachineRecipeDisplay.java:73) at aztech.modern_industrialization.compat.rei.machines.MachineRecipeDisplay.getOutputEntries(MachineRecipeDisplay.java:82) at me.shedaniel.rei.impl.client.view.ViewsImpl.isRecipesFor(ViewsImpl.java:294) at me.shedaniel.rei.impl.client.gui.widget.EntryWidget._getTransferHandler(EntryWidget.java:318) at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getTransferHandler(EntryWidget.java:359) at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getCurrentTooltip(EntryWidget.java:437) at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry.getCurrentTooltip(EntryListStackEntry.java:191) at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.queueTooltip(EntryWidget.java:414) at me.shedaniel.rei.impl.client.gui.widget.DisplayedEntryWidget.queueTooltip(DisplayedEntryWidget.java:60) at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:369) at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:246) at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:139) at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:110) at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:196) at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:330) at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:239) at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:398) at net.minecraft.class_757.handler$zmg000$renderScreenPost(class_757.java:12596) at net.minecraft.class_757.method_3192(class_757.java:881) at net.minecraft.class_310.method_1523(class_310.java:1143) at net.minecraft.class_310.method_1514(class_310.java:734) at net.minecraft.client.main.Main.main(Main.java:237) at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29) at crystallauncher.MineClient.start(MineClient.java:213) at crystallauncher.MineClient.main(MineClient.java:36)

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Render threadStacktrace: at aztech.modern_industrialization.compat.rei.machines.MachineRecipeDisplay.getItemOutputs(MachineRecipeDisplay.java:73) at aztech.modern_industrialization.compat.rei.machines.MachineRecipeDisplay.getOutputEntries(MachineRecipeDisplay.java:82) at me.shedaniel.rei.impl.client.view.ViewsImpl.isRecipesFor(ViewsImpl.java:294) at me.shedaniel.rei.impl.client.gui.widget.EntryWidget._getTransferHandler(EntryWidget.java:318) at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getTransferHandler(EntryWidget.java:359) at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getCurrentTooltip(EntryWidget.java:437) at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry.getCurrentTooltip(EntryListStackEntry.java:191) at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.queueTooltip(EntryWidget.java:414)
-- Screen details --Details: Screen name: net.minecraft.class_481Stacktrace: at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:50) at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:44) at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:248) at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:139) at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:110) at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:196) at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:330) at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:239) at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:398) at net.minecraft.class_757.handler$zmg000$renderScreenPost(class_757.java:12596) at net.minecraft.class_757.method_3192(class_757.java:881) at net.minecraft.class_310.method_1523(class_310.java:1143) at net.minecraft.class_310.method_1514(class_310.java:734) at net.minecraft.client.main.Main.main(Main.java:237) at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29) at crystallauncher.MineClient.start(MineClient.java:213) at crystallauncher.MineClient.main(MineClient.java:36)
-- Renderer details --Details: Renderer name: me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry Z level: 0 Bounds: me.shedaniel.math.Rectangle@1ed53dbd[height=18,width=18,x=380,y=174] Notice mark: 0 Interactable: true Interactable favorites: true Highlight enabled: true Tooltip enabled: true Background enabled: false Entries count: 1
-- Current Rendering Entry --Details: Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack Z level: 100 Entry type: minecraft:item Is empty: false Entry identifier: supplementaries:byg/sign_post_rainbow_eucalyptus
-- Entry Renderer --Details: Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition Item Type: byg/sign_post_rainbow_eucalyptus Item Damage: 0 Item NBT: null Item Foil: false
-- Screen details --Details: Screen name: net.minecraft.class_481
-- System Details --Details: Minecraft Version: 1.19 Minecraft Version ID: 1.19 Operating System: Windows 10 (amd64) version 10.0 Java Version: 17.0.1, Microsoft Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft Memory: 860356736 bytes (820 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB) CPUs: 16 Processor Vendor: AuthenticAMD Processor Name: AMD Ryzen 7 3800X 8-Core Processor              Identifier: AuthenticAMD Family 23 Model 113 Stepping 0 Microarchitecture: unknown Frequency (GHz): 3.90 Number of physical packages: 1 Number of physical CPUs: 8 Number of logical CPUs: 16 Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti Graphics card #0 vendor: NVIDIA (0x10de) Graphics card #0 VRAM (MB): 4095.00 Graphics card #0 deviceId: 0x1c82 Graphics card #0 versionInfo: DriverVersion=27.21.14.6627 Memory slot #0 capacity (MB): 8192.00 Memory slot #0 clockSpeed (GHz): 3.20 Memory slot #0 type: DDR4 Memory slot #1 capacity (MB): 8192.00 Memory slot #1 clockSpeed (GHz): 3.20 Memory slot #1 type: DDR4 Virtual memory max (MB): 18742.21 Virtual memory used (MB): 16513.29 Swap memory total (MB): 2432.00 Swap memory used (MB): 167.27 JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096M -Xms4096M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M Fabric Mods:  additionaladditions: Additional Additions 5.0.1 libgui: LibGui 6.0.0-beta.5+1.19-pre1 jankson: Jankson 4.1.1+j1.2.1 blue_endless_jankson: jankson 1.2.1 libninepatch: LibNinePatch 1.1.0 additionalstructures: Additional Structures 4.0.0 advancementplaques: Advancement Plaques 1.4.5 adventurez: AdventureZ 1.4.14 ae2: Applied Energistics 2 12.0.2-alpha alloy_forgery: Alloy Forgery 2.0.15+1.19 alloygery: Alloygery 2.1+1.19 another_furniture: Another Furniture 2.0.1-1.19 apocalypse: Apocalypse Origins 0.2.25 apollo: Apollo's Additional Structures 1.3 appleskin: AppleSkin 2.4.0+mc1.19 arcanus: Arcanus 1.30 architectury: Architectury 5.10.33 artifacts: Artifacts 7.1.1+fabric com_github_llamalad7_mixinextras: MixinExtras 0.0.11 expandability: ExpandAbility 6.0.0 step-height-entity-attribute: Step Height Entity Attribute 1.0.0 awesomedungeon: Awesome Dungeon 2.0.11 awesomedungeonend: Awesome Dungeon Edition end 1.0.3 awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.3 awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.8 bclib: BCLib 2.0.19 betteranimalsplus: Better Animals Plus 1.19-11.0.7 betterend: Better End 2.0.11 betternether: Better Nether 7.0.8 bewitchment: Bewitchment 1.19-4 fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT impersonate: Impersonate 2.6.1 midnightlib: MidnightLib 0.5.2 playerabilitylib: Pal 1.6.0 reach-entity-attributes: Reach Entity Attributes 2.3.0 terraform-wood-api-v1: Terraform Wood API (v1) 4.1.0 biomemakeover: Biome Makeover 1.19-1.5.9 bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.1-1.19 maelstrom_library: Maelstrom Library 1.3-1.19-pre1 multipart_entities: MultipartEntities 1.2-1.19-pre1 bwplus: Bewitchment Plus 1.19-4 byg: Oh The Biomes You'll Go 2.0.0.7 cardinal-components: Cardinal Components API 5.0.1 cardinal-components-base: Cardinal Components API (base) 5.0.1 cardinal-components-block: Cardinal Components API (blocks) 5.0.1 cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1 cardinal-components-entity: Cardinal Components API (entities) 5.0.1 cardinal-components-item: Cardinal Components API (items) 5.0.1 cardinal-components-level: Cardinal Components API (world saves) 5.0.1 cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1 cardinal-components-world: Cardinal Components API (worlds) 5.0.1 castle_dungeons: Castle Dungeons 3.3-1.19-fabric cave_enhancements: Cave Enhancements 1.19-FABRIC-1.3.1 cloth-api: Cloth API 4.0.65 cloth-basic-math: cloth-basic-math 0.6.1 cloth-client-events-v0: Cloth Client Events v0 4.0.65 cloth-common-events-v1: Cloth Common Events v1 4.0.65 cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65 cloth-utils-v1: Cloth Utils v1 4.0.65 cloth-config: Cloth Config v6 7.0.73 coloredglowlib: ColoredGlow Lib 1.3.4 copperhopper: Copper Hopper 0.0.9+1.19 creeperoverhaul: Creeper Overhaul 2.0.1 crockpot: Crock Pot 0.9.2+1.19 croptopia: Croptopia 2.0.7 com_typesafe_config: config 1.4.1 io_leangen_geantyref_geantyref: geantyref 1.3.11 org_spongepowered_configurate-core: configurate-core 4.1.2 org_spongepowered_configurate-hocon: configurate-hocon 4.1.2 ctov: ChoiceTheorem's Overhauled Villages 3.0.1 dataattributes: Data Attributes 1.2.1 dawn: Dawn API 3.5.0 doom: Doom Fabric 4.2.7 dungeon_now_loading: dungeon-now-loading-17-1 1.0.0 dungeons_arise: When Dungeons Arise 2.1.51 earlygame: EarlyGame 1.19-1.1.2 earthbounds: Earthbounds 1.19-1.1.3 earthtojavamobs: Earth2Java 1.9.2 ecologics: Ecologics 2.1.6 edenring: EdenRing 0.6.3 eldritch_mobs: EldritchMobs 1.12.5 endrem: End Remastered 5.1.1 enhancedcelestials: Enhanced Celestials 2.1.0.0 expandeddelight: Expanded Delight 0.2.1 expert_armor: Expert_Armor 2.0 expert_weapons: Expert Weapons and Tools 2.5 fabric: Fabric API 0.58.0+1.19 fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9 fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9 fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9 fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9 fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9 fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9 fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9 fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9 fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9 fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9 fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9 fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9 fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9 fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9 fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9 fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9 fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9 fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9 fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9 fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9 fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9 fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9 fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9 fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9 fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9 fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9 fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9 fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9 fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9 fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9 fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9 fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9 fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9 fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9 fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9 fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9 fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9 fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9 fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9 fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9 fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9 fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9 fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9 fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9 fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9 fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9 fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0 org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0 org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0 org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0 org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0 org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0 org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3 org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3 org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0 org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3 org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3 org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3 fabricloader: Fabric Loader 0.14.8 fallingtree: FallingTree 3.7.4 farmersdelight: Farmer's Delight 1.19-0.3.0 flytre_lib: FlytreLib 1.8.8 forgeconfigapiport: Forge Config API Port 4.0.2 com_electronwill_night-config_core: core 3.6.5 com_electronwill_night-config_toml: toml 3.6.5 forgero: Forgero 0.9.5-BETA-1.19 advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2 friendsandfoes: Friends&Foes 1.5.5 mm: Manningham Mills 2.3 fwaystones: Fabric Waystones 3.0.2+mc1.19 galosphere: Galosphere 1.19-1.1.1 geckolib3: Geckolib 3.1.6 com_eliotlash_mclib_mclib: mclib 18 com_eliotlash_molang_molang: molang 18 gobber2: Gobber2 2.6.27 pugh_lib: Pugh Lib 1.4.11 pugh_tools: Pugh Tools 1.3.15 graveyard: The Graveyard 1.10 omega-config: OmegaConfig 1.2.2-1.18.1 graveyard_biomes: The Graveyard Biomes 1.2 haema: Haema 1.10.2+1.19 satin: Satin 1.9.0 hopobetterunderwaterruins: Hopo Better Underwater Ruins 1.0.9 hplus: Hopper Plus 3.3.1 iceberg: Iceberg 1.0.38 immersive_weathering: Immersive Weathering 1.0.1-1.19_SNAPSHOT incantation: Incantation 0.1.5 incendium: Incendium 5.1.2 indium: Indium 1.0.7+mc1.19 inventorysorter: Inventory Sorter 1.8.10-1.19 kyrptconfig: Kyrpt Config 1.4.14-1.19 iris: Iris 1.2.6 org_anarres_jcpp: jcpp 1.4.14 java: OpenJDK 64-Bit Server VM 17 journeymap: Journeymap 5.8.5rc2 journeymap-api-fabric: JourneyMap API 1.19-1.8-fabric-SNAPSHOT libraryferret: Library Ferret 2.0.0 lightwithin: LightWithin Mod 0.1.2 renderer: Renderer 1.0 magicalforest: Magical Forest 2.1.0 marium: Marium's Soulslike Weaponry 0.8.4 materialisation: Materialisation 3.1.4 mca: Minecraft Comes Alive 7.3.14+1.19 mcda: MC Dungeons Armors 2.1.1 mcdar: MC Dungeons Artifacts 1.5.0 mcdw: MC Dungeons Weapons 4.4.0-1.19 enchant_giver: Enchant Giver 1.3.0 medievalweapons: Medieval Weapons 1.2.1 minecraft: Minecraft 1.19 modern_industrialization: Modern Industrialization 1.3.1 magna: Magna 1.8.0-1.19 noindium: No Indium? 1.1.0+1.19 team_reborn_energy: Energy 2.2.0 modid: Creatures Of The Snow 2.2.0+1.19 modmenu: Mod Menu 4.0.4 moonlight: Moonlight 1.19-2.0.10 moreweaponry: More Weaponry v1.19.4+1.19 customportalapi: Custom Portal Api 0.0.1-beta51-1.19 mythicmetals: Mythic Metals 0.15.1 mythicmounts: Mythic Mounts 1.19-7.0 naturalist: Naturalist 2.0.1 origins: Origins 1.6.2 apoli: Apoli 2.5.1 additionalentityattributes: Additionalentityattributes 1.0.0+1.19 calio: Calio 1.7.0 overweight_farming: Overweight Farming 1.19-1.5.3-fabric owo: oωo 0.7.3+1.19 patchouli: Patchouli 1.19-74-FABRIC fiber: fiber 0.23.0-2 pehkui: Pehkui 3.3.3+1.14.4-1.19.1 kanos_config: Kanos Config 0.3.1+1.14.4-1.19 playerex: PlayerEx 3.3.4 net_objecthunter_exp4j: exp4j 0.4.8 opc: Offline Player Cache 0.6.1 placeholder-api: Placeholder API 2.0.0-beta.7+1.19 presencefootsteps: Presence Footsteps 1.6.1 kirin: Kirin UI 1.11.0 promenade: Promenade 2.7.0 terraform-shapes-api-v1: Terraform Shapes API (v1) 4.0.0 repurposed_structures: Repurposed Structures 6.1.1+1.19 rocks: This Rocks! 1.6.1 roughlyenoughitems: Roughly Enough Items 9.1.520 rpgdifficulty: Rpg Difficulty 1.2.0 sodium: Sodium 0.4.2+build.16 org_joml_joml: joml 1.10.4 spiceoffabric: Spice of Fabric 1.5.3+1.19 coat: Coat 1.0.0-beta.18+mc22w17a nbtcrafting: NBT Crafting 2.1.4+mc1.19 tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a tweed4_base: tweed4_base 1.7.1+mc22w17a tweed4_data: tweed4_data 1.2.1+mc22w17a tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a splatus_spellbound_weapons: Spellbound Weapons 3.3.4 splatus_ultris: Ultris: Boss Expansion 5.6.4 structory: Structory 1.0.1 subterrestrial: Subterrestrial 1.0.3 supplementaries: Supplementaries 1.19-2.0.9 t_and_t: Towns and Towers - Structure Add-on 1.8 techreborn: Tech Reborn 5.3.2 reborncore: Reborn Core 5.3.2 terrablender: TerraBlender 2.0.0.120 terralith: Terralith 2.3 the_bumblezone: The Bumblezone - Fabric 6.1.4+1.19 fake-player-api: Fake Player API 0.4.0 transportables: Transportables 1.2.1 travelersbackpack: Traveler's Backpack 1.19-8.0.3 trinkets: Trinkets 3.4.0 unstructured: Unstructured 0.5.2+1.19 whisperwoods: Whisperwoods 1.19-2.1.1 wilderworld: WilderWorld 2.3.0 chord: Chord 1.8.0+1.19-fabric wwoo: William Wythers' Overhauled Overworld 3.1+1.19.1 Loaded Shaderpack: (off)

**Comment by Technici4n** [comment]
I think I found the fix, I will also you to confirm once 1.3.2 is released (in a few minutes).

**Comment by Surpos0** [comment]
Its fixed Yay
