### ISSUE TITLE
Fluid display of modern industrialization mods

### ISSUE THREAD

**Issue by xiaodou233333** [AztechMC/Modern-Industrialization#372]
![QQ图片20220816144837](https://user-images.githubusercontent.com/61956441/184815699-7c7d4e06-2c5c-40fc-91c5-065a9330d354.png)
There is no problem with starting with a single mod
This bug does not appear in 1.3.1, but appears in versions above 1.4.0

**Comment by Technici4n** [comment]
Did you find a fix? AOF is struggling with this.

**Comment by deluxghost** [comment]
what do you mean by "1.4.0"?

**Comment by deluxghost** [comment]
> Did you find a fix? We probably just forgot the translation key.

btw, could you merge #363?

**Comment by zakari66** [comment]
The 1.4.0 relates to a modpack version / not the mod version (AOF5 is the modpack).

I'm experiencing the same on 1.5.1 on that pack (MC 1.18, Mod version 1.2.2) the name of some fluids render correctly (Oxygen ...) some others render as fluid.modern_industrialization.fluidname.

**Comment by Technici4n** [comment]
Porting lib issue, they are breaking MI fluid names.
