### ISSUE TITLE
Manganese ingots and nuggets are unobtainable

### ISSUE THREAD

**Issue by heyjudek** [AztechMC/Modern-Industrialization#374]
So, I am currently on MI 1.2.2 and discovered this issue through REI. I can obtain Manganese tiny dusts and craft them into Manganese dust. However, I cannot in any way turn them into their ingot form. According to REI, the only way to get ingots is with Manganese nuggets, which require Manganese nuggets. So, they are on a closed loop and cannot be obtained.
It should be possible to place manganese dust either in a furnace or an electric blast furnace to turn them into ingots.

**Comment by Azercoco** [comment]
Closed by d706c66708604388eb5e0f182b87e4a34cba782e
