### ISSUE TITLE
After Server reboot, the pipes won't reconnect appropriately

### ISSUE THREAD

**Issue by MrMoogles** [AztechMC/Modern-Industrialization#375]
It looks like when a server is rebooted, the pre-existing pipes that were attached to two blocks, now only attach to one and I can't configure it to reattach to the other. It feels like the world knows there's already a block there and refuses to redo the connection. We tried a different color pipe and it worked before, but now even that's not a solution. We can work around it by moving the tanks, chests, whatever else around.

Using version: Modern Industrialization 1.2.2
On Modpack: All of Fabric 5, 1.5.1

I even tried using world edit to replace the pre-existing pipes to air but nope. If I build in a different location the pipes connect as expected.

**Comment by Technici4n** [comment]
This generally happens whenever the game crashes unexpectedly, and the world data (including where pipes are) gets desynced from the actual blocks. You can enable debug commands and use `/mi pipes clear x y z` to remove any leftover pipe data.
