### ISSUE TITLE
Names of fluids missing.

### ISSUE THREAD

**Issue by Elliad-Live** [AztechMC/Modern-Industrialization#378]
![image](https://user-images.githubusercontent.com/10016064/190958931-f6dfa836-e299-482f-98f7-5f32f27d473a.png)
Several liquids are missing their name when viewed outside of their bucket. The is an issue cause it also means several liquids are missing their name when viewed in machine inputs or in tanks. Screen shot from AOF 5 after I made sure it had the most recent version of this mod..

**Comment by Elliad-Live** [comment]
`{
  "fluid.modern_industrialization.acrylic_acid": "Acrylic Acid",
  "fluid.modern_industrialization.acrylic_glue": "Acrylic Glue",
  "fluid.modern_industrialization.benzene": "Benzene",
  "fluid.modern_industrialization.boosted_diesel": "Boosted Diesel",
  "fluid.modern_industrialization.butadiene": "Butadiene",
  "fluid.modern_industrialization.caprolactam": "Caprolactam",
  "fluid.modern_industrialization.chlorine": "Chlorine",
  "fluid.modern_industrialization.chromium_hydrochloric_solution": "Chromium Hydrochloric Solution",
  "fluid.modern_industrialization.creosote": "Creosote",
  "fluid.modern_industrialization.crude_oil": "Crude Oil",
  "fluid.modern_industrialization.cryofluid": "Cryofluid",
  "fluid.modern_industrialization.deuterium": "Deuterium",
  "fluid.modern_industrialization.diesel": "Diesel",
  "fluid.modern_industrialization.diethyl_ether": "Diethyl Ether",
  "fluid.modern_industrialization.ethanol": "Ethanol",
  "fluid.modern_industrialization.ethylbenzene": "Ethylbenzene",
  "fluid.modern_industrialization.ethylene": "Ethylene",
  "fluid.modern_industrialization.heavy_fuel": "Heavy Fuel",
  "fluid.modern_industrialization.heavy_water": "Heavy Water",
  "fluid.modern_industrialization.heavy_water_steam": "Heavy Water Steam",
  "fluid.modern_industrialization.helium": "Helium",
  "fluid.modern_industrialization.helium_3": "Helium 3",
  "fluid.modern_industrialization.helium_plasma": "Helium Plasma",
  "fluid.modern_industrialization.high_pressure_heavy_water": "High Pressure Heavy Water",
  "fluid.modern_industrialization.high_pressure_heavy_water_steam": "High Pressure Heavy Water Steam",
  "fluid.modern_industrialization.high_pressure_steam": "High Pressure Steam",
  "fluid.modern_industrialization.high_pressure_water": "High Pressure Water",
  "fluid.modern_industrialization.hydrochloric_acid": "Hydrochloric Acid",
  "fluid.modern_industrialization.hydrogen": "Hydrogen",
  "fluid.modern_industrialization.light_fuel": "Light Fuel",
  "fluid.modern_industrialization.liquid_air": "Liquid Air",
  "fluid.modern_industrialization.lubricant": "Lubricant",
  "fluid.modern_industrialization.manganese_sulfuric_solution": "Manganese Sulfuric Solution",
  "fluid.modern_industrialization.methane": "Methane",
  "fluid.modern_industrialization.naphtha": "Naphtha",
  "fluid.modern_industrialization.nitrogen": "Nitrogen",
  "fluid.modern_industrialization.nylon": "Nylon",
  "fluid.modern_industrialization.oxygen": "Oxygen",
  "fluid.modern_industrialization.platinum_sulfuric_solution": "Platinum Sulfuric Solution",
  "fluid.modern_industrialization.polyethylene": "Polyethylene",
  "fluid.modern_industrialization.polyvinyl_chloride": "Polyvinyl Chloride",
  "fluid.modern_industrialization.propene": "Propene",
  "fluid.modern_industrialization.purified_platinum_sulfuric_solution": "Purified Platinum Sulfuric Solution",
  "fluid.modern_industrialization.raw_synthetic_oil": "Raw Synthetic Oil",
  "fluid.modern_industrialization.shale_oil": "Shale Oil",
  "fluid.modern_industrialization.sodium_hydroxide": "Sodium Hydroxide",
  "fluid.modern_industrialization.soldering_alloy": "Soldering Alloy",
  "fluid.modern_industrialization.steam": "Steam",
  "fluid.modern_industrialization.steam_cracked_heavy_fuel": "Steam-Cracked Heavy Fuel",
  "fluid.modern_industrialization.steam_cracked_light_fuel": "Steam-Cracked Light Fuel",
  "fluid.modern_industrialization.steam_cracked_naphtha": "Steam-Cracked Naphtha",
  "fluid.modern_industrialization.styrene": "Styrene",
  "fluid.modern_industrialization.styrene_butadiene": "Styrene-Butadiene",
  "fluid.modern_industrialization.styrene_butadiene_rubber": "Styrene-Butadiene Rubber",
  "fluid.modern_industrialization.sulfuric_acid": "Sulfuric Acid",
  "fluid.modern_industrialization.sulfuric_crude_oil": "Sulfuric Crude Oil",
  "fluid.modern_industrialization.sulfuric_heavy_fuel": "Sulfuric Heavy Fuel",
  "fluid.modern_industrialization.sulfuric_light_fuel": "Sulfuric Light Fuel",
  "fluid.modern_industrialization.sulfuric_naphtha": "Sulfuric Naphtha",
  "fluid.modern_industrialization.synthetic_oil": "Synthetic Oil",
  "fluid.modern_industrialization.synthetic_rubber": "Synthetic Rubber",
  "fluid.modern_industrialization.toluene": "Toluene",
  "fluid.modern_industrialization.tritium": "Tritium",
  "fluid.modern_industrialization.uu_matter": "UU Matter",
  "fluid.modern_industrialization.vinyl_chloride": "Vinyl Chloride"
}`

This should be the missing language parts.

**Comment by Technici4n** [comment]
Porting lib issue, they are breaking MI fluid names.
