### ISSUE TITLE
Add EU utility blocks

### ISSUE THREAD

**Issue by JustinHuPrime** [AztechMC/Modern-Industrialization#379]
It would be great if we could get some blocks to help with testing out creative setups and otherwise getting a better handle on the energy balance of our setups

- [ ] EU meter: Block takes EU input at some fixed voltage and outputs at same voltage (like a one-way cable), and displays throughput in its GUI
- [ ] Creative EU Sink: Inverse of the creative storage unit, a creative-only block that consumes an infinite amount of EU

**Comment by JustinHuPrime** [comment]
Following up, it would also be great if we could get some blocks or tools to measure item pipe and fluid pipe throughput

**Comment by Azercoco** [comment]
For the EU sink, you can always use a Superconductor Storage Unit.

**Comment by Technici4n** [comment]
The following pipe tooltips will be in the next release. This fixes the issue. :wink:

![image](https://user-images.githubusercontent.com/13494793/192162893-c16317c2-0d63-46e2-bea3-2251eb1a398d.png)
![image](https://user-images.githubusercontent.com/13494793/192162896-8c0e4242-9e7c-4cf5-956c-619ccae56c88.png)
![image](https://user-images.githubusercontent.com/13494793/192162913-75887805-4b50-4a56-be50-122d7c01b9a2.png)
