### ISSUE TITLE
Crash after ctrl+right clicking a tank with some liquid inside

### ISSUE THREAD

**Issue by ifritdiezel** [AztechMC/Modern-Industrialization#386]
The game crashes every time the world is opened. Minecraft 1.19.2, MI 1.3.2, no other (non-dependency) mods enabled

Crash log: [log.txt](https://github.com/AztechMC/Modern-Industrialization/files/9704293/log.txt)

**Comment by Technici4n** [comment]
Actually I fixed this "by mistake" already. Will be fine in the next release. :smile:
