### ISSUE TITLE
Probabilistic Outputs Are Not Automatable

### ISSUE THREAD

**Issue by t-mart** [AztechMC/Modern-Industrialization#387]
Hi there! Firstly, thank you for your development efforts on this mod. I'm really enjoying it.

How should recipes with probabilistic outputs be automated?

There are many recipes that only output items probabilistically, instead of certainly. For example, in a Coke Oven, an input of 1 Coal Dust yields:

- 1 Coke Dust (certain)
- 500 mB Creosote at a 50% probability

![creosote](https://user-images.githubusercontent.com/200012/194602539-f4465d9c-c43a-44dd-8cf5-87e580bbc54c.gif)

I appreciate this design choice because it reflects how real-life extraction operations (mining, distillation, etc) are probabilistic as well.

However, this design has also been difficult to automate around. **There's no amount of items I can input to a machine that will guarantee the probabilistic output.**

While setting up piping for other recipes has been straightforward, these recipes require complex setups. For example, to reliably produce Creosote, the best I have been able to do is insert Coal Dust via an AE2 Export Bus that's triggered by an AE2 Level Emitter tied to a certain amount of Creosote. In other words, when the network is "low" on Creosote, the export bus kicks on and stuffs the oven input full of coal until the amount of Creosote in the network is no longer "low" on Creosote. This system is wasteful (because it stuffs the oven buffer full of input items), uncooperative (this input port cannot be used by any other recipe), and not on-demand (I can only declare an arbitrary amount to stock, not the amount that might be needed for a specific purpose).

And, this problem doesn't just exist for Creosote. Any recipe with probabilistic outputs would require this kind of setup.

So, could you help me in answering the following:

- How should recipes with probabilistic outputs be automated? Is my implementation improvable (hopefully without the need for other mods)?
- Would you consider replacing probabilistic outputs with lower amounts of certain ones? Say, instead, the above recipe would produce 200 mB of Creosote every time.

**Comment by ifritdiezel** [comment]
MI hinges on passive automation, you're expected to have the coke ovens running full time until there's simply no storage space left for more. It might sound wasteful but you have to keep in mind that you're also expected to have quarries running all the time which constantly supply new resources. Sometime in endgame you might actually have to trash some items that are generated in excess

**Comment by Technici4n** [comment]
Hi, @ifritdiezel is correct. MI is actually fully automatable without any other mod. :wink:
