### ISSUE TITLE
Swapping REI dependency to EMI

### ISSUE THREAD

**Issue by HexBugOrion** [AztechMC/Modern-Industrialization#394]
I've seen several people, some of them close friends, swap to EMI, all of them saying Shedaniel is a massive twerp, harming others online and other nasty things. Plus, EMI isn't rewritten every minor update.

**Comment by Technici4n** [comment]
What the fuck are you talking about...

1. I know shedaniel and he's fine, please reconsider your sources.
2. The last big REI rewrite happened way before EMI was released.

**Comment by rdrpenguin04** [comment]
The only comment I have is that shedaniel does come off as hostile online. But then again, so does a very large part of the modding community.

If anything, EMI should be supported alongside REI, not replacing it; the two each have their advantages.

**Comment by Technici4n** [comment]
My conditions are actually pretty simple: I will only support EMI when it does not require me to write the same code a third time.
