### ISSUE TITLE
Fluids are often not localized! 

### ISSUE THREAD

**Issue by MSandro** [AztechMC/Modern-Industrialization#395]
![image](https://user-images.githubusercontent.com/10937159/197462274-ee34f899-318d-49a0-a1f8-ab6c6831c3b0.png)
![image](https://user-images.githubusercontent.com/10937159/197462295-1bf8884c-460c-4b2c-8e20-e13034f94809.png)

**Comment by Technici4n** [comment]
Duplicate of #378.
