### ISSUE TITLE
Add compatibility for liquids with TR. Sorry if the problem is not yours but theirs.

### ISSUE THREAD

**Issue by Anzarot121** [AztechMC/Modern-Industrialization#396]
As the name says, I would really like to get at least a few fluids compatible, because it gets a bit annoying to build two large systems to get essentially the same thing.

**Comment by Technici4n** [comment]
Which fluids? Many of these are too easy to access in TR for our purposes.

**Comment by Anzarot121** [comment]
From the simplest Hydrogen, although it is easily obtained, I would definitely like to use those 100k cells with it that I received from converting bauxite dust to aluminum.

**Comment by Seegras** [comment]
Certain of these fluids are actually chemical elements, and hydrogen is always hydrogen. It's extremely infuriating when they're not. And well defined chemical compounds shouldn't be "incompatible" either. 

Of course, "heavy fuel" can be whatever it likes. But ethanol (C2H6O) cannot.

**Comment by Technici4n** [comment]
For now they will remain incompatible by design. TR already messes up enough of MI's progression as is, no need to make it worse.
