### ISSUE TITLE
Crash related to Steam Furnace | Fabric 1.19.2 | MI v1.4.0

### ISSUE THREAD

**Issue by devBoi76** [AztechMC/Modern-Industrialization#398]
After trying to smelt anything in a steam furnace I got a crash with this error:

https://mclo.gs/AuuY3yG#L703

I managed to recreate the same error on a brand new world in creative: https://mclo.gs/TeeaxnZ#L819

This also happens when you try to launch the world after a crash

List of mods and other debug info are in the crash logs

EDIT: For now I've reverted to MI v1.3.2 where this issue is not present

**Comment by Technici4n** [comment]
Is the issue fixed by running with ftb quests? We might have accidentally added a dependency on it...

**Comment by devBoi76** [comment]
Yes! I installed ftb quests (1902.4.2-build.116) and the game no longer crashes!
