### ISSUE TITLE
Hard Dependency on REI?

### ISSUE THREAD

**Issue by Derpford** [AztechMC/Modern-Industrialization#401]
Why does this mod have a strict dependency on REI? Normally mods don't *require* a recipe manager, they simply use the recipe manager's API. This causes issues when I want to use another recipe manager such as EMI.

**Comment by Thepigcat76** [comment]
Some machines like the distillery require REI recipe selection to work and EMI isnt supported anyways so why use it?

**Comment by Derpford** [comment]
I'm using EMI partly for its recipe tree feature, and partly because another mod I like--Yttr--only supports EMI. Regarding the Distillery interface...is there any reason you couldn't add a GUI element of some kind to select the recipe?

**Comment by Technici4n** [comment]
See also #326.

**Comment by Derpford** [comment]
Will the distillery change be backported? 1.18.2 is more stable for me right now.

**Comment by Technici4n** [comment]
No backports, no. Also, the distillery was not changed. You still need JEI or REI to use it.
