### ISSUE TITLE
Rancher entity limit being cleared

### ISSUE THREAD

**Issue by BMAB2012** [AztechMC/Modern-Industrialization#406]
Hi there.
I have found that my rancher mk1 sometimes gets it's configuration wiped and the entity limit is cleared. Everything else works just fine (input/output, inventory and functionality). I am running the All of Fabric 6 modpack that has MI version 1.4.2-beta. I currently don't have time to do a lot of testing.
Thanks for this amazing mod!

**Comment by Technici4n** [comment]
Hi, this is not Industrial Revolution. :P
