### ISSUE TITLE
with crafting recpies

### ISSUE THREAD

**Issue by TheLonelyBard** [AztechMC/Modern-Industrialization#408]
so im playing AOF5 and its sayong in order to craft the electric circuit i need the chemical rector but i need a EC to make one but need that block to make it so idk if its an issue with the modpack or just a bug

**Comment by TheLonelyBard** [comment]
i need the thing to make the n plates there is no other way?

**Comment by TheLonelyBard** [comment]
![Screenshot 2022-11-28 083455](https://user-images.githubusercontent.com/119273441/204290767-c835fbb6-3f90-45e3-8405-5ab0c0c13304.png)

**Comment by Itplayz** [comment]
you dont need N nor P doped silicon plates you can just use regular silicon plates you just get half of what you would get with them

**Comment by TheLonelyBard** [comment]
ohhhhh thank you it didnt say that i dont think could have just looked over it thank you
