### ISSUE TITLE
Client crash when equipping Quantum Armour 1.19.2

### ISSUE THREAD

**Issue by waddon1** [AztechMC/Modern-Industrialization#411]
When going in to 3rd person or viewed by another play the Quantum armour crashes the game.

https://pastebin.com/GkGpGXfe

**Comment by Technici4n** [comment]
Update fabric API.

**Comment by Technici4n** [comment]
Should be fixed in fabric-rendering-v1 version 1.11. So probably a conflict with another mod... Nothing I can do.

If you're using quilt report to them.
