### ISSUE TITLE
Pipes&Cables render issue

### ISSUE THREAD

**Issue by inklesspen1scripter** [AztechMC/Modern-Industrialization#42]
Hello! I have issue with pipes and cables rendering
![image](https://user-images.githubusercontent.com/22255205/104838318-5570e700-58cb-11eb-9b69-471412c35e04.png)

Minecraft 1.16.4
Mods:
  [✔️] fabric-api-0.29.3+1.16
  [✔️] Modern-Industrialization-0.3.9
  [✔️] sodium-fabric-mc1.16.3-0.1.0

Without Sodium all works fine
Log file:
[latest.log](https://github.com/AztechMC/Modern-Industrialization/files/5825889/latest.log)
I tried to disable all options from "Advanced" but there is no effect

**Comment by ProjectET** [comment]
It is not an issue with Modern Industrialization. Sodium does not support fabric rendering api.

**Comment by Technici4n** [comment]
This is indeed a Sodium issue. Fabric rendering api support on Sodium's end is planned eventually, but for now mods with complicated rendering like AE2 and MI can't be used with Sodium.
