### ISSUE TITLE
Item config pipe not working until chunk reload

### ISSUE THREAD

**Issue by Despacito696969** [AztechMC/Modern-Industrialization#422]
Connect two infinite barrels with different items as input into the same pipe and then place a pipe outputting into the chest with one of the inputs. Use item config pipe to change that pipe to output the other input, it will still output the first input, even though the GUI says it should otherwise. This bug stays until you reload the chunk or save and quit.

**Comment by Technici4n** [comment]
I'm planning to release the fix tonight, thanks a lot for the clear reproduction steps!
