### ISSUE TITLE
Boiler temperatures are ridiculously high

### ISSUE THREAD

**Issue by Seegras** [AztechMC/Modern-Industrialization#428]
It's probably just a GUI thing, so easy to fix, but the temperatures on the boilers are way to high. 1499° C is above the melting(!) point of steel. Yes, the steel boiler should turn into lava. 

Normal low-efficiency boilers start generating at 100° C, and maybe reach 150° C, perhaps up to 220° C. After that it's high-pressure boilers. 

And highest pressure tube boilers only reach 500-600° C (like those that were used on steam-powered ships), so that's what perhaps the "advanced high pressure boiler" might reach. Nuclear reactors shouldn't go higher than this either. Also, something like 538° C is the maximum allowed for super-heating tubing, as it starts to deform. 

Perhaps something like this:
bronze boiler: 150° C
steel boiler: 175° C
large boiler: 200° C
advanced large boiler: 225° C
high pressure large boiler: 400° C
high pressure advanced large boiler: 500° C

**Comment by Technici4n** [comment]
Sorry but these numbers are actually related to other internal quantities and there is a high probability of messing things up if they are changed naively. I'd rather add more features than change a few numbers because of realism. Realism is not the primary concern in MI.
