### ISSUE TITLE
MV to LV Transformer should have 1 input to 5 outputs

### ISSUE THREAD

**Issue by Joeboon2** [AztechMC/Modern-Industrialization#432]
Current behavior is 5 inputs to 1 output. This makes no sense for a transformer from MV to LV. You'd need 5 LV outputs to properly output all the energy input from 1 MV cable. Currently this makes transporting power across your factory much harder.

LV to MV  transformer is correct with 5 in : 1 out, but MV to LV should be reversed.

This could also be solved by allowing the LV to MV transformer to accept energy input on its 'Y' side rather than a strict output

This is on version 1.2.2 for 1.18. Looking at the changelog, this has not been changed in any recent release or beta versions either.

**Comment by Technici4n** [comment]
Turns out this was fixed in 1.19 already. We can't fix it in 1.18 as it's a breaking change.
