### ISSUE TITLE
lapis and bronze macerator makes blue dye instead of lapis dust

### ISSUE THREAD

**Issue by AsheX1** [AztechMC/Modern-Industrialization#434]
you cant make lapis dust with a macerator as you just get blue dye instead of lapis dust

we can how ever silk touch mine lapis ore and crush that to get crushed lapis dust and turn that in lapis dust

i dont know why its using the normal recipe from the craftingtable and not its own for the macerator

this is on 1.19.2
and Modern-Industrialization-1.6.2-beta

**Comment by NeveHanter** [comment]
You can, just drag the dust from the JEI to the macerator output slot (lock the slot), it works the same when you want to cut cobble to different things in the cutting machine.
