### ISSUE TITLE
Config to disable the quarry generating ores?

### ISSUE THREAD

**Issue by kitsushadow** [AztechMC/Modern-Industrialization#436]
Is it possible to make the quarry not generate ores?

**Comment by ramidzkh** [comment]
Make a datapack to take the place of `data/modern_industrialization/recipes/quarry/bronze.json`, `data/modern_industrialization/recipes/quarry/steel.json`, etc (check [here](https://github.com/AztechMC/Modern-Industrialization/tree/master/src/main/resources/data/modern_industrialization/recipes/quarry)) or use kubejs to remove recipes
