### ISSUE TITLE
Plasma Turbine Energy Output

### ISSUE THREAD

**Issue by joshey40** [AztechMC/Modern-Industrialization#437]
I wanted to build a Plasma Turbine but none of the energy outputs work in the Multiblock. The fluid input of the Helium plasma works fine. Maybe im doing something wrong, but I thought the Plasma Turbine should output energy, so there has to be energy output hatch.

**Comment by JustinHuPrime** [comment]
Did you try using a superconductor energy output hatch? I'm not sure if lower-tier hatches work

**Comment by joshey40** [comment]
> Did you try using a superconductor energy output hatch? I'm not sure if lower-tier hatches work

Yes, i tried all off them.
