### ISSUE TITLE
Crash with newest kubejs

### ISSUE THREAD

**Issue by Nidre** [AztechMC/Modern-Industrialization#44]
I use newest kubejs-1605.3.4.153-fabric. And server don`t start because Modern Industrialization use the old version of kubejs.
[crash.txt](https://github.com/AztechMC/Modern-Industrialization/files/5882214/crash.txt)

**Comment by Technici4n** [comment]
Try updating to MI version 0.3.10. That should work, otherwise please reopen.

**Comment by Nidre** [comment]
Yes, i got this crash on Modern-Industrialization-0.3.10.
