### ISSUE TITLE
Add tool/option to hide barrel item display

### ISSUE THREAD

**Issue by Mg138** [AztechMC/Modern-Industrialization#443]
The item displaying of barrels is quite laggy apparently. According to spark, it can take up to 20% of the rendering time, and FPS drops to 50 for us whenever we face to an area with a bunch of barrels.

Optional: tool to *mass* hide barrels

**Comment by Technici4n** [comment]
I can add such an option, but could you also provide the spark profile so I can check if the performance issue can be solved directly?

**Comment by Mg138** [comment]
Will do.

**Comment by Mg138** [comment]
https://spark.lucko.me/BN4jU8rJvJ

**Comment by Mg138** [comment]
There's some stuff that are from Sodium instead. We wonder if there could be an issue there?

**Comment by Technici4n** [comment]
What happens if you remove glyphix? It seems to make text rendering very slow.

**Comment by Technici4n** [comment]
As a workaround, make sure to surround the faces of the barrels that you don't use with solid blocks. This will cause the barrel to skip rendering for that side entirely. (E.g. if you only use the front face you should surround the 3 other faces with some opaque block).
