### ISSUE TITLE
All machines stopped accepting energy

### ISSUE THREAD

**Issue by TheBlackEntity** [AztechMC/Modern-Industrialization#448]
**Describe the bug**
I was powering an Electrolyser and a Polariser at the same time.

I noticed they stopped at some point.

The Steam Turbine was completely filled with electricity, but the machines didn't use it.

I also made some other electric stuff and all of them stopped accepting electricity.

I replaced all of them multiple times without success.

I also tried the cables from all sides, so there is no way I'm just using the wrong side.

I also tried all cable types I had access to.
Like Tin, Cupronickel and Electrum.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.2
 - Mod Loader: Quilt 0.17.11

**Logs**
Here's a log of today:
https://mclo.gs/IZwJezj

I'm unsure when exactly the issue appeared, so I cannot provide any logs from that day, I'm sorry.

**Comment by Technici4n** [comment]
Can you post a few pictures of your setup?

**Comment by TheBlackEntity** [comment]
Sure!

Here are some screenshots of my test-setup:
![2023-02-27_11 01 09](https://user-images.githubusercontent.com/36412486/221533595-f173cb7a-aa34-4d24-bd1b-ec8b48853cda.png)
![2023-02-27_11 01 15](https://user-images.githubusercontent.com/36412486/221533604-a31a369d-e37a-4d60-8d56-e6c3b17a8309.png)
![2023-02-27_11 01 25](https://user-images.githubusercontent.com/36412486/221533605-a74690e3-9f4c-4fde-9203-6aa5661ba9a6.png)
![2023-02-27_11 01 29](https://user-images.githubusercontent.com/36412486/221533612-8b675228-6b02-4772-b54b-17af9748be53.png)
![2023-02-27_11 01 35](https://user-images.githubusercontent.com/36412486/221533617-c570014d-e0d5-4e15-923a-8a814aab731d.png)

**Comment by Technici4n** [comment]
Which cables are those?

**Comment by TheBlackEntity** [comment]
Those are tin cables, but I also tried, as I already said, others too

**Comment by Technici4n** [comment]
You need HV cables for HV turbines. You need LV cables for machines with an LV hull.

**Comment by Technici4n** [comment]
You'll need 2 transformers to go HV->MV and MV->LV :)
