### ISSUE TITLE
Lock icon is hard to see on steel barrels and tanks

### ISSUE THREAD

**Issue by Abbie5** [AztechMC/Modern-Industrialization#449]
![2023-02-28_21 09 06](https://user-images.githubusercontent.com/43531981/221981041-4694d4b2-e312-4ce6-87cf-1edbf8205f21.png)

It would be nice if the lock was coloured white, like the item name text.

**Comment by Technici4n** [comment]
Implemented in https://github.com/AztechMC/Modern-Industrialization/commit/a78eaa2f532cc55df07f4f2a5040a12b1e4b902e.
