### ISSUE TITLE
Crash with kubejs. (Reopen #44)

### ISSUE THREAD

**Issue by Nidre** [AztechMC/Modern-Industrialization#45]
Reopen #44
Yes, i got this crash on Modern-Industrialization-0.3.10.

**Comment by Nidre** [comment]
On v0.3.11 crash is still present.
[newcrash.txt](https://github.com/AztechMC/Modern-Industrialization/files/5890810/newcrash.txt)

**Comment by Technici4n** [comment]
Can you try with the latest KubeJS?

**Comment by Nidre** [comment]
On kubejs-1605.3.5-build.156-fabric don`t work.
[crash0.txt](https://github.com/AztechMC/Modern-Industrialization/files/5894157/crash0.txt)

**Comment by Technici4n** [comment]
There was an issue with one of the released KubeJS builds. Version 0.3.12 should now work with the latest KubeJS builds, sorry for the delay.
