### ISSUE TITLE
Hammer Forge not working on fabric server.

### ISSUE THREAD

**Issue by yeetrut** [AztechMC/Modern-Industrialization#451]
Im playing on a 1.19.2 server with MI version 1.6.3 and when i put ingots in the slot in the hammer forge it does not display the crafting options in the dedicated spot. This works with the same mods in singleplayer.

**Comment by Technici4n** [comment]
Anything in the server logs?

**Comment by yeetrut** [comment]
The only thing i can see is a warn that something isnt right with FactoryAPI, im not the best at reading logs so ill just attach it, the warn is in line 338. Other then that i can nor figuere out any other problems with MI itself.
[latest.log](https://github.com/AztechMC/Modern-Industrialization/files/10961915/latest.log)

**Comment by Technici4n** [comment]
This is almost surely caused by another mod on your server, but I don't know which one. Maybe a protection mod like FTB Teams?

**Comment by cplir-c** [comment]
You could try binary searching for the conflicting mod (remove half the non-MI mods until it works properly, and repeat with smaller mod selections until you find it).
Maybe a mod that changes packets like Polymer? I see `autocrafter` pulls it in.

**Comment by yeetrut** [comment]
Ill try these tomorrow when I have time and I will tell you the results. Thanks in advance.
