### ISSUE TITLE
Vanilla "Times Crafted" stats aren't incremented as player-placed machines process recipes

### ISSUE THREAD

**Issue by James103** [AztechMC/Modern-Industrialization#455]
Modern Industrialization machines placed by a player store the UUID of the player that placed the machine.
This is already used in #385 to complete quest tasks whenever a player crafts an item required by a quest from FTB Quests.
However, vanilla stats are still not incremented.

To reproduce:
1. Craft and place a bronze, steel or electric furnace.
2. Power it (with steam or EU).
3. Use hoppers or item pipes to insert clay balls into the furnace and take out the resulting bricks.
4. Notice the vanilla stat "Times Crafted" for the brick item isn't automatically incrementing; however, a quest task requiring the brick item would auto-complete.

Originally found in mod pack "All of Fabric 6" version 1.5.0, which uses Modern Industrialization 1.6.3 and Minecraft 1.19.2.

Alternative to #343.

**Comment by Technici4n** [comment]
Problem: vanilla stats can only be awarded while the player is online, so this won't work very well.

**Comment by James103** [comment]
> Problem: vanilla stats can only be awarded while the player is online, so this won't work very well.

This could be worked around by keeping track of all the items a player's machines crafted while that player itself is offline, then awarding points to the relevant stats once the player comes online.
