### ISSUE TITLE
Moving cables with AE2 causes them to connect to invisible blocks

### ISSUE THREAD

**Issue by kusheng03** [AztechMC/Modern-Industrialization#460]
I was moving some stuff in my Base with the Spatial Pylons from AE2, when i placed it down again, the tin cables connected to invisible blocks:
![2023-04-01_11 52 58](https://user-images.githubusercontent.com/64306810/229279171-688b3e9f-0ff4-4d43-a1df-4c7442eb3c0f.png)
Any Idea how to remove these? i cant place any cables on the blocks that are affected.... /setblock does place a block there but when i remove it, the connection stays...
I'm playing All of Fabric 6 Minecraft 1.19.2 -> Modern Industrialization 1.6.3...

**Comment by Technici4n** [comment]
Enable debug commands in the config, then you will have a command like `/mi pipes clear x y z` that you can use to remove the ghost pipes.

Please leave the issue open, I will blacklist these pipes from being moved by AE2.

**Comment by kusheng03** [comment]
Thank you for the quick answer, sadly this only removes the connection, if i try to place a new cable there, it bugs out again. if i try the command again after that, i get an error message. 
[error.txt](https://github.com/AztechMC/Modern-Industrialization/files/11129194/error.txt)

**Comment by Technici4n** [comment]
You need to clear the ghost pipe, so make sure you target the invisible pipe and not the visible one?

**Comment by kusheng03** [comment]
For example there is a ghost pipe above this block, so i think this command should have the correct position? but when i execute it, there is just the error message in the console, nothing happens. it even crashes the server.
![2023-04-01_12 58 35](https://user-images.githubusercontent.com/64306810/229284881-06a1dfd8-f3a9-4f46-80e6-ed025af5d746.png)
[error1.txt](https://github.com/AztechMC/Modern-Industrialization/files/11129252/error1.txt)

**Comment by Technici4n** [comment]
It seems that the state of the pipe network got corrupted... I have no idea how that is even possible, it's the first time it happens in 2.5 years...

**Comment by kusheng03** [comment]
is it possible to reset the pipe network somehow? delete all pipes there are?

**Comment by Technici4n** [comment]
You can turn off MC and then delete the network data file (I think it's in world/data?). You will need to place all the pipes again after that, sorry for the inconvenience...

**Comment by kusheng03** [comment]
To be sure i just loaded a backup from 2 days ago (before i did the spacial transfer). Now everything seems to be okay again. Thank you again for your help. I will leave this issue open ofc.
