### ISSUE TITLE
Add Red Fuming Nitric Acid

### ISSUE THREAD

**Issue by Technici4n** [AztechMC/Modern-Industrialization#470]
Funny name go brrr

**Comment by cplir-c** [comment]
I was wondering what this was
[wikipedia page](https://en.wikipedia.org/wiki/Red_fuming_nitric_acid)
"Red fuming nitric acid (RFNA) is a storable [oxidizer](https://en.wikipedia.org/wiki/Oxidizer) used as a [rocket propellant](https://en.wikipedia.org/wiki/Rocket_propellant)."
