### ISSUE TITLE
Error in the machine creation chain

### ISSUE THREAD

**Issue by VadimPPvorona** [AztechMC/Modern-Industrialization#478]
To create Electric machines, plates processed only on a Chemical centrifuge are required. However, in order to create a Centrifuge, these same boards are needed, created exclusively on it. As a result, it turns out that it is not possible to develop cars further. Or I didn't see something (but checked, trying to solve this problem).

**Comment by Technici4n** [comment]
You don't need to use P or N doped plates at the beginning, use the normal silicon plates.

**Comment by VadimPPvorona** [comment]
I am at the stage of electricity, and for further development it is very important to improve the quarry to electric. This is where everything breaks down. And it is the alloyed ones that are required.

**Comment by VadimPPvorona** [comment]
They are required by semiconductors

**Comment by Technici4n** [comment]
It is definitely possible to finish MI, lots of people have.

You don't need superconductors for the electric quarry, superconductors come much later.

**Comment by VadimPPvorona** [comment]
I'll look again later, maybe I missed something after all. There is no way to send screensavers now.

**Comment by VadimPPvorona** [comment]
I found a way through silicon wafers. I'm sorry, it happens when you look, but you don't see... And thank you so much for responding.
