### ISSUE TITLE
Сopper in Minecraft 1.16.5

### ISSUE THREAD

**Issue by heX16** [AztechMC/Modern-Industrialization#48]
I installed your mod on a pure Minecraft 1.16.5. Where do I get copper? - It will be added to Minecraft 1.17.

**Comment by Technici4n** [comment]
It should generate in the overworld, maybe have a look around in spectator mode?

**Comment by Technici4n** [comment]
Yes it does generate copper. You can see what ores are generated by looking at the config in `config/modern_industrialization.toml`.

**Comment by heX16** [comment]
My mistake. I added the mod after generating the world, it was necessary to go very far from the starting location to find copper.
