### ISSUE TITLE
pipe item models bake all possible shape variants

### ISSUE THREAD

**Issue by unix-supremacist** [AztechMC/Modern-Industrialization#480]
this causes lag when mods request for the models to be rebaked mid game, especially when using modernfix dynamic resources and going to the MI page in rei where it bakes all pipe models at the same time

relevant discord message: https://discord.com/channels/754461970870173767/754461971499450512/1104045368733343754

**Comment by embeddedt** [comment]
Worth noting that even without my dynamic resources, I noticed MI's pipe models taking a substantial amount of time to bake by themselves. Might be worth looking into whether the shape generation logic can be made to run faster.

This is a profiler excerpt from AOF6 startup.

![image](https://user-images.githubusercontent.com/42941056/236697601-e13a799c-e343-4860-8899-b16fd7f0a827.png)
