### ISSUE TITLE
Config option for instant overclocking

### ISSUE THREAD

**Issue by jeytee84** [AztechMC/Modern-Industrialization#486]
While i get the idea around the mod being different in many ways including the semi-separated energy generation and the incremental overclocking system promoting the building of huge continious factories, it would be nice to get a config option for the oc system just as for the energy system to set it back to "normal". Huge, factorio style building is a great thing, but for those of us who like to automate as many things as possible through AE2 in a neat compact factory having less machine duplicates, it would be great if there was an option to set the overclocking to instant instead of the spinning up system (even if it would come at a general slower speed of all machines for balancing reasons). Also it would make it possible for pack builders to finetune how the mod integrates into the pack.

**Comment by Technici4n** [comment]
Thanks for the suggestion, but this is a key mechanic of the mod and I don't want to add a config option that bypasses it. Automatic lubricant application is something that is planned however, but likely will take a while to happen.

**Comment by jeytee84** [comment]
The lubrication would speed up the spinup process or somtehing?

Another idea that just came up, is if hull upgrades could modify the "baseclock". So that a machine running on 16EU/t by default, would start at 32EU/t with an advanced hull, 256EU/t with a turbo hull etc. I think that would fit in really nicely with the regular progression as well as fix the alternative "compact factory" progression, since it would't make it such a problem if a machine that was overclocked super high accidentally spins down. Not to mention it would make hull upgrades and different levels of energy input hatches on multiblock machines worth using even in "BidirectionalEnergyCompat" mode. 

> Btw in my playthrough in AOF2 getting to Turbo upgrades territory, this whole thing comes up as a real problem. Until now, everything was great and playable with the "compact factory" process, with slight optimisations and the occasional nudging with a Temporal Pouch, which is totally fine and great. But right now im getting to the point where there are so many recipes that machines have pretty much no way to spin up, no matter how I try to optimize. No matter what i do and how many upgrades I use everything gets really slow, and the only bottleneck to keep going with progression is this mechanic. While I totally get that it is the intended way for the mod to work, but it makes the player try to use machines other than MIs' that are upgradable "normally" and the whole mod starts to feel out of place in the pack. Standalone it would be totally fine, but considering modpacks, I think it would be a good design decision to offer that kind of customizability.

**Comment by Technici4n** [comment]
Lubrication is already a feature and it increases overclock directly at the expense of some lubricant, but it can only be applied manually at the moment.

MI is designed to have different gameplay from most other tech mods. `bidirectionalEnergyCompat` is already a compromise that was designed for modpacks that correctly rebalance energy production from other mods and remove their cables to make everything fit around MI. Feel free to use it for other purposes, but I don't want it to be used as an excuse to remove more things that make this mod unique.

I think the usual "connect everything to AE2 pattern providers" pattern that is so prevalent in modded MC is quite boring, and I do not encourage it with MI. I would suggest that you try the way MI is meant to be played.

**Comment by Technici4n** [comment]
Lubrication is already a feature and it increases overclock directly at the expense of some lubricant, but it can only be applied manually at the moment.

MI is designed to have different gameplay from most other tech mods. `bidirectionalEnergyCompat` is already a compromise that was designed for modpacks that correctly rebalance energy production from other mods and remove their cables to make everything fit around MI. Feel free to use it for other purposes, but I don't want it to be used as an excuse to remove more things that make this mod unique.

I think the usual "connect everything to AE2 pattern providers" pattern that is so prevalent in modded MC is quite boring, and I do not encourage it with MI. I would suggest that you try the way MI is meant to be played.

**Comment by MikeDev0ps** [comment]
Having faced a similar problem, I think I have a few ideas on how to solve it. It would make sense to add an "overclocking controller" that allows the device to be left in standby mode. The user will be able to leave the device, which does not perform any actions, turned on, but it will consume energy in standby mode. When using this module, the device resets acceleration only when disconnected from the power supply and regains acceleration when power is restored. These mechanisms will operate similarly to real production lines.

**Comment by Technici4n** [comment]
Related: https://github.com/AztechMC/Modern-Industrialization/pull/870
