### ISSUE TITLE
Machine hull upgrade upgrade

### ISSUE THREAD

**Issue by jeytee84** [AztechMC/Modern-Industrialization#487]
A spinoff of #486 but with a whole different point centered around machine hull upgrades.
(sorry for spaming the issue tracker, got into a bit of a brainstorm)

Right now machine hull upgrades in **singleblock machines** only change the input voltage.
In multiblocks a higher hull fluid and item input has **double the storage**.
This could be the case for single block machine hull upgrades, for fluids especially but
for items as well. Some machines benefitting greatly from **more input slots**.
(A macerator hooked up to a quarry could work on one resource without interruption longer for example).
As I already mentioned in #486 hull upgrades could also **double the baseclock** of the machine.
It would make sense for an advanced machine to spin up **faster than a low-tier one**.
(Not to mention that as a byproduct it would fix #486 and also add better compatibility, as mentioned there)

**Comment by Technici4n** [comment]
#486 is not happening in any way.

You can use configurable chests and configurable tanks as buffers if you need more capacity in some machines.
