### ISSUE TITLE
Steam can be placed by Create pipes

### ISSUE THREAD

**Issue by TropheusJ** [AztechMC/Modern-Industrialization#493]
When Create tries to spill fluid into the world through an open pipe end, it gets the BlockState of the fluid, and places it if it's not air.
MI steam, and probably a few other fluids, use an MIFluidBlock for some name behavior. Since it's not air, you get this:
![image](https://github.com/AztechMC/Modern-Industrialization/assets/60247969/ba93ee72-1cf4-455a-bcf8-ec85693103a1)

I think the easiest way to fix this would be to mark instances of MIFluidBlock as air in their properties. A tag could also work if that's preferred.
Create issue: https://github.com/Fabricators-of-Create/Create/issues/837

**Comment by Technici4n** [comment]
It shouldn't be placed at all since it's not a FlowableFluid (that was the name?). Buckets can't place it, so there must be a check that Create is forgetting.

**Comment by Technici4n** [comment]
@TropheusJ you should check for `instanceof FlowingFluid`, see `BucketItem#emptyContents`.
