### ISSUE TITLE
Steam Quarry - I can't connect the steam pipe

### ISSUE THREAD

**Issue by heX16** [AztechMC/Modern-Industrialization#50]
![image](https://user-images.githubusercontent.com/3930496/109053191-7fe56980-76ed-11eb-9aa9-96a94ea62e6c.png)

**Comment by Technici4n** [comment]
You will need hatches for this to work - check the coke oven guidebook entry in the guide book.

**Comment by heX16** [comment]
![image](https://user-images.githubusercontent.com/3930496/109057074-58dd6680-76f2-11eb-8bf1-c986bfcd3db8.png)

It doesn't work...

**Comment by Technici4n** [comment]
Come on the discord for this kind of practical questions.

**Comment by heX16** [comment]
> 
> 
> Come on the discord for this kind of practical questions.

Thank you, but I've already deleted the mod. I'm looking for a convenient and concise mod, without pointless complexity. This mod is definitely not suitable (as well as many others).

**Comment by YuRaNnNzZZ** [comment]
> without pointless complexity

5хед, ставить блоки которые часть мультиблока ВНЕ ЭТОГО САМОГО МУЛЬТИБЛОКА.

а виноват конечно же сам мод

**Comment by heX16** [comment]
> 5хед, ставить блоки которые часть мультиблока ВНЕ ЭТОГО САМОГО МУЛЬТИБЛОКА.
Мультиблок собран в точности по "инструкции" которую предоставляет "гаечный ключ" и "книжка".

P.S. Мне будет проще вас понять, если будете оформлять свои мысли более общепринятым способом.
