### ISSUE TITLE
Dev builds are failing for all commits since 1.6.7 release

### ISSUE THREAD

**Issue by James103** [AztechMC/Modern-Industrialization#500]
All dev builds, triggered via GitHub Actions on push, for commit 6ae2b0975f90567cdc26b0e15f437949896061de and later (after 1.6.7 release), are failing fairly early on.

The failure message is that a plugin named `com.diffplug.spotless` version `5.14.0` was not found. Most likely, that is because the specific version used to exist but has since been taken down.

The `build.gradle` file was not modified since before the last commit with a successful dev build, with the plugin not having been updated for approximately two years: https://github.com/AztechMC/Modern-Industrialization/blob/e7893564321d75a58c7c2f9eefb8bf0e5b82344f/build.gradle#L4

**Comment by Azercoco** [comment]
Least obsessed MI fan 

(Actually being currently fixed)

**Comment by Technici4n** [comment]
Should be fixed by 67d50a31.
