### ISSUE TITLE
Typo in reactor info "Max Temperature" line

### ISSUE THREAD

**Issue by James103** [AztechMC/Modern-Industrialization#501]
https://github.com/AztechMC/Modern-Industrialization/blob/50fb65bfc88b2c771118860c7feda419d2e3d637/src/main/java/aztech/modern_industrialization/MIText.java#L151
The line that says "Max Temperature: X **C°**" should instead say "Max Temperature: X **°C**", just like all other uses of the 'degrees Celsius' symbol.

**Comment by Azercoco** [comment]
Fixed by 54cd0f79b2907f1137af2f4428304954f14dc013
