### ISSUE TITLE
[Question] Update to MC 1.x.x

### ISSUE THREAD

**Issue by AlexChevios** [AztechMC/Modern-Industrialization#504]
MI will be updated to newer versions of Minecraft, for example 1.19.4 or 1.20.X, or is it only for 1.19.2 so far?

**Comment by Azercoco** [comment]
MI will probably skip 1.19.4 and update to 1.20 as soon as all the depedencies are available.

**Comment by Technici4n** [comment]
We will update MI to 1.20 at some point[^1]. 1.19.4 will be skipped.

[^1]: Only once enough crucial mods have been ported. We are thinking of waiting for both Create and KubeJS to be updated, depending on how long that takes.
