### ISSUE TITLE
Electrolyzer not working

### ISSUE THREAD

**Issue by Plague-Breaker** [AztechMC/Modern-Industrialization#508]
I have it supplied with power, it will not process bauxite or lapis, however it would process water.

I am not sure if this is me not understanding how it works or if it's a bug

Mod version is Modern Industrialization 1.6.8 for fabric 1.19.2

It processed one set of lapis dust after I put it down and then just stopped

![image](https://github.com/AztechMC/Modern-Industrialization/assets/135455394/fd697980-ea70-4051-8841-8868d15242bc)

**Comment by James103** [comment]
By default, you need 10 bauxite, 18 lapis or 23 emerald dust in an Electrolyzer's input slot in order for it to process any; you can check the exact numbers for your modpack/server in REI/EMI.

**Comment by Plague-Breaker** [comment]
Oh, I didn't know that, my server's REI is broken. Thank you.
