### ISSUE TITLE
Trying to Triple my Ore 

### ISSUE THREAD

**Issue by phatpenguin123** [AztechMC/Modern-Industrialization#52]
I can not seem to figure out how to connect the industrial smelter to the condenser so I can get automatic tripling of my ores. My fluid pipes are not working, is it because they are not of a higher tier pipe, do I need bronze or something type fluid pipes?

**Comment by Technici4n** [comment]
Make sure
1) you have configured IR machines with the IR wrench to accept fluid pipe connections and
2) the pipes have an arrow pointing out of the industrial smelter and into the condenser.

If that doesn't work, please join our discord for this kind of practical questions for more interactive help. :)
