### ISSUE TITLE
Mixed Iridium Ingot... as food? Why is this food?

### ISSUE THREAD

**Issue by MommaDragon** [AztechMC/Modern-Industrialization#530]
More of an inquiry than an issue, but.

![image](https://github.com/AztechMC/Modern-Industrialization/assets/106483611/dcce678b-1ce8-4b1f-9b0d-9457bc9dc86a)

This normally isn't food. Why did someone tag it as food and say it was 20/20? (Yes, this is in your code; this isn't a modpack thing. Just checked your code.)

**Comment by Technici4n** [comment]
Oreo !
