### ISSUE TITLE
kjs 6.1 recipe parser ignores count and chance for output items

### ISSUE THREAD

**Issue by Abalieno** [AztechMC/Modern-Industrialization#532]
event.custom works normally, this is only about MI kjs internal plugin.

Happens on both REI and EMI, I haven't tested if running recipes are working for some reason. Kjs build doesn't seem relevant.

![rukykik](https://github.com/AztechMC/Modern-Industrialization/assets/4656436/4ded2f20-86a9-41dd-ac83-2b37968fe9e7)

![yukyikuik](https://github.com/AztechMC/Modern-Industrialization/assets/4656436/217de150-099c-433c-813f-9e199d29d7da)

Can't see chances in the image, but the 5x for copper is ignored and none of the tooltips show chances. This for outputs only because the inputs show "9%" and "not consumed" as they should.

**Comment by Linguardium** [comment]
likely caused by KubeJS using "chance" property and MI using "probability" property. MI implements its own input item that uses the "probability" property so that is likely why it is working.  Fluid outputs should work fine since that is also a custom parser

**Comment by Abalieno** [comment]
Cannot pass "chance" to MI internal parser. Can't mix syntax on a whim.

**Comment by Technici4n** [comment]
Thanks @Linguardium for figuring out the issue.
