### ISSUE TITLE
Ticking block entity crash with Nuclear Reactors

### ISSUE THREAD

**Issue by TheStaticVoid** [AztechMC/Modern-Industrialization#533]
[crash-2023-07-25_11.23.53-server.txt](https://github.com/AztechMC/Modern-Industrialization/files/12164749/crash-2023-07-25_11.23.53-server.txt)

**Comment by Fauli1221** [comment]
I had that issue as well in addition to that reactors seem to be broken entirely right now

I used a workaround to keep my server operating by installing [Neruina - Ticking Entity Fixer](https://modrinth.com/mod/neruina)
