### ISSUE TITLE
Solar Panels

### ISSUE THREAD

**Issue by xXmilchzombieXx** [AztechMC/Modern-Industrialization#536]
Hi, I only wanted to share a short idea about your mod because it got me the old Minecraft 1.7 feeling. 

My idea was that you could implement the old mod named „advanced solar panels“ (https://www.curseforge.com/minecraft/mc-mods/advanced-solar-panels).

It used extreme amounts of energy so it would be nice to use the fusion reactor for that later and maybe to use your fusion reactor to create not only fluids but also like iridium. That will be then used for building those solar panels. Those solar panels (at least the quantum solar panel) should be very expensive so that you have nice goal to reach it.
 Maybe you could also make a armor that uses this solar panel as power source so you almost not run out of energy.

![27D5E07E-9622-45E8-ABCC-346AC4E8341C](https://github.com/AztechMC/Modern-Industrialization/assets/72553828/d3b83ede-f942-49d5-bfa3-3209f9ce81aa)

**Comment by Technici4n** [comment]
See #346.
