### ISSUE TITLE
Move aztech.modern_industrialization.compat.waila.holder package to api level

### ISSUE THREAD

**Issue by SirEdvin** [AztechMC/Modern-Industrialization#541]
So, I am a developer of integration mod between MI and CC:T, and I faced [issue](https://github.com/SirEdvin/UnlimitedPeripheralWorks/issues/25) with my integration when this package was moved from "megane" to "waila". 

Unfortunately, holders are very suitable for information reading integrations and I really need to use this interfaces rather than check all their implementations. Can I suggest for 1.20 version move this holder to separate package inside `api` for example?

**Comment by Technici4n** [comment]
Which holders are you actually using, and which properties of the components are you reading? This is important so I know what to expose in the API. :wink:

**Comment by Technici4n** [comment]
See #550.

**Comment by SirEdvin** [comment]
Thanks, it is perfect!
