### ISSUE TITLE
Configurable capacity / add tiers to Portable Storage Unit

### ISSUE THREAD

**Issue by James103** [AztechMC/Modern-Industrialization#545]
Could there be an option to reduce the number of batteries the Portable Storage Unit can hold, or will the unit's capacity be forever locked at 10,000 (and no less) as it was originally designed?

Alternatively, could there be different tiers to the Portable Storage Unit, with higher tiers able to hold more batteries, starting at or just over the vanilla stack size and increasing to a few thousand for the highest tiers?

10,000 batteries in a single Portable Storage unit, especially one that can be crafted mid-LV, can be a bit much for some players, who may like the capacity reduced to a saner value such as 64 times a small power of 2.

**Comment by Technici4n** [comment]
If players don't want to fill it that's fine. Plain tiered batteries are boring...
