### ISSUE TITLE
1.20.1 Fabric crash on startup (Modern Industrialization v1.7.0-beta)

### ISSUE THREAD

**Issue by BrokenHearted2** [AztechMC/Modern-Industrialization#551]
[crash-2023-08-21_04.55.03-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/12395665/crash-2023-08-21_04.55.03-client.txt)

**Comment by Technici4n** [comment]
Mystical agriculture includes a broken version of Magna, please report the issue to them.
