### ISSUE TITLE
Crash when attaching pump to fluid pipe

### ISSUE THREAD

**Issue by Su5eD** [AztechMC/Modern-Industrialization#552]
Attaching a fluid pump to a fluid pipe results in a crash.

### Environment
- Minecraft 1.20.1
- Fabric Loader 0.14.22
- Fabric API 0.87.0+1.20.1
- Modern Industrialization 1.7.0-beta

### Steps to reproduce
1. Place a fluid tank
2. Connect a fluid pipe to the tank
3. Use a fluid pump on the connected pipe block

<img src="https://github.com/AztechMC/Modern-Industrialization/assets/51261569/baad252f-3037-4b9d-a72f-e8733b190eac" width="50%" />

### Logs
[Crash report](https://mclo.gs/jA7H6QD)

### Suspect

Passing a null component into the button class.

https://github.com/AztechMC/Modern-Industrialization/blob/e62cf211f7cfd50e93b92be9747c99c4b7380d2a/src/client/java/aztech/modern_industrialization/pipes/fluid/FluidPipeScreen.java#L113-L114

**Comment by 0x6273** [comment]
I get a similar crash when trying to open the UI on fluid and item pipes. https://mclo.gs/ZzO20tB

**Comment by Technici4n** [comment]
Fixed in 354b6d5.
