### ISSUE TITLE
Request: expanding distillation towers

### ISSUE THREAD

**Issue by Abalieno** [AztechMC/Modern-Industrialization#553]
As discussed on discord.

Right now while it's possible to add fluid output slots, they won't work due to the fact the multiblock behavior is hardcoded. Adding more slots would also require adding another layer to the structure.

Same for adding an item output.

I'd need to do the same on a distillery, but I guess in that case I can create a new machine for the purpose. Single block machines can't mess with slots, but also don't have custom behaviors like the distillation tower.

**Comment by Technici4n** [comment]
> I was also wondering if there's some reason behind setting certain machines to have limited fluid/items input/output.

It was added to prevent datapack authors from adding broken recipes. This was a very long time ago, when the KubeJS API didn't exist yet.
