### ISSUE TITLE
Crash when scrolling on MI Items pages in EMI or REI

### ISSUE THREAD

**Issue by jonycase** [AztechMC/Modern-Industrialization#557]
Minecraft 1.20.1 
MI Version 1.7.3
[crash-2023-08-26_00.20.06-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/12442931/crash-2023-08-26_00.20.06-client.txt)

**Comment by jonycase** [comment]
in creative tab too

**Comment by jonycase** [comment]
[crash-2023-08-26_00.27.56-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/12442958/crash-2023-08-26_00.27.56-client.txt)

**Comment by Technici4n** [comment]
Hi, does it also happen without Continuity? Can you also post the full log?

**Comment by jonycase** [comment]
> Hi, does it also happen without Continuity? Can you also post the full log?

yes, is not full?
ok where is full log

**Comment by Technici4n** [comment]
You can find it as `latest.log` right after the crash occurs.

**Comment by Technici4n** [comment]
This seems to be an issue with ModernFix, actually. Will look into fixing it.

**Comment by Technici4n** [comment]
Updating to ModernFix 5.7.2 or newer should fix your issue. :)
