### ISSUE TITLE
Crashing when trying to search REI

### ISSUE THREAD

**Issue by Twoscore23** [AztechMC/Modern-Industrialization#558]
I went to type "rabbit" and after "rab" it crashed my game. It says when trying to render crafting_table which is weird and doesnt seem attached to your mod but I also launched and did "@modern" and scrolled the pages I crashed on I believe pages 2, and 3. I removed the mod and scrolled every page available in REI and no crash that is how I narrowed it down to being cause by your mod even tho it seems its being crashed by an item outside your mod.

LOG: https://pastebin.com/2VEhpaha

**Comment by Twoscore23** [comment]
Oops looks like I made a duplicate issue my bad. I can move my comment into that issue if you would like

**Comment by Twoscore23** [comment]
@Technici4n I understand this is a thing you do for fun no pressure, but any updates?

**Comment by Technici4n** [comment]
Sorry, was quite busy. Please update MI and ModernFix to their latest version, and let us know if the issue persists.

**Comment by Twoscore23** [comment]
Works with modernfix 5.7.2 doesnt work on modernfix under that version just FYI. Thank you!

**Comment by Technici4n** [comment]
Sweet! :)
