### ISSUE TITLE
AE2 Ender dust

### ISSUE THREAD

**Issue by Imsvale** [AztechMC/Modern-Industrialization#56]
Just wondering if Ender Dust could be added as a macerator recipe. In AE2 you make this in the grindstone from an Ender Pearl.

**Comment by Technici4n** [comment]
Thanks for the suggestion, will be in the 0.4.x releases! Feel free to suggest other such recipes if you think we've missed some! :-) (And sorry for the delay, we've been quite busy lately).

**Comment by Imsvale** [comment]
Thanks for adding it in! :)
