### ISSUE TITLE
Server Wont start up at all

### ISSUE THREAD

**Issue by Bglad97** [AztechMC/Modern-Industrialization#561]
As the title says, the server crashed one day while I was playing and refuses to start back up. Sent a ticket request and was told its a block in modern industrialization. No further information.

**Comment by Technici4n** [comment]
Without a crash log I can't do anything...

**Comment by Bglad97** [comment]
All it says when you try to load it is "Server refused: No further information"

**Comment by Technici4n** [comment]
Then how can you know it's MI... Please find some crash or log information, otherwise I'll have to close this issue a I really can't do anything without that info. :/

**Comment by Bglad97** [comment]
Ahh okay. Sorry I'm not sure how to get that info. You can close the issue, sorry for the bother. We decided to just shut the server down as it has been having issues left and right anyway.
