### ISSUE TITLE
Advanced Large Steam Boiler not producing promised 1024 mb/t

### ISSUE THREAD

**Issue by Aphyxia** [AztechMC/Modern-Industrialization#570]
I have 4 MV turbines connected to a Advanced Large Steam Boiler but they are running out of steam when operating at high capacity (480 EU/t consumption).
The boiler has fuel, is operating at max heat and the steam output is empty, meaning everything is distributed.

Now, 4 x 128 should only take 512 mb of steam to run all the turbines at max power and the boiler promises up to 1024mb/t. Am I understanding something incorrectly or how to achieve this "up to 1024mb/t"?

Playing on MC version 1.19.2 with MI 1.6.12 on the Prominence I modpack.

**Comment by Technici4n** [comment]
Does the boiler have max temperature, and is it always full of water?

**Comment by Aphyxia** [comment]
Good call. I had the water input tucked away and forgotten. Water inflow was lacking. Closing this as user error. :S Thank you.
