### ISSUE TITLE
MI Datagen is not working on 1.20.1

### ISSUE THREAD

**Issue by TheStaticVoid** [AztechMC/Modern-Industrialization#572]
[Link to Discord](https://discord.com/channels/754461970870173767/760125612126896196/1151923752494444595)

**Comment by Technici4n** [comment]
Fixed in https://github.com/AztechMC/Modern-Industrialization/commit/92f207729dffbbc228e9ef279ba5efb9e784fff8#diff-f228c0243c3a524fcb80bb44a59cdc3ead69e44572dea5894b404c6c972d6767L76-R94.
