### ISSUE TITLE
Request: subordinate machine upgrades to hulls

### ISSUE THREAD

**Issue by Abalieno** [AztechMC/Modern-Industrialization#574]
This is one of my highest priority top peeves that I stumbled on because I'm changing many things, but I want to know what possible negative influences it would have on standard MI, because I can't see any.

Right now machine upgrades and hulls are independent, and I've tested it's possible to scale EU requirements of recipes infinitely, especially with machine extenders that lets one connect infinite amount of cables.

That means it's easily possible to run max EU recipes with an LV machine, skipping hull requirements.

To have a more sane and controlled behavior the system would need to just have machine upgrades being a feature given by hulls (and maybe giving customization to it). So that an LV machine has a cap to how much EU it can reach, and this cap will rise by using higher hulls.

Nothing changes in costs or behaviors. Machines still use the same hulls and they still need upgrades to increase EU usage, but with a better incentive to actually upgrade hulls as well.

As a suggestion on how this should work: have maybe a green or red outline around the machine upgrade slot. The slot still accepts any amount and type of upgrade but, if the total upgrades stay lower than the cap set by the hull, then the outline stays green. If you instead have inserted upgrades that push the machine beyond the cap set by the hull, then the outline turns red, and if you hover on it the tooltip would say: "Max reached, use an higher hull to increase the cap" or something like that.

**Comment by Technici4n** [comment]
> That means it's easily possible to run max EU recipes with an LV machine, skipping hull requirements.

That's fine if people really want to waste time bringing 10 different cables to the machine... :P
