### ISSUE TITLE
Problems with ghost pipes

### ISSUE THREAD

**Issue by Wirezat** [AztechMC/Modern-Industrialization#577]
After you /setblock a block where a cable/pipe was, the pipe is not completley removed. i stil exists but doesnt work anymore. it is not possible to lace a new pipe there, but you still can "connect" pipes to it. this still happens after manually placing another block there afterwards
![image](https://github.com/AztechMC/Modern-Industrialization/assets/91149414/e8a0e6f0-614c-40fb-950b-51dee57ef494)

**Comment by truepurpledino** [comment]
You can usually resolve this issue by using this debug command after changing `enableDebugCommands = false` to `true` in the MI config : `/mi pipes <pos> clear` where `<pos>` is the position of the pipe in the world.

**Comment by Technici4n** [comment]
`/setblock` correctly removes the pipe for me, must be another mod's fault.

**Comment by CommanderTso** [comment]
As a note - this is an issue with the Carry On mod (or at least it is for me using it in Prominence 2 in Aug 2024).  I've logged a bug [in the Github repo](https://github.com/Tschipp/CarryOn/issues/677) - it outlines the changes you need to make to the Carry On server config to disallow picking up wires, etc.
