### ISSUE TITLE
Configured Chests do not appear as inventory peripherals to CC: Restitched computers

### ISSUE THREAD

**Issue by brennie** [AztechMC/Modern-Industrialization#579]
When interacting with a configurable chest via a CC: Restitched computer, it does not appear to be recognized as an inventory peripheral. Inventory peripherals should have the following methods available:
- pullItems
- size
- list
- getItemDetail
- pushItems
- getItemLimit

However, the methods available are:
- pullItem
- items
- pushItem

Minecraft 1.19.2
Fabric 0.76.1+1.19.2
CC: Restitched 1.101.2
Modern Industrialization 1.6.15

**Comment by JustinHuPrime** [comment]
I think this is intentional - configurable chests only expose the Fabric item transfer API. The [UnlimitedPeripheralWorks](https://www.curseforge.com/minecraft/mc-mods/unlimitedperipheralworks) mod should add peripheral support for the Fabric item transfer API

**Comment by Technici4n** [comment]
It probably already supports the Transfer API, however MI does not implement slot support at the moment.

**Comment by SirEdvin** [comment]
[UnlimitedPeripheralWorks](https://www.curseforge.com/minecraft/mc-mods/unlimitedperipheralworks) introduce also slotless API support, so it should be fine in 1.19 and 1.20 versions.
