### ISSUE TITLE
[Feature Request] Floodlights

### ISSUE THREAD

**Issue by dnkmmr69420** [AztechMC/Modern-Industrialization#584]
Floodlights are a type of light that lights a much greater area than the standard vanilla light sources. The downside is that they require electrical power for them to run. They could also be upgradable where you can have them shine light further (at the cost of using more power). They could also be upgraded to expand the radius of light beam.

I have an idea how they could work. When they are turned on, they replace air or water blocks with these invisible light emitting blocks that extend to a certain distance. When they are turned off, the blocks are replaced with air or water depending if it is water logged. They are also turned on by a redstone signal

Lets compare the advantages and disadvantages of standard lights and the floodlights I am talking about

### Standard Light Sources:
Advantages: Requires no power
Disadvantages: Does not cover as much area

### Floodlights
Advantages: Covers a large area depending on the moduels added to it
Disadvantage: Requires power to run

**Comment by Technici4n** [comment]
That seems a bit out of scope for our mod, but I could see this being done by other mods. ;)
