### ISSUE TITLE
Fail to start minecraft 1.20.1 / draylar.magna.api.MagnaTool

### ISSUE THREAD

**Issue by buridan1999** [AztechMC/Modern-Industrialization#588]
Try mod versions: 1.7.1, 1.7.4, 1.7.5
Fabric API version: fabric-api-0.90.0+1.20.1

Failed to load class: dev.draylar.magna.api.MagnaTool

[Uploading log.txt…]()

**Comment by Technici4n** [comment]
Usually happens when another mod loads the wrong version of Magna.

**Comment by buridan1999** [comment]
There are only this mods:
![image](https://github.com/AztechMC/Modern-Industrialization/assets/25010424/fa776010-1aec-4150-8d36-fba9897752a9)

**Comment by Technici4n** [comment]
Please post the log again, your link doesn't work

**Comment by Technici4n** [comment]
Ah, unfortunately I don't support tlauncher.

**Comment by buridan1999** [comment]
@Technici4n, I can try another. Which is the best for you? I wil rty it

**Comment by buridan1999** [comment]
Try it with MultiMC, works fine, Thanks for help.
