### ISSUE TITLE
Modpack starts randomly crashing because of Modern Industrialization 

### ISSUE THREAD

**Issue by LeaderrCole** [AztechMC/Modern-Industrialization#589]
Everything was perfectly fine up until today, nothing has changed and nothing has been updated (for all I know)
[crash-2023-10-12_13.01.16-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/12885282/crash-2023-10-12_13.01.16-client.txt)

**Comment by Technici4n** [comment]
The MI config got corrupted, please try resetting it.

**Comment by LeaderrCole** [comment]
do I just delete it or? sorrry, no clue what I'm doing

**Comment by LeaderrCole** [comment]
got it figured out, thanks!
