### ISSUE TITLE
Obscure bug with cables

### ISSUE THREAD

**Issue by Imsvale** [AztechMC/Modern-Industrialization#59]
I had an issue where some of my MV to LV transformers weren't getting powered by my MV Electrum Cables. I removed some of the nearest Electrum Cable bits and replaced them, and it was fixed. It didn't seem to be the nearest cable bit (the one connecting to the transformer), but one a little bit further away. Maybe at the cable intersection. Not sure.

Weird thing is a transformer further downstream from the power source was still getting power. I suppose maybe there's no real direction to the "flow" of electricity, so maybe it's not relevant.

Unfortunately that's all the information I have. Just thought I would report as a heads up if it isn't useful for anything else. But maybe it can give a clue to a flaw somewhere in the cable code.

**Comment by Technici4n** [comment]
Which version are you on? In 0.3.x, power is not distributed evenly across the cables: the first machine that is found (and the order is "random") receives as much power as possible, then the next machine (again chosen "randomly") receives as much as possible, and so on...

Version 0.4.x fixes this behavior by trying to distribute power evenly across the network, but it's still alpha and likely has plenty of (other) bugs. :)

**Comment by Imsvale** [comment]
I see. Yes, sorry, I'm on 0.3.15. Maybe it got somehow stuck on trying to provide just the one transformer with power and forgot that the other ones existed until I gave it a nudge by replacing the cables. ^^

I guess I'll wait for 0.4 and see if it might still happen. Probably quite a rare issue (first time I see it after running this for weeks), so I'll just see if it pops up again for now.
