### ISSUE TITLE
Superconductor cable draws power

### ISSUE THREAD

**Issue by Aphyxia** [AztechMC/Modern-Industrialization#590]
I'm not sure if this is solely a superconductor cable issue but that's where I encountered it.
By having a single piece of SC cable "outputting" from a **storage unit** it seems to "delete" the power. Having no cables connected it gains power as expected because it is supplied by several turbines running at full steam.
Video of the problem:
https://www.youtube.com/watch?v=nIAVJfdTZB0

It seems to work as intended (?) when I connect the output and input with a SC cable:
https://imgur.com/a/B4NXnE6
I also, pretty much instantly, get 70 GEU of power this way meaning the power was stored somewhere? Do SC cables store power themselves? I don't have anything connected that could store such an amount of power.

Playing on MC version 1.19.2 with MI 1.6.15 on the Prominence I modpack.

**Comment by GarrettNixSoft** [comment]
My understanding is that every cable type stores some amount of power per block, similar to how fluid pipes have their own capacity. This behavior can be seen easily by fueling a generator with nothing attached to it and then attaching cables to its output; with each cable placed, you will see the generator activate briefly to "charge" the cables.

In the case of SC cables, their capacity may just be very high, leading to the behavior you experienced.

**Comment by Aphyxia** [comment]
I thought of that but, as it is not documented anywhere, did not believe that to be the case. So by breaking a SC cable, I lose 1GEU of power. Oof.

**Comment by Technici4n** [comment]
Yeah this happens because superconductor cables store a lot of power each.
