### ISSUE TITLE
Texture visual bug

### ISSUE THREAD

**Issue by Faked4075** [AztechMC/Modern-Industrialization#598]
Some cars and gateways are equipped with a white texture on the front side, what should I do? Mods include sodium, indium, lithium, phosphor, and MI itself
![Screenshot_20231129_231549_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/AztechMC/Modern-Industrialization/assets/141859258/a3fd2f79-edcc-42ad-be75-5b16f1d9b556)

**Comment by Technici4n** [comment]
Unfortunately we don't support pojav launcher - the issue is probably coming from there.

**Comment by Faked4075** [comment]
> К сожалению, мы не поддерживаем программу запуска pojav — возможно, проблема возникла оттуда.

but without sodium there is no such bug
![Screenshot_20231130_133659_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/AztechMC/Modern-Industrialization/assets/141859258/a64df7db-483d-46cc-a54d-e858b3fe0443)

**Comment by Technici4n** [comment]
Like most other mods, Sodium does not support pojav either.

**Comment by Faked4075** [comment]
> Как и большинство других модов, Sodium также не поддерживает pojav.

So you support pojav, but sodium does not.

**Comment by Faked4075** [comment]
I would be very glad if you could help me(
