### ISSUE TITLE
[1.20.1] Minecraft crashes upon trying to render a custom multiblock controller made with KubeJS

### ISSUE THREAD

**Issue by KonSola5** [AztechMC/Modern-Industrialization#601]
Versions:
Modern Industrialization 1.7.4
Minecraft 1.20.1
KubeJS 2001.6.4-build.95
Sodium 0.5.3
Indium 1.0.27+mc1.20.1

To reproduce:
1. Follow the [ADDING_MACHINES.md](https://github.com/AztechMC/Modern-Industrialization/blob/master/docs/ADDING_MACHINES.md) and [MACHINE_MODELS.md](https://github.com/AztechMC/Modern-Industrialization/blob/master/docs/MACHINE_MODELS.md). Also add a blockstate.
(Or copy the files from StaTech: Industry)

2. Launch the game.

3. Notice that the held item is fine, but if you place the block, Minecraft crashes:
https://mclo.gs/yPDTocf

**Comment by Technici4n** [comment]
That generally happens when the custom machine doesn't have a proper model json.
