### ISSUE TITLE
Allow KubeJS to register custom motors to increase item pipe transfer speed

### ISSUE THREAD

**Issue by James103** [AztechMC/Modern-Industrialization#606]
For example, being able to register custom motors that are better than the Large Advanced Motor, or using other items as motors to increase MI pipe item throughput.

Example use cases (including but not limited to):
* Re-register the Large Advanced Motor to increase max transfer by 128 items instead of 64.
* Register additional higher tiers of motors to enable even more throughput.
  - Elite Motor (IV) and Large Elite Motor (LuV) for 512 and 2048 items every 3 seconds.
  - Ultimate Motor (ZPM) and Large Ultimate Motor (UV) for 8192 and 32768 items every 3 seconds.
* Add a Quantum Motor to enable the transfer of a billion items every 3 seconds, akin to the Quantum Upgrade but for items instead of EU.

**Comment by Technici4n** [comment]
We now have an event in 1.20.1 and a data map in 1.20.4+.
