### ISSUE TITLE
[BUG] Blast Furnace shows valid shape but won't work

### ISSUE THREAD

**Issue by CalebCox** [AztechMC/Modern-Industrialization#61]
**Note**
I'm experiencing this problem while using the All of Fabric 3 1.16.5 Modpack

**Describe the bug**
I've built the blast furnace as described and see a successful "Shape Valid" message when viewing the blast furnace. I'm working to make Silicon Dust specifically, which in the case of this modpack utilizes Quartz Dust from Tech Reborn and Coke Dust from MI to create 1 Silicon Dust. I added two Bronze Item Inputs, 1 Bronze Item Output and 1 Bronze Fluid Input for steam. Steam is full and item in/out automation is completely setup, I'm even seeing the 'Silicon Dust 0' within the Item Output as it recognizes the recipe but the blast furnace is still failing to start at all.

**Expected behavior**
Based on the recipe listed within REI and the prefilled 0 Silicon Dust within the Output Hatch, this should be turning the two input dusts into silicon dust (seemingly after 20 seconds based on the REI recipe screen).

**Screenshots**
<img width="556" alt="Screen Shot 2021-05-20 at 12 48 19 AM" src="https://user-images.githubusercontent.com/20094217/118920931-46478780-b905-11eb-978b-534a8c6fa6ce.png">

**Additional**
I'm unsure if this is an MI specific issue or an issue with the Modpack itself, I'll report the issue to the modpack maintainers as well if it's found to not be MI specific (per the AoF3 recommendations)

I've temporarily gotten over this issue myself thanks to AoF3 having KubeJS and creating a new recipe script for the Tech Reborn Industrial Blast Furnace that mimics the MI Blast Furnace recipe but that doesn't really solve the actual issue of the blast furnace not working at all.

**Comment by ProjectET** [comment]
Steam Blast furnace can only process recipes with a max of 2/4 EU. Silicon recipe requires 32 EU, you need an electric blast furnace for that.

**Comment by Technici4n** [comment]
Many thanks for the detailed report! You do indeed need an Electric Blast Furnace for recipes using more than 4 EU/t. The next AOF update will include a new version of MI that makes this much clearer in REI.

Sorry for the inconvenience, and thanks for the amazing high quality report. :)

**Comment by CalebCox** [comment]
@Technici4n @ProjectET Thank you both for the quick responses! Apologies for not noticing the output difference, I let REI confuse me at a glance.
