### ISSUE TITLE
[1.19.2] Steam Quarry Doesn't Function

### ISSUE THREAD

**Issue by Nekohime1989** [AztechMC/Modern-Industrialization#610]
Steam Quarry stopped functioning after updaying.
Tried building a new one, didn't work either.

**Comment by Azercoco** [comment]
Hi, can you provide a list of step and picture on how to reproduce the issue ?

**Comment by Nekohime1989** [comment]
![2023-12-30_09 08 42](https://github.com/AztechMC/Modern-Industrialization/assets/94816519/4a9ce4c5-163d-4598-8b37-48a976a1013d)
![2023-12-30_09 08 47](https://github.com/AztechMC/Modern-Industrialization/assets/94816519/14793d03-fbe7-4aed-86bf-529a8cc6fdde)
![2023-12-30_09 09 45](https://github.com/AztechMC/Modern-Industrialization/assets/94816519/54ef5bf1-1bfd-407c-8559-60a660adc908)
![2023-12-30_09 08 23](https://github.com/AztechMC/Modern-Industrialization/assets/94816519/6ba1b235-da0e-41a4-bff2-beeb26bf274c)

everything is steel grade but it wont turn on...

**Comment by truepurpledino** [comment]
You are using a gold drill, not a bronze drill, which requires more energy/t for its recipe than what the steam quarry can do, hence it not working.

**Comment by Nekohime1989** [comment]
oh... that was my mistake thanks.

**Comment by Kazuhiko-Gushiken** [comment]
@truepurpledino @Nekohime1989  actually you can overclock the steam quarry with gunpowder to reach the 8eu/t for gold to work, but its a very temporary use

**Comment by truepurpledino** [comment]
yea I know, but I knew OP didn't mean to do that
