### ISSUE TITLE
Detonate a AE2 Tiny TNT near a disguised pipe can crash server

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [AztechMC/Modern-Industrialization#611]
running on a 1.19.2 server
MI version: 1.6.16, AE2 version: 12.9.8

not sure it's AE2's problem or  MI, but the crash happens on the Primed Tiny TNT entity itself
crash report: 
[crash-2023-12-30_17.25.17-server.txt](https://github.com/AztechMC/Modern-Industrialization/files/13797636/crash-2023-12-30_17.25.17-server.txt)

**Comment by James103** [comment]
Does the game crash if you detonate a regular TNT or a creeper near a disguised MI pipe? If so, can you please attach the resulting crash report?

**Comment by Technici4n** [comment]
From the looks of it this is actually an AE2 bug.
