### ISSUE TITLE
How to place Item pipe on barrel

### ISSUE THREAD

**Issue by yu-re-ka** [AztechMC/Modern-Industrialization#613]
MI 1.8.0, Minecraft 1.20.1, I am shift right clicking with an item pipe on a locked (Air) barrel. I would expect that because of the shifting, it does not interact with the barrel and instead is placed as a block on the barrel, but in reality the item pipe stack gets inserted into the barrel.

**Comment by Technici4n** [comment]
You can use a wrench to connect the pipe to the barrel. (Click the center of the pipe in the direction you want to connect.)

**Comment by yu-re-ka** [comment]
I see. That's kind of annoying but by now I understand the mechanics change from 1.7.x to 1.8.0 and it makes sense.
