### ISSUE TITLE
request an official Modpack for Modern-Industrialization

### ISSUE THREAD

**Issue by evan0greenup** [AztechMC/Modern-Industrialization#619]
For each release of Modern-Industrialization, it would be nice to provide a modpack which include the latest support Minecraft version and all its dependency in curseforge or modrinth. 

It would make user who use MultiMC or PolyMC much easier to setup.

**Comment by Technici4n** [comment]
Too much effort for us, sorry. Most of the time, you don't need to update the dependencies, only MI itself. :)

**Comment by Lumiinos8100** [comment]
![image](https://github.com/AztechMC/Modern-Industrialization/assets/136110984/2c136dc9-0246-4f42-8914-7c5fa6b35eb4)
