### ISSUE TITLE
Placed modern_industrialization:bronze_compressor and an entire server was permacrashed

### ISSUE THREAD

**Issue by Blueshark0722** [AztechMC/Modern-Industrialization#62]
I am playing on a friend's server with a few mods. I saw a steam engine mod and thought it was cool so I focused that. I got to making a compressor and placing it kicked everyone from the server and shut it down. We had to delete the whole world file.

**Comment by Technici4n** [comment]
How am I supposed to debug this without the crash report? Please send it to me...

**Comment by Technici4n** [comment]
Closing, please reopen with a crash report if it happens again.
