### ISSUE TITLE
Synthetic oil 222 mb numbers don't make sense on NeoForge

### ISSUE THREAD

**Issue by Technici4n** [AztechMC/Modern-Industrialization#646]
Can't divide a bucket into 9 parts anymore...

There's possibly / probably other offenders as well.

**Comment by JustinHuPrime** [comment]
Could we, as a blanket change, make all of the 1/9th of a bucket recipes slightly more expensive by changing it to 1/10th of a bucket?

**Comment by Technici4n** [comment]
Depends on the recipe. Ingots should be 90 mb. For synthetic oil I have to check the uses.
