### ISSUE TITLE
Pipes producing errors in logs when placing

### ISSUE THREAD

**Issue by matt31084** [AztechMC/Modern-Industrialization#67]
I placed a fluid pipe to export from a tech reborn basic storage tank into a kibe entangled tank.  The pipe placed normally, but i noticed it wasn't removed from my inventory.  It seemed to duplicate itself, so I checked the server log and noticed some errors.  I've also had weird random issues in the end dimension.  pipes disappearing when broken, my wrench randomly disappearing, pipes aren't able to connect to other blocks when using the wrench.

Overworld fluid pipe placement:
https://paste.alloffabric.com/bikuqepobe.properties
End Dimension item pipe placement:
https://paste.alloffabric.com/omomatadib.properties

Environment:
All of Fabric 3 2.8.4 with no extra mods
Server running on same PC as client.

**Comment by Technici4n** [comment]
Thanks for the report, it is now fixed. `0.4.0-alpha.10` will be released in a few minutes.
