### ISSUE TITLE
Bronze Compressor not compressing

### ISSUE THREAD

**Issue by Widget1200** [AztechMC/Modern-Industrialization#68]
Modern Industrilization v0.4.0-alpha.08
All of Fabric 3 modpack v2.8.4

I'm on a server and the bronze compressor won't compress ingots, double ingots, or any other recipes I can try at the moment. It works on a single player world, so I dont really know how to fix this.

**Comment by Technici4n** [comment]
The server must update to the latest alpha, this is a bug that was fixed a few days ago.
