### ISSUE TITLE
Пропадают текстуры блоков

### ISSUE THREAD

**Issue by Apple025** [AztechMC/Modern-Industrialization#684]
Я использую версию 1.20.1 и версию мода 1.8.3, от 15.03.24
Когда зашел в игру было все в порядке, но минут 10 спустя, я заметил что у меня у всех блочных механизмов пропала текстура, и они стали прозрачными, решил очистить config, после захожу и вроде все норм текстуры вернулись, но спустя время они опять пропали, я  снова решил очистить config, но теперь и это не помогло

**Comment by Technici4n** [comment]
Probably an issue caused by another mod

**Comment by Apple025** [comment]
Решено)
