### ISSUE TITLE
[Feature Request] Pipe/cable in the mainhand + Pipe/cable in the offhand = attempt to place both

### ISSUE THREAD

**Issue by trunksbomb** [AztechMC/Modern-Industrialization#692]
I *think* this would be a simple change. When placing a pipe from the mainhand, check if there's a pipe in the offhand - if yes, attempt to place the offhand pipe *after* placing the first pipe. 

It would basically call the `onItemUse` (or whatever the equivalent code is nowadays) for the offhand pipe after placing the mainhand pipe. Therefore everything except the "check offhand for a pipe" would use existing code. If it's as simple as I hope it is, it would be just like placing one pipe then switching to another pipe and attempting to place it.

![image](https://github.com/AztechMC/Modern-Industrialization/assets/1904331/d0629b05-0d59-4b85-8749-042b9cd67577)

I want to double fist my pipes, please 😩

**Comment by Technici4n** [comment]
I think that would be super cursed. It's not like you can place 2x1 block columns like that...

Not gonna do it but I like the creative thought. :P

**Comment by trunksbomb** [comment]
You also can't place 2 blocks in one spot, but you can with MI pipes and cables :)

I'm holding out hope - one day..
