### ISSUE TITLE
rare random Crafting Issue

### ISSUE THREAD

**Issue by MSandro** [AztechMC/Modern-Industrialization#694]
NeoForge Version 20.4.225
MI: 2.0.17

Steps to Reproduce
It's hard to reproduce. When I enter a world it happens about 1 in 30 times that the crafting outputs are messed up. So recipes without input are loaded.

I don't necessarily just want to blame MI for this, sometimes an item from another mod comes out, e.g. Twilight Forest, Mekanism or Blue Skies.
I've been running different mod combinations dozens of times for hours. Load worlds at least 5-10 times each time only to notice that the error occurs again.
I hope someone can help me find out what the problem is. I will also report this bug to the other affected mods.

What You Expected
The recipes shouldn't get so mixed up.

What Happened Instead
![image](https://github.com/AztechMC/Modern-Industrialization/assets/10937159/6b3c59ce-7945-454d-a380-c7375a92d9f5)
![image](https://github.com/AztechMC/Modern-Industrialization/assets/10937159/fb96774b-6161-44e2-aec1-2d1615b4ed5c)

**Comment by Technici4n** [comment]
Can you post the recipe ID of the broken recipe? There is an option in EMI to show recipe IDs.

**Comment by MSandro** [comment]
![image](https://github.com/TeamTwilight/twilightforest/assets/10937159/d2f7ba5f-7539-4f2d-b441-6eaaae465142)

After re-joining or reloading (without any changes, no DataPack, etc.):
![image](https://github.com/TeamTwilight/twilightforest/assets/10937159/e6e9bb7b-5331-4090-b878-c050995ccd5f)


It is the same ID, but something gets messed up randomly.

**Comment by MSandro** [comment]
I have found this bug in this modpack: https://www.curseforge.com/minecraft/modpacks/new-game-neoforge-version
Since MI is not part of these packs, I can rule it out.
