### ISSUE TITLE
Can't make silicon dust in steam blast furnace

### ISSUE THREAD

**Issue by AcTaviousBlack** [AztechMC/Modern-Industrialization#70]
I'm trying to make silicon dust in the steam blast furnace but it doesn't seem to process. 

Things I have double checked to make sure it's not user error:
-Steel item input hatch
-Steam is available and getting into the bronze fluid input hatch
-Filled item slots to maximum with coke dust and quartz dust
-All items are modern industrialization. IE: No tech reborn dusts or similar
-Checked the steam blast furnace works with other items and recipes

I am playing on a private server with no edited settings, and a few other mods are installed as well such as tech reborn. I've ran into this same kind of problem trying to use the mixer to make more lava, but no matter what I did, I couldn't get it to work. I believe that this is a bug.

**Comment by Technici4n** [comment]
You need an Electric Blast Furnace for recipes that use more than 4 EU/t.

**Comment by Azercoco** [comment]
You should consider update MI to the last version where the Steam and Electric recipes are different REI categories.

**Comment by AcTaviousBlack** [comment]
> You should consider update MI to the last version where the Steam and Electric recipes are different REI categories.

So go back a few versions or something? That's pretty ridiculous to have to go from the latest version to an older version. I see that the book mentions that electric machines overclock recipes to 32 eu/t and in the electric blast furnace section it mentions it unlocks new recipes. I hope there will be a way to tell which recipes in the future. The latest version of REI and MI show that the recipe is available in both the steam blast furnace and electric blast furnace so you can probably see where my confusion came from. 

Also, I found a small typo in the guide book under the "Advanced Machines" section on the first page. "Like the other electric machines, >hese< new machines will only connect to LV cables."

**Comment by Technici4n** [comment]
> I hope there will be a way to tell which recipes in the future.

![image](https://user-images.githubusercontent.com/13494793/122592928-3be3ef00-d065-11eb-8aec-017606fba7e0.png)

![image](https://user-images.githubusercontent.com/13494793/122592993-4ef6bf00-d065-11eb-8a11-969131a0aac4.png)

**Comment by AcTaviousBlack** [comment]
> ![image](https://user-images.githubusercontent.com/13494793/122592928-3be3ef00-d065-11eb-8aec-017606fba7e0.png)
> 
> ![image](https://user-images.githubusercontent.com/13494793/122592993-4ef6bf00-d065-11eb-8a11-969131a0aac4.png)

Fair enough, thank you for the quick replies and dedicated developer work.
