### ISSUE TITLE
Removing empty fluid from machines

### ISSUE THREAD

**Issue by zarwald** [AztechMC/Modern-Industrialization#704]
![image](https://github.com/AztechMC/Modern-Industrialization/assets/71650304/6fbae906-c2c8-4eb3-9551-7d54a1d7b321)
My bronze machines show exactly 0 mB of steam in their input and I don't know how to remove it, neither a bucket nor even breaking blocks helps.

**Comment by Technici4n** [comment]
That's intended - these blocks require steam to work at all.

**Comment by zarwald** [comment]
Oh, I'm dumb. I've confused inputs, you can close that

**Comment by zarwald** [comment]
s
