### ISSUE TITLE
Minecraft crashses upon creating new world

### ISSUE THREAD

**Issue by CCrown04** [AztechMC/Modern-Industrialization#706]
Version: 1.20.1
Loader: Quilt on Curseforge
Crash report [pastebin](https://pastebin.com/YqXq0WdF)
Issue:
Minecraft crashes upon attempting to create a new world with error 
" java.lang.IllegalStateException: Item: modern_industrialization:platinum_block does not exist "

Modern industrialization was not installed at the time, I would prefer it to not be installed

**Comment by Technici4n** [comment]
Looks like you still have recipes that refer to MI blocks. You'll have to remove the offending data packs.

**Comment by Poopooracoocoo** [comment]
Caused by Blasting Base/Modded Metal Blocks ([Modrinth](https://modrinth.com/mod/blasting-smelting-metal-blocks) | [CurseForge](https://www.curseforge.com/minecraft/mc-mods/blasting-smelting-metal-blocks-with-mod)).

The ingot version is the one with this issue. The proportional version is fine.
