### ISSUE TITLE
What Does Shape Invalid Mean?

### ISSUE THREAD

**Issue by Nishant1500** [AztechMC/Modern-Industrialization#72]
Hi, i installed this mod and made my fisrt Coke Furnance but when i open it it Shows Shape Invalid. What Does that mean? and how to fix it?

**Comment by Technici4n** [comment]
The Coke Oven is a multiblock, and it means you have not fully built it yet. Check out the guide book page for more info!
Note: you can hold a wrench to view the shape.

**Comment by Nishant1500** [comment]
Thank you
