### ISSUE TITLE
Quarry: Configure ores.

### ISSUE THREAD

**Issue by Derpford** [AztechMC/Modern-Industrialization#73]
I'm playing this alongside Yttr, and I want to add Gadolinite to the drops table for the Quarry (likely in the steel pipe pool). How would I go about doing this? Is it possible as of right now?

**Comment by Birgliss** [comment]
Yeah, it's possible. As easy as modifying any other recipe.  
[Recipe found in the 1.16 branch.](https://github.com/AztechMC/Modern-Industrialization/blob/1.16/src/main/resources/data/modern_industrialization/recipes/quarry/steel.json)  
From there you'd just need to add another output object for gadolinite, like this snippet here:  
```json
    {
      "item": "yttr:gadolinite",
      "amount": 8,
      "probability": 0.015
    }
```  
And then you'd just load your custom recipe in a datapack.

**Comment by Technici4n** [comment]
Exactly! Thanks @Birgliss.

**Comment by Derpford** [comment]
Out of curiosity: It looks like it's possible to add quarry recipes for other kinds of item pipes, or possibly any item. Is this supported at all?

**Comment by Technici4n** [comment]
Yes, for example when AE2 is installed we have a recipe to turn ME cables into certus quartz ore.
