### ISSUE TITLE
ore generation disable option not work

### ISSUE THREAD

**Issue by KEJWII** [AztechMC/Modern-Industrialization#730]
Apparently in the options of this mod (not .config)
can be turned off ore generation
and it seems that it does not work

**Comment by Technici4n** [comment]
Which MC version?

**Comment by KEJWII** [comment]
1.20.1 fabric

**Comment by Technici4n** [comment]
That is indeed handled by datapacks. The option doesn't do anything anymore and was removed in 1.20.4.

**Comment by KEJWII** [comment]
if it's possible
there is an example datapack that would do it?

**Comment by Technici4n** [comment]
Sadly not. Look up how to change vanilla's ore config, I guess. It should be similar.
