### ISSUE TITLE
Monocrystalline Silicon will not craft in the Kanthal EBF

### ISSUE THREAD

**Issue by Twoscore23** [AztechMC/Modern-Industrialization#731]
I have 5 buckets of Argon and a stack of silicon in a valid Kanthal EBF with a MV input (fully charged) bronze item input and output, advanced fluid input, and bronze fluid output. Nothing happens it just sits idle. Let me know if you need any additional information.

**Comment by Twoscore23** [comment]
Oh and cause I feel this recipe is very comparable the Annealed Copper Hot Ingot works just fine with the oxygen and copper. Same with titanium

**Comment by Technici4n** [comment]
No idea. I just tried it and it's working for me, so it has to be a setup issue?
