### ISSUE TITLE
Steam quarry don't drop nickel

### ISSUE THREAD

**Issue by CristianoDeNuntis** [AztechMC/Modern-Industrialization#733]
Why steam quarry doesn't drop nickel? Im pretty sure that in some yt videos it work what i have to do?

**Comment by Swedz** [comment]
No nickel is not produced by any steam quarry recipes. It takes steel drills in an electric quarry. Always check recipes before assuming there's a bug with the mod. Some packs make changes to recipes too.

**Comment by CristianoDeNuntis** [comment]
ok thanks, now I should understand something, the j tells me that to create the silicone I need to put the quartz powder and the carbon powder in the electric blast furnace, but there aren't those inputs, what do I do?

**Comment by CristianoDeNuntis** [comment]
Sorry but there's no good wiki to follow

**Comment by Swedz** [comment]
The EBF is a multiblock. There is a guide book that will tell you how to input items into multiblocks.

**Comment by Swedz** [comment]
Also, @CristianoDeNuntis I highly recommend joining the [discord](https://discord.gg/Z5hGBuH) for questions like these rather than making an issue on the github ^^
