### ISSUE TITLE
[1.21] Strange graphical glitch on steam drill fuel gauge

### ISSUE THREAD

**Issue by MuteTiefling** [AztechMC/Modern-Industrialization#738]
Mod Version: 2.2.2-alpha

![image](https://github.com/AztechMC/Modern-Industrialization/assets/9543430/6f6892d3-d400-45c9-a02b-58c0ee68db05)

Mods:
https://www.curseforge.com/minecraft/modpacks/enigmatica10 with Modern Industrialization added

**Comment by Technici4n** [comment]
Fixed by https://github.com/AztechMC/Modern-Industrialization/pull/742.
