### ISSUE TITLE
[1.21] multiblock machines look wrong

### ISSUE THREAD

**Issue by ghost** [AztechMC/Modern-Industrialization#739]
![Screenshot_20240619_082600](https://github.com/AztechMC/Modern-Industrialization/assets/144516052/10fc08a0-c2c8-42f1-9c58-76b890d4a198)
![Screenshot_20240619_083040](https://github.com/AztechMC/Modern-Industrialization/assets/144516052/42567edf-84e1-497a-aac5-4684712efd03)
they look out of place

**Comment by Technici4n** [comment]
What's wrong? If you hold a wrench you see a preview.

**Comment by ghost** [comment]
> What's wrong? If you hold a wrench you see a preview.

Doesn't it look wrong?
[Screencast_20240619_103242.webm](https://github.com/AztechMC/Modern-Industrialization/assets/144516052/30e18fcc-1614-4638-9b35-539b6351636f)
I guess the video doesn't open
https://youtu.be/eTiZlb3qsys
