### ISSUE TITLE
Update modrinth

### ISSUE THREAD

**Issue by Samisaprogrammer** [AztechMC/Modern-Industrialization#74]
Bruhhhhhh

![image](https://user-images.githubusercontent.com/59611020/125391296-c03f3e80-e393-11eb-81c5-eca99d778b01.png)
![image](https://user-images.githubusercontent.com/59611020/125391325-d3520e80-e393-11eb-80a8-543a5d557c05.png)

**Comment by Technici4n** [comment]
Just use curseforge.

**Comment by Samisaprogrammer** [comment]
Why have modrinth then???
