### ISSUE TITLE
Idea for Coke Ovens

### ISSUE THREAD

**Issue by VincentYankowsky** [AztechMC/Modern-Industrialization#740]
How about adding Charcoal as an optional item to use that gives less of the same ingredients that normal coal provides when trying to use the coke oven?   The issue with coal is that it is a limited use resource.  And the only way to get an infinite supply is killing wither skeletons.

**Comment by warbaque** [comment]
There's drills and quarries in MI that give you infinite ores. So no resource is really limited use.

**Comment by Technici4n** [comment]
Indeed, it is intended that a quarry is required to produce coke continuously.
