### ISSUE TITLE
Tanks rendering opaque when using resource pack.

### ISSUE THREAD

**Issue by Haemophilu** [AztechMC/Modern-Industrialization#748]
Using resource packs causes tanks to become opaque with their base color.

![2024-06-23_13 08 47](https://github.com/AztechMC/Modern-Industrialization/assets/116599266/e36a7ee2-d2e3-4441-9b96-22eaff60714f)

Resource pack used.

[MI Retextured.zip](https://github.com/user-attachments/files/15945545/MI.Retextured.zip)

**Comment by Technici4n** [comment]
The `models/base/tank.json` model needs to include `"render_type": "cutout"` on NeoForge. ;)

**Comment by Haemophilu** [comment]
works perfectly now, thanks :)
