### ISSUE TITLE
Mod Loading Error

### ISSUE THREAD

**Issue by XRealismX** [AztechMC/Modern-Industrialization#756]
I only have Modern Industrialization and Modern Dynamics mods and the dependency Cloth Config v15 API. I am using Minecraft 1.21 on NeoForge 21.0.38-beta. When I loaded up the pack with only those mods, and NeoForge; it failed to load with the message you see in the screenshot.

lastest.log > https://mclo.gs/JkqEiin
Crash Report > https://mclo.gs/esPWDMe

![Screenshot 2024-06-26 192624](https://github.com/AztechMC/Modern-Industrialization/assets/13025294/4126c53c-9bbf-4833-b602-beee81541062)

**Comment by Technici4n** [comment]
That is fixed in MI 2.2.4-alpha!
