### ISSUE TITLE
Steam drill not working when refueling

### ISSUE THREAD

**Issue by GideonBear** [AztechMC/Modern-Industrialization#76]
Hi, I am playing this mod in 1.16 with my friend, and we have spotted a bug. When you use a steam drill, every time it has to refuel, (there are no seconds left,) it will not break the block you break. After 1-2sec, it will, but not the surrounding blocks. After that it works fine.

**Comment by FreeFull** [comment]
The same happens in 1.17.1. The worst part is, the one block that does break doesn't even drop an item.

**Comment by Technici4n** [comment]
This is now fixed in 1.17. It won't be fixed in 1.16 though, sorry.
