### ISSUE TITLE
Neoforge 1.20.4 Drills void fluid tanks from other mods when mining

### ISSUE THREAD

**Issue by Saereth** [AztechMC/Modern-Industrialization#772]
Using a Mekanism basic tank for example filled with soldering alloy. If you mine it up with a steam drill it will return an empty tank. Not sure if this is on MI's side or mekanism, if it's Mek let me know and i'll open an issue with them. Ty!

**Comment by Saereth** [comment]
Here is a video of the issue, this impacts MOST mods tanks, including just outright deleting MI's own tanks.
https://drive.google.com/file/d/1tTomiamwtL9wy7TqJZewIzQDZ4L3NtuY/view?usp=sharing

**Comment by Technici4n** [comment]
Sorry this took a bit. It is fixed in MI 2.0.24. :)
