### ISSUE TITLE
MI Machine output slot locks up

### ISSUE THREAD

**Issue by guvnor33** [AztechMC/Modern-Industrialization#773]
MI machines' output slots get stuck when there's an overlapping input/output. To clarify, when the output slot of an MI machine contains something like dust for example and then dust is inserted into the input slot, the machine will lock up. This happens on the following MI machines: The wiremill, the macerator, the compressor, the mixer, the cutting machine. 

Another example: You are using the cutting machine to make bronze rods and then you put some bronze rods into the input because you need bronze bolts, The machine will lock up if there are bronze rods in the input and there are still leftover bronze rods in the output. No bolts for you!

To clarify, the machines' output slot locks entirely, even if the machine is set to auto eject and even if there is an adjacent inventory attempting to pull.

**Comment by Technici4n** [comment]
Not sure what you mean? For me it works fine...

![image](https://github.com/AztechMC/Modern-Industrialization/assets/13494793/e051e89c-dd4b-4a10-980e-fac41a86bca2)

![image](https://github.com/AztechMC/Modern-Industrialization/assets/13494793/5ce58b1a-5233-4ff2-825b-1a2c7e5339aa)

This was on 1.21, maybe some other version or some other mod in the pack causes this.

**Comment by BrunoMacadre** [comment]
I've probably same issue (or an equivalent). I play StaTech Industry modpack. I'm using MI and create, I'm using belt and funnel to insert and extract item in ML machines. But even with the auto-extract activated MI machines never extracts if another item is in input slot. For exemple : if some iron ingot are inserted into an MI compressor the compressor start issuing plates but never extract them if some iron ingot are always in input slot. When the last iron ingot start processing if another ingot is waiting and is inserted into the compressor the iron plates never extract and it locks the entire process.

Step to reproduce :
1. Create a working create belt
2. Put a MI machine (compressor, cutting, wiremil, ..) over the belt with 1 funnel for insertion et another funnel for extraction at the opposite.
3. Drop some iron ingot followed by some copper ingot (feel free to use other ingot).
4. Iron ingots are processed but iron plates locks into output slots...

I hope my explanation was clear.

Edit: Modern Industrialization 1.6.18 is in the modpack.

Regards,
Bruno

**Comment by BrunoMacadre** [comment]
I've just doing some tests :

- Trying andesite and bronze funnels => Same behaviour output locks
- Replacing output funnel by item pipe (from Modern Dynamics) => Same behaviour output locks (seems to be working first time I configure the pipe, but locks after)
- Putting another MI machine instead of funnel or pipe => It works !
- Putting barrel instead of funnel or item pipe => It works !

So actual workaround : Putting a barrel at the machine output and extracting barrel content with funnel or item pipe

Regards,
Bruno

**Comment by Technici4n** [comment]
@BrunoMacadre this is most likely a Create issue. Unfortunately, Create Fabric 1.19.2 has a number of unsolved bugs like that. :(
