### ISSUE TITLE
MI Pipes break when moved by a create contraption

### ISSUE THREAD

**Issue by ShadowFox88** [AztechMC/Modern-Industrialization#774]
This is a similar issue to https://github.com/AztechMC/Modern-Industrialization/issues/460, and has similar effects.

**Comment by Technici4n** [comment]
The pipes are in the `c:relocation_not_supported` block tag. I think that it's up to create to support that. Can you clarify for which Minecraft version you opened this issue?

**Comment by ShadowFox88** [comment]
I tried this on All of Fabric 7, on one of the v2.2.x versions. It uses Minecraft 1.20.1

**Comment by Technici4n** [comment]
I think this is a Create issue. MI Pipes should be tagged already: https://github.com/AztechMC/Modern-Industrialization/blob/1.20.1/src/generated/resources/data/c/tags/blocks/movement_restricted.json. Not much to do on my end unfortunately.
