### ISSUE TITLE
Pipes may stop working at the chunk borders

### ISSUE THREAD

**Issue by Salovlas** [AztechMC/Modern-Industrialization#778]
The pipes stopped working on the modpack 1.19.2 Fabric that I'm playing on. The latest version of the mod.

![2024-07-11_16 52 37](https://github.com/AztechMC/Modern-Industrialization/assets/175323962/c3a1b5a9-5b66-49b6-b35e-90868c8afb96)
![2024-07-11_16 53 13](https://github.com/AztechMC/Modern-Industrialization/assets/175323962/c704a10a-c05d-4c77-b7e0-ce4d3025b638)
![2024-07-11_16 53 14](https://github.com/AztechMC/Modern-Industrialization/assets/175323962/bd30b6d5-200a-4f36-9161-ffe73766d618)

**Comment by Technici4n** [comment]
There is a nonzero chance that this is actually a Create issue. Honestly I have no idea, and 1.19.2 is getting too old for me to spend too much time on it. Sorry 😓
