### ISSUE TITLE
Why was fabric support abandoned?

### ISSUE THREAD

**Issue by hl2jeep** [AztechMC/Modern-Industrialization#780]
I'm just wondering why fron 1.20.4 fabric will no longer be supported, it's kinda disappointing to see one of the few fabric tech mods go EOL (atleast on fabric) it's never explained why anywhere.
I'm just curious.

**Comment by Technici4n** [comment]
To put it simply, I am convinced that NeoForge will fix the modloader divide and I am working towards that. Maintaining the mod for both loaders is too much work, so a choice has to be made. I chose NeoForge so that the community can eventually have *all* the mods on the same loader.

**Comment by hl2jeep** [comment]
> To put it simply, I am convinced that NeoForge will fix the modloader divide and I am working towards that. Maintaining the mod for both loaders is too much work, so a choice has to be made. I chose NeoForge so that the community can eventually have _all_ the mods on the same loader.

Totally understand that, I honestly had issues with fabric ever since it first came out, I hope neoforge will take over. But I must ask.
I'm not a mod developer but theoretically if someone made a pull request with fabric support, would you merge it?

**Comment by Technici4n** [comment]
No, I'd encourage that person to maintain their unofficial version of the mod separately. The license allows it, I only ask that the name clearly indicate that it's an unofficial version. ;)

**Comment by Hellscaped** [comment]
There will never be one "universal" modloader.

Fabric exists as a minimal loader to update as fast as possible, with minimal overhead. Its much lighter than forge. It doesn't focus on mod compatibility (everyone directly touches the game code) so you have to specially craft your modpack.

Whereas, Forge is heavy and takes a while to update, as they have to port their middleman API that enforces strict mod compatibility.

There will always be a modloader divide for these reasons. Simply different usecases for loaders.

**Comment by Hellscaped** [comment]
Basically,

You use Forge if you want an ultramodded massive pack that just "works".

You use Fabric if you want mods that mixin and edit the core of the game, or just want a light loader overall.
