### ISSUE TITLE
Crash when trying to change recipe in wiremill

### ISSUE THREAD

**Issue by MoyVahn** [AztechMC/Modern-Industrialization#783]
Hello, I am experiencing a consistent and repeatable crash when using a rather small load order including this mod. Some interaction, based on my admittedly amateur reading of java logs, between MI and Just Enough Items when trying to view/set recipes in the wiremill menu (tested, both the steel and electric ones cause this issue) will immediately cause my game to CTD. I have also tested this by paring down my load order to just MI, JEI, and all required dependencies to still experience this CTD.

Pastebin link to the crash log 
https://pastebin.com/rN86HN9k

Steps to reproduce:
All mods listed in the crash log are installed and loaded via Neoforge (version 21.0.91), running on Java 1.21.

Place a wiremill, either variety.
Insert ingots and power supply, attempt to select recipe.
Immediate CTD. 

Notably, happens to all 8 players on the server I'm running for my friends. So it is not an isolated issue with just my install.

I've tried completely wiping out my minecraft installation, including all mods&neoforge, and redownloading everything; inserting a java arguement to allocate more RAM to minecraft (4gb, 8gb, and 16gb in sequence) to no avail.

Any help would be appreciated.

**Comment by MoyVahn** [comment]
Update: Also happens with all other machine types that have selectable recipes.

**Comment by Technici4n** [comment]
This looks like a bad interaction between JEI and LowDragLib. Not MI related I think.
