### ISSUE TITLE
Pipes crushing the game 

### ISSUE THREAD

**Issue by Tomoyukiryu** [AztechMC/Modern-Industrialization#784]
I don't know what causes the crush exactly, but log said something about pipes from this mod 
[http://0x0.st/X9sM.txt](url)

System:
OS:Arch Linux 64-bit x86
GPU:Nvidia
CPU:Intel 9th gen

Sorry for not providing more details

**Comment by Technici4n** [comment]
Duplicate of https://github.com/AztechMC/Modern-Industrialization/issues/745.
