### ISSUE TITLE
mod doesnt load with neoforge 1.21

### ISSUE THREAD

**Issue by theguymandude1** [AztechMC/Modern-Industrialization#785]

**Comment by Technici4n** [comment]
Last time I checked it did. Consider including important information such as the versions you used, and the crash log.

**Comment by theguymandude1** [comment]
> Last time I checked it did. Consider including important information such as the versions you used, and the crash log.

i just tried switching to 1.20.4 and it still wouldnt load, is there another mod that is needed???
java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/configdata

**Comment by Swedz** [comment]
As both the curseforge and modrinth pages indicate, Cloth Config API is required.
