### ISSUE TITLE
EMI Recipe Transfer not working [1.20.4]

### ISSUE THREAD

**Issue by MSandro** [AztechMC/Modern-Industrialization#786]
MI v2.0.24
EMI 1.1.10
NeoForge 20.4.237

tried with the Refined Storage Pattern Grid.
![image](https://github.com/user-attachments/assets/304f66eb-5968-4252-a5d4-93aa7758b331)

**Comment by Technici4n** [comment]
I believe that is a refined storage issue if you are talking about the pattern grid.

**Comment by MSandro** [comment]
Thanks for the information. I'll remove EMI. Because it works with JEI.
Even if I try to add a Recipe to a Machine it does not work with EMI.
