### ISSUE TITLE
Crashing due to kubejs integration

### ISSUE THREAD

**Issue by MuteTiefling** [AztechMC/Modern-Industrialization#796]
When I attempt to load a world, I get a message about invalid data packs. 

When I try to make a new world, the game crashes out to this: 

[crash-2024-07-23_13.03.05-client.txt](https://github.com/user-attachments/files/16352226/crash-2024-07-23_13.03.05-client.txt)

MI 2.2.10 is the last version that works. .11 and .12 both give the above error.

**Comment by Technici4n** [comment]
Looks like a KJS version mismatch. There's a chance that #795 fixes this.

**Comment by Technici4n** [comment]
Yeah #795 should be the fix.

**Comment by MuteTiefling** [comment]
Awesome thanks!
