### ISSUE TITLE
Fluid pipes randomly connecting

### ISSUE THREAD

**Issue by BlazeAxtrius** [AztechMC/Modern-Industrialization#80]
I have this setup! I am playing All of Fabric 4.
![Untitled](https://user-images.githubusercontent.com/5176481/126965831-3b2cf89e-fd72-486f-8d37-87d209fc9ddd.png)

The issue is that the water pipe and the steam pipe sometimes connect between each other and the water pipe gets filled with steam. This has happened several times already and for the time being the solution is to build the pipes one block apart so that they can't connect. I am not sure why that happens.

Also I get a WARN in the console that says "Amount > 0 but fluid is blank, deleting some fluid!". This mostly appears when someone logs into the server. I am not sure if it is part of this mod though.

I disconnected and reconnected and the pipes are connected again.
![Untitled1](https://user-images.githubusercontent.com/5176481/126966585-418d6c88-223f-45ee-b969-188df87d82dd.png)

**Comment by FreeFull** [comment]
As a workaround, you could dye the steam pipes with a different colour, until this bug gets fixed.

**Comment by BlazeAxtrius** [comment]
> 
> 
> As a workaround, you could dye the steam pipes with a different colour, until this bug gets fixed.

Thanks! The colored pipes are great.

**Comment by Technici4n** [comment]
Hmmm yes, the warning message means that for some reason the fluid doesn't get read properly. This typically happens when the world saved data of the pipe networks doesn't get saved properly.
