### ISSUE TITLE
Steam Quarry, doesn't seem to work

### ISSUE THREAD

**Issue by KryxusCZ** [AztechMC/Modern-Industrialization#808]
In the quarry I have everything I need, drills in, connected steam, hatch for output, and I am kinda lost for past 2 hours now, and don't know how to make it work.
![2024-07-27_10 26 32](https://github.com/user-attachments/assets/51435286-ed36-4336-8943-2727c528f3c6)
![2024-07-27_10 26 35](https://github.com/user-attachments/assets/176fc44b-d693-456c-9fa7-a501babd5b70)
![2024-07-27_10 26 39](https://github.com/user-attachments/assets/d989f278-96fc-4c31-9bc1-7a756b3e7a72)
![2024-07-27_10 26 44](https://github.com/user-attachments/assets/2f8ec245-09fa-462f-ac95-7d7f63c06dfa)
![2024-07-27_10 26 48](https://github.com/user-attachments/assets/1c366754-b296-4be6-939e-32df212aa2ff)
![2024-07-27_10 26 53](https://github.com/user-attachments/assets/285e8d15-b716-4178-af93-8e95e0e4ac2b)

**Comment by likhogub** [comment]
@KryxusCZ How did you resolved your problem? Probably I have the same issue

**Comment by zarwald** [comment]
> @KryxusCZ How did you resolved your problem? Probably I have the same issue

They've put drill heads instead of drills themself
