### ISSUE TITLE
Jetpack 1.17.1

### ISSUE THREAD

**Issue by Metyjordan** [AztechMC/Modern-Industrialization#81]
I don't know if this is a bug or not 
 
 https://www.youtube.com/watch?v=6UVJR-_1P14

**Comment by Technici4n** [comment]
That's probably a compat issue with FallFlyingLib (included in Winged). Is it installed in your 1.17 instance, but not in your 1.16 instance?
We have plans to fix it, but it's quite low priority. (Blame FFL's awful mixins).
