### ISSUE TITLE
Large Electric Furnace crashes game when trying to render multiblock using wrench

### ISSUE THREAD

**Issue by hobnob11** [AztechMC/Modern-Industrialization#820]
Minecraft version: 1.20.4, Neoforge version: 20.4.237, MI Version: 2.0.25, Modpack: FTB Neotech 1.6.0

steps to reproduce: 
1) place down a large electric furnace
2) hold a MI Wrench and look at the block
3) observe game crash

also, EMI usually shows what blocks are needed to complete the multiblock, but this doesn't show up for the large electric furnace, which leads me to assume that the multiblock isn't defined properly? 

crash report:
[crash-2024-08-05_02.51.27-client.txt](https://github.com/user-attachments/files/16489900/crash-2024-08-05_02.51.27-client.txt)

**Comment by Swedz** [comment]
This is an issue with EI not MI. It was fixed in EI 1.1.4 for 1.20.4 and 1.4.4 for 1.21

**Comment by hobnob11** [comment]
thanks!
