### ISSUE TITLE
Is it possible to update from fabric 1.20.1 to neoforge 1.21?

### ISSUE THREAD

**Issue by maned2** [AztechMC/Modern-Industrialization#823]
I tried to update, the mod itself worked, but all the items related to mi - disappeared (
Or is the update not possible?
I have many errors like: 
[Server thread/ERROR] [minecraft/ItemStack]: Tried to load invalid item: 'Item must not be minecraft:air'
[Server thread/WARN] [Modern Industrialization/]: Amount > 0 but fluid is blank, deleting some fluid!

**Comment by Technici4n** [comment]
Not possible, no.
