### ISSUE TITLE
The added machine texture does not display

### ISSUE THREAD

**Issue by Water-Gate-King** [AztechMC/Modern-Industrialization#824]
1.21Neoforge, Modern-Industrialization2.2.16, Kubejs2100.7.0build.119
game：
![image](https://github.com/user-attachments/assets/adb223a9-0c9e-4d1b-af56-d218342e7844)
file path:
![image](https://github.com/user-attachments/assets/5976da57-a454-49fa-8a0c-faa5f40229d1)
I am unable to identify any errors
js:
MIMachineEvents.registerMachines(event => {
    event.craftingSingleBlock(
		// English name, internal name, recipe type (see above), list of tiers (can be bronze/steel/electric)
		"Autoclave", "autoclave", AUTOCLAVE, ["electric"],
		// Background height (or -1 for default value), progress bar, efficiency bar, energy bar
		186, event.progressBar(95, 45, "arrow"), event.efficiencyBar(48, 86), event.energyBar(4, 4),
		// Number of slots: item inputs, item outputs, fluid inputs, fluid outputs
		2, 2, 2, 2,
		// Capacity for fluid slots
		16,
		// Slot positions: items and fluids.
		items => items.addSlots(39, 35, 2, 1).addSlots(107, 35, 2, 1),
		fluids => fluids.addSlots(39, 55, 2 , 1).addSlots(107, 55, 2, 1),
		// front overlay?, top overlay?, side overlay?
		true, true, true
	);
  })

**Comment by Technici4n** [comment]
You need to enable runtime datagen to produce the required model files.

**Comment by Water-Gate-King** [comment]
OK, I can successfully use runtime datagen in 1.19.2, but in 1.21, it dose not work.

**Comment by Technici4n** [comment]
Keep in mind that the JSON format changed between 1.19.2 and 1.21. This might explain why the latter doesn't work?
