### ISSUE TITLE
Crash when right-clicking on a pipe attached to a machine to edit filters, I/O, etc.

### ISSUE THREAD

**Issue by WarMind666** [AztechMC/Modern-Industrialization#826]
Minecraft version:  1.20.4
Modern Industrialization version: 2.0.25
NeoForge version: 20.4.237

Duplication of error:

1.) Place an item or fluid pipe.
2.) Right-click the pipe part attached to the machine to view the pipe GUI.
3.) Receive the attached error message.
![Screenshot 2024-08-07 090135](https://github.com/user-attachments/assets/72b867f1-0103-4cbc-848a-58e1b8f918c4)

Troubleshooting applied:
Disable other mods referencing Modern Industrialization.
Wrench works to change insert/extract behaviour, but unable to access GUI.
This error is being experienced in single player.  I have not yet attempted on a server, since trying to squash bugs before uploading to a server.

**Comment by James103** [comment]
What do you get in the client and server logs when disconnecting due to the above error?

**Comment by WarMind666** [comment]
Found the issue.  It is something that Visual Overhaul does to the GUI that was causing the issue.

**Comment by WarMind666** [comment]
I will still add log information, for mod author to look at, if they so desire, since the issue does not seem to be with their mod, but Visual Overhaul.  Just in case there is something that they can do on their end.

Disabling Visual Overhaul resolved the issue.

https://pastebin.com/kke2k7ev

**Comment by Technici4n** [comment]
Indeed, Visual Overhaul issue I think.
