### ISSUE TITLE
my game crashes whenever i look at the items in the rei/jei on the all of fabric 4 modpack

### ISSUE THREAD

**Issue by wnbrn** [AztechMC/Modern-Industrialization#84]
whenever I go to look at the items in the jei thing they are untextured blocks and then my game instantly crashes, not sure why. I'm playing on the all of fabric 4 mod pack, and I installed the  iris-fabric mod as well. 

The game crashed whilst rendering screen
Error: java.lang.reflect.UndeclaredThrowableException
Exit Code: -1

**Comment by Technici4n** [comment]
Please post the full crash log.

**Comment by Technici4n** [comment]
Please reopen with a crash log if the issue persists.

**Comment by m44ster** [comment]
you are probably using sodium without [iris](https://modrinth.com/mod/iris)

**Comment by m44ster** [comment]
ups I meant [indium](https://modrinth.com/mod/indium)
