### ISSUE TITLE
Storage block to ingot recipes use shaped recipes instead of shapeless

### ISSUE THREAD

**Issue by rlnt** [AztechMC/Modern-Industrialization#844]
Modern industrialization uses shaped recipes for converting storage blocks to ingots. This should be shapeless instead. Vanilla is also using shapeless for Iron Blocks to Iron Ingots.

Nuggets to ingots and and ingots to blocks should be shaped instead but this is already the case in the mod.

Minecraft: 1.21.1
NeoForge: 21.1.21
Modern Industrialization: 2.2.16-beta

**Comment by Technici4n** [comment]
This is intended. You'll notice that one of the inputs is not tagged.

**Comment by Technici4n** [comment]
Oh the unpacking recipes. Hmm

**Comment by rlnt** [comment]
The packaging recipes are fine. Unpacking should follow vanilla tho. It messes with recipe duplicates detection. 🙃
