### ISSUE TITLE
Water visible through terrain, possibly a Sodium/Induim conflict

### ISSUE THREAD

**Issue by TheSpiderDungeon** [AztechMC/Modern-Industrialization#85]
I haven't done much besides isolate which mod was making me see water through the terrain when looking above the horizon (it's definitely this one), but I will try to do whatever you need to help figure out what happened.

I went through my newly installed mods and disabled everything that seemed like it would interact with the renderer, and MI's multipart wires sounded like they would affect something. I don't really know what it would be about it, I just picked it because it was maybe possibly loosely connected.

The only thing I can think of is a conflict with Immersive Portals, or Sodium/Indium. Here's a full mod list:
https://pastebin.com/7xY9gT71

Sorry about the directory being added to the names; I had spent the time typing it all out individually but forgot to click "Create Paste" and didn't feel like typing it all out again, so I just did a "Copy as Path".

**Comment by Technici4n** [comment]
Hmmm, does the conflict go away if you remove MI but keep sodium/indium?

**Comment by TheSpiderDungeon** [comment]
It does.

**Comment by Technici4n** [comment]
That might have been fixed now, can you try again with the latest 1.17 MI? Thanks!

**Comment by TheSpiderDungeon** [comment]
Looks like it, yes!
