### ISSUE TITLE
(Bug) Fluid pipes retain last fluid inside of them as a filter.

### ISSUE THREAD

**Issue by VladParshin** [AztechMC/Modern-Industrialization#852]
I'm currently playing on FTB NeoTech, and noticed some weird behavior with fluid pipes. I have fluid pipes set to pull out fluids from a machine that is automated to produce multiple fluids. The first fluid the pipe pulls out, is set as the fluid it will contain from there on in. 

For example: Blast Furnace set to produce Synthetic Oil, is set to produce Molten Redstone. Synthetic oil remains in the pipe with 0 buckets, the output tank empty after being filled originally, but Molten Redstone is not pulled out into the fluid pipe. Breaking the pipe, and putting a fresh one in, will allow the Molten redstone to flow out, and into the empty container.

I have not tried connecting it to other sections of the pipe still with Synthetic Oil in the above example, but testing it in another spot between another section of Synthetic Oil and Steam, the 0bucket content synth oil section, is instantly flooded by steam, when steam is connected to that section. There is some behavior going on, where the pipe is set to filter the first fluid that enters the connected sections, but does not clear despite being empty of any fluids, unless it is reconnected to a different fluid-containing section.

**Comment by Technici4n** [comment]
That is an intended feature, to make building fluid networks easier.
