### ISSUE TITLE
Incompability with Additional Additions

### ISSUE THREAD

**Issue by f-raZ0R** [AztechMC/Modern-Industrialization#86]
ok **somebody implemented mining levels in a cursed way**. I was told to go here after being told that it wasn't on Additional Addition's end.
You can not mine MI ores with a Rose Gold Pickaxe from Additional Additions, despite the pickaxe having a mining level of iron.
Other pickaxes from other mods, do not have this same problem. Other blocks, from other mods, do not have this same problem. It is only these two mods, and these two mods together, that have this problem.

This is some :concern: level shit and I have no idea **why it is like this**.

**Comment by Technici4n** [comment]
They must tag their pickaxe with the fabric tool tag (`fabric:pickaxes`).
