### ISSUE TITLE
Scewdriver not available

### ISSUE THREAD

**Issue by rosshar** [AztechMC/Modern-Industrialization#860]
I'm playing Modern Industrialization version 2.2.18-beta on a public ATM 10 server and there is no screwdriver to change the template of the EFB to Kanthal. Has this changed from screwdriver to something else, or has screwdriver not been implemented yet in this version?

**Comment by ramidzkh** [comment]
The screwdriver was removed, you should be able to change the tier inside the main block's GUI like this:
![image](https://github.com/user-attachments/assets/fdc9b9b6-8852-4d72-b218-ad6a50764354)

**Comment by rosshar** [comment]
I have been able to update to Kanthal. Thank you for your help!

**Comment by rosshar** [comment]
Issue closed
