### ISSUE TITLE
Add config option for item pipe base transfer rate

### ISSUE THREAD

**Issue by gr8pefish** [AztechMC/Modern-Industrialization#865]
Simply put, allow item pipe transfer rates to be easily changed from the hardcoded 16 per operation.

Combined with limiting motor availability, and other custom work, it will then theoretically be possible to create throughput issues as an interesting logistical problem to solve in a modpack.

Also should be a super easy add from your end. Thanks!

(1.21+ only is fine too, for my use case)

**Comment by Technici4n** [comment]
Will be in the next release. :)

**Comment by gr8pefish** [comment]
Thank you! All your hard work, this included, is greatly appreciated 🙏
