### ISSUE TITLE
Where is Compatibility with REI

### ISSUE THREAD

**Issue by BodyaTopBro** [AztechMC/Modern-Industrialization#866]
I'm sure it's not that hard to solve this problem, but the benefits will be many. So please add compatibility with REI

**Comment by Swedz** [comment]
There's already compat with REI

**Comment by BodyaTopBro** [comment]
What kind of compatibility are you talking about? You can't see the recipes for items that are created with MI blocks. Whereas in EMI you can.

**Comment by Swedz** [comment]
Right here
![2024-09-09_00 12 43](https://github.com/user-attachments/assets/d46135bb-482b-4451-8edd-8c8ad7a29be2)
