### ISSUE TITLE
Placeing a Pipe crashes game. Mod conflict?

### ISSUE THREAD

**Issue by Buggitt** [AztechMC/Modern-Industrialization#87]
I'm sure this is a weird conflict cause if I have the mod alone it's fine, but looking at the crash report myself I'm not sure where to start in looking for it. Was hoping someone might recognize something in figuring out what's causing it since there are about 80ish mods.

Everything that isn't a full block in this mod has a broken texture, and I attempted to place a pipe and it crashes the game. 
and if it helps at all when ran on a server it also crashes the server.

[crash-2021-08-05_10.12.14-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/6940507/crash-2021-08-05_10.12.14-client.txt)
![image](https://user-images.githubusercontent.com/7709438/128393864-df82e1e5-c8b2-4fe7-a8a3-9825eeaeb8c2.png)

**Comment by Technici4n** [comment]
Install indium.
