### ISSUE TITLE
Overdrive module doesn't auto insert into Vacuum Freezer

### ISSUE THREAD

**Issue by MuteTiefling** [AztechMC/Modern-Industrialization#884]
For most machines and multiblocks, I can right click it to insert a overdrive module. That doesn't work on a Vacuum Freezer, it just opens the GUI instead. 

MI 2.2.22

**Comment by MuteTiefling** [comment]
Implosion Compressor also just opens the gui instead of inserting

**Comment by MuteTiefling** [comment]
And Heat Exchangers :D

**Comment by Swedz** [comment]
Looks like `ElectricCraftingMultiblockBlockEntity` doesn't register the overdrive component as a component

**Comment by Technici4n** [comment]
> Looks like `ElectricCraftingMultiblockBlockEntity` doesn't register the overdrive component as a component

Looks like the culprit yeah.

**Comment by MuteTiefling** [comment]
Hrm, on logging out and back in, all those machines that wouldn't accept them with a right click have also lost the upgrade item

**Comment by Swedz** [comment]
> Hrm, on logging out and back in, all those machines that wouldn't accept them with a right click have also lost the upgrade item

Yeah, that would be because the component is not registered so it doesn't get saved in the block data
