### ISSUE TITLE
wthit error by this mod

### ISSUE THREAD

**Issue by VaporeonScripts** [AztechMC/Modern-Industrialization#895]
https://mclo.gs/chx0haq

**Comment by Swedz** [comment]
What makes you think MI has anything to do with this error? I don't see it mentioned in the error. luckytntmod is at fault as per the first line of the error.

```
[14:09:10] [Render thread/ERROR] [Mod Menu | ModsScreen/]: Error from mod 'luckytntmod'
```

**Comment by VaporeonScripts** [comment]
that got nothing to do with crash or sum, that line is a visual error with the config of luckytnt lib

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/706cd519-82b7-4fa9-9574-c2f8b3c70035)
![image](https://github.com/user-attachments/assets/dd130fd4-48b9-4def-869b-1af0963f9e66)
