### ISSUE TITLE
ore textures bugged with resource packs

### ISSUE THREAD

**Issue by pancakers2001** [AztechMC/Modern-Industrialization#90]
as seen in screenshot, ore textures are bugged with resource packs (resource pack used is stay true)
![2021-08-07_01 01 57](https://user-images.githubusercontent.com/76455320/128588628-430d0dd5-f920-4b89-86e3-1606193856de.png)

**Comment by Technici4n** [comment]
That's a feature unfortunately. You need to edit MI's overlays, as we color them then apply those directly on top of the ore texture. https://github.com/AztechMC/Modern-Industrialization/tree/master/src/main/resources/assets/modern_industrialization/textures/materialsets/ores

**Comment by pancakers2001** [comment]
That's ridiculous, why would you make that a feature knowing it will break with resource packs, why can't you just use a regular texture like every other mod?

**Comment by Technici4n** [comment]
Due to the sheer amount of items we have, we generate textures dynamically for item parts. However, recoloring ore textures specifically by hand is probably something we will consider if we can't find a more elegant solution to this problem.

**Comment by pancakers2001** [comment]
I think a more elegant solution would be to have them display over the stone texture instead, that way there is no conflicts over other ores

**Comment by Technici4n** [comment]
Using the stone texture looks really bad as we can't take advantage of the extra contrast ore textures have.

Fixed by using the default ore texture instead of the resource pack one. The fix will be in the next release, probably in a few days.
