### ISSUE TITLE
bronze things recipes issue

### ISSUE THREAD

**Issue by KEJWII** [AztechMC/Modern-Industrialization#902]
So
- Version: 1.20.1
- loader: Fabric
- Modern industrialization mod 1.8.4
- 
mods i used too:
- Tech reborn 5.8.7
- Industrial revolution 1.16.5-BETA

Issue description:

the attached pictures do not show the recipe for bronze or things for which bronze is used
![Base Profile Screenshot 2024 09 26 - 18 03 34 82](https://github.com/user-attachments/assets/9a4ad376-008c-4d79-9f99-16e7c25187ff)
![Base Profile Screenshot 2024 09 26 - 18 03 43 63](https://github.com/user-attachments/assets/abdf6421-1eec-4e2c-a3f6-717430979949)
![Base Profile Screenshot 2024 09 26 - 18 03 51 67](https://github.com/user-attachments/assets/dd7861fb-3b10-4df1-a57c-ae66867de9fa)
![Base Profile Screenshot 2024 09 26 - 18 03 59 73](https://github.com/user-attachments/assets/10504356-f7d0-43d5-b252-9aafaf963c59)

**Comment by Technici4n** [comment]
Looks like you accidentally hid bronze ingots from EMI?
