### ISSUE TITLE
JEI overlay offset

### ISSUE THREAD

**Issue by Veydiz** [AztechMC/Modern-Industrialization#905]
Hello, I'm in the latest version of MI (2.2.24) in 1.21.1, as well as the latest version of JEI (19.19.0.220) in the last version of Neoforge (21.164) . And I have a display problem on all MI machine interfaces in JEI, there's an overlay offset 
![image](https://github.com/user-attachments/assets/13e6b07d-6f65-4317-880e-32e01a37a5e0)

**Comment by mezz** [comment]
There was a missing push/pop for the gui transform in MI's JEI plugin.
I created a PR for this issue here:
* https://github.com/AztechMC/Modern-Industrialization/pull/912
