### ISSUE TITLE
Lubricant placed on the ground causes x-ray.

### ISSUE THREAD

**Issue by kalutro** [AztechMC/Modern-Industrialization#906]
FTB NeoTech 1.7.0

Lubricant in a bucket cannot be placed on the ground as a liquid, but if you put it inside of a Mekanism tank, it places it as a see-through block, allowing an x-ray-like effect. The block is solid and when broken, causes missing texture particles. The Lubricant cannot be picked back up with a bucket or tank.

![javaw_sHYZQU5i6G](https://github.com/user-attachments/assets/50e34975-5e32-4da1-bd73-99fc58a3b5a4)

**Comment by Swedz** [comment]
This was already reported in #810 and fixed in #812. A fix likely won't be back-ported.
