### ISSUE TITLE
Crash while moving Industrial Foregoing's Meat Ore Fluid with MI's fluid pipes

### ISSUE THREAD

**Issue by MuteTiefling** [AztechMC/Modern-Industrialization#907]
https://gist.github.com/MuteTiefling/93db85f0bb75b0e01cd4079ede9fcc1f

Steps to reproduce
1. Pump Meat/Ores into a Ore Washer
2. Wait for it to generate meat ore
3. Attempt to pipe out said fluid with an MI pipe

**Comment by Swedz** [comment]
Hmmm. Looking into this myself - ~~what even is the purpose of the check at [FluidVariantImpl:68](https://github.com/AztechMC/Modern-Industrialization/blob/39d2650e5202f6a9b547b3cd01a3145297c283ca/src/main/java/aztech/modern_industrialization/thirdparty/fabrictransfer/impl/fluid/FluidVariantImpl.java#L68)? Seems kinda weird to me~~
