### ISSUE TITLE
[Feature] About Nuclear Hatch

### ISSUE THREAD

**Issue by SMFDrummer** [AztechMC/Modern-Industrialization#909]
Please tell me how to simultaneously complete the input and output of nuclear reactants and fluid compartments through one surface.

In the tutorial book of the game, you wrote that each item or fluid interface has one input surface and two output surfaces, but the nuclear reactor only allows one surface to be exposed. So, who are the other two surfaces designed for?

**Comment by Swedz** [comment]
You can put more than one MI fluid pipe in a block as long as they are different colors.

**Comment by SMFDrummer** [comment]
Oh GOD, that's so horriable. Weird pipe.
![2024-10-06_12 46 18](https://github.com/user-attachments/assets/6f54b602-2153-4ba9-8423-8d9c179382ce)

**Comment by Swedz** [comment]
Did you perhaps misspell "amazing"?
