### ISSUE TITLE
lost the textures

### ISSUE THREAD

**Issue by HIN0815** [AztechMC/Modern-Industrialization#91]
Some textures are lost as seen in the screenshot
![image](https://user-images.githubusercontent.com/43261589/128591820-6f30f139-9336-472e-bbff-bd80cc9f0957.png)
![image](https://user-images.githubusercontent.com/43261589/128591833-82accde0-7334-4b81-b428-f236236cf462.png)

mod ver: Modern-Industrialization-0.5.5
minecraft ver: 1.17.1
fabric ver: fabric-api-0.37.1+1.17

**Comment by Azercoco** [comment]
MI is not compatible with sodium witthout lithium. There is a download link to install the correct both versions on our Discord.

**Comment by HIN0815** [comment]
Oic, Thank you.
