### ISSUE TITLE
Tech reborn compatibility

### ISSUE THREAD

**Issue by vermilion-exe** [AztechMC/Modern-Industrialization#916]
I have been playing a modpack that has both tech reborn and modern industrialization and I've noticed that the tech reborn iridium ore does not spawn bc of modern industrialization. Would be great if there was a compatibility between those two mods.

**Comment by Swedz** [comment]
As far as I know... there's nothing in MI that touches other mods' world generation stuff. This may be something your modpack has configured.

**Comment by vermilion-exe** [comment]
> As far as I know... there's nothing in MI that touches other mods' world generation stuff. This may be something your modpack has configured.

Well, I decided to test that and included only tech reborn and modern industrialization only to find that iridium ore is gone. Before that I, of course, tested and saw that the iridium ore was there. I am still not sure what's the issue, but that's just my best guess.

**Comment by Technici4n** [comment]
MI does not touch other mods' worldgen.

**Comment by vermilion-exe** [comment]
My bad, it does spawn, but is in fact extremely rare. Sorry for the misunderstanding.
