### ISSUE TITLE
Empty Tag

### ISSUE THREAD

**Issue by ddbrn** [AztechMC/Modern-Industrialization#919]
Recipes for some items displays an "empty tag" and it won't work. 
![Screenshot 2024-10-29 133759](https://github.com/user-attachments/assets/aacbcddd-bd12-4ec4-9b5d-59e05ce1fa55)
![image](https://github.com/user-attachments/assets/57d2b8d9-1747-4a36-b91b-37fbce9e9c63)

**Comment by Technici4n** [comment]
Please try to reproduce with only MI installed. This is probably a modpack misconfiguration issue.
