### ISSUE TITLE
Why is REI a required dependency 

### ISSUE THREAD

**Issue by xeros-and-ones** [AztechMC/Modern-Industrialization#921]
the game doesn't want to start on 1.18.2 fabric without REI installed, even though i have both JEI and EMI installed together, but the Mod requires REI for the game to even open

**Comment by Technici4n** [comment]
Otherwise you won't be able to progress in the mod past some point. Starting from 1.19.2 we also support JEI and EMI, but in 1.18.2 it's REI only.
