### ISSUE TITLE
synthetic rubber is not craftable?[BUG]

### ISSUE THREAD

**Issue by Cebio** [AztechMC/Modern-Industrialization#923]
I upgraded my modpack to 1.15 ATM10. All my recipes were same for the crafting and i tried for the first time in new version to craft basic upgrade and im keep producing yellow dye for the synyhetic rubber recipe. I also tried steel mixer but i think it is a bug because im using what JEI tell me to do.

![Screenshot 2024-11-04 205933](https://github.com/user-attachments/assets/bf179656-ecaa-4aae-9f62-4703b8c0d418)

**Comment by Swedz** [comment]
That's because ATM tags sulfur as a yellow dye. You can get around this by locking your output slots.

**Comment by Cebio** [comment]
Hmm then i should make another mixer just for this bc im using it for a lot of recipes with output of items?

**Comment by Swedz** [comment]
yes
