### ISSUE TITLE
JEI, EMI not showing MI Recipes 

### ISSUE THREAD

**Issue by chdonncha** [AztechMC/Modern-Industrialization#924]
**Summary:**
Using my own custom Modpack
- Recipes for JEI, EMI or REI for MI do not work. However, the MI items do appear but nothing happens on click.
- Some recipes clicked on such as Lubricant will only Display other relevant mods such as Create, where parts such as Bronze Rod, Curved Plate etc... will have no response on click.
- The Cutting Machine recipes do not also appear when in the Cutting Machine menu, clicking the lines in-between the Input/Output does not do anything, and the "View Recipes for Cutting Machine" tool tip does not appear either.

- Since I'm using Sinytra Connector I'd assume that something related to that would be the issue but have found someone else who does not have this issue who uses MI with Forge via Sinytra Connector too, however I do not know their versions, and Forge might be reacting differently to NeoForge with it in this case.

**Specifications:**
Using Neoforge so Sinytra Connector is used to bridge compatibility.

**Versions:**
MineCraft: 1.20.1
NeoForge 47.1.106
Modern Industrialization: 1.8.6
JEI: 1.41
EMI: 1.1.18+1.20.1 + forge
REI: [Forge 1.20(.1)] v12.1.785 [beta]

**Screenshots:**
![image](https://github.com/user-attachments/assets/9d3bcdef-c8c8-4b4f-b394-466a91a6cdfd)
_Example when clicking Lubricant, MI machines are absent from Recipe_

**Comment by Swedz** [comment]
Can you confirm this happens in an isolated environment on 1.20.1 with just EMI and MI? It sounds like it's a modpack or sinytra connector issue.

**Comment by chdonncha** [comment]
> Can you confirm this happens in an isolated environment on 1.20.1 with just EMI and MI? It sounds like it's a modpack or sinytra connector issue.

1. Tried it there with a new instance of 1.20.1 using Fabric as Modloader and installed MI and EMI, tested a world there and EMI functions with MI recipes perfect.

2. Tried with then with another new instance of 1.20.1, using NeoForge Modloader and installed EMI, Forgified Fabric API, Cloth Config v10 API and Sinytra Connector then applied the same Modern Industrialization: 1.8.6 to Sinytra Connector.
EMI does not function as expected with recipes and functions the same way as the original issue.

It seems that Sinytra Connector is the problem after all.

**Comment by chdonncha** [comment]
Updated the description there, the person I was talking to who got this working on what I thought was NeoForge confirmed it was actually Forge, will try an instance using Forge with MI and Sinytra loader and share the results.

**Comment by Technici4n** [comment]
Connector is not supported.
