### ISSUE TITLE
MI is getting me insane

### ISSUE THREAD

**Issue by TaoHu71** [AztechMC/Modern-Industrialization#927]
i cant deal with MI anymore i spent a day trying to make those rubber sheets, it took another day to attach a quarry, on the third day i tried making the electric one, but i needed more power, that means more steam, that means bigger boiler, ok i started making the componens and i lost my mind when, after upgrading my cutting machine to steel it stopped pumping lubrificant, i have put back the bronze one and it stopped, replacing the cable didnt worked, break and rebuild the thing didnt worked, so i destroyed everything. Plz fix my mental issue

**Comment by TelepathicGrunt** [comment]
So the issue is under a specific setup, the pipes stop pumping? If you can remake the problematic setup and show pictures of everything, that’ll greatly help the devs with reproducing the issue or point out where the setup is wrong
