### ISSUE TITLE
Attempt to get block drops from MI barrel/tank without attached block entity can crash the game

### ISSUE THREAD

**Issue by James103** [AztechMC/Modern-Industrialization#931]
When an MI barrel or tank is broken or its drops are otherwise retrieved, the mod checks if the block entity, which holds the content of the barrel, is empty or locked when determining whether to copy the block entity data into the barrel to be dropped.
However, mods like Building Gadgets 2 can call the function to get the item which drops from breaking the barrel without the barrel having an attached block entity. This breaks these mods' functionality, which can cause errors or even crash the game.
Original issue: https://github.com/Direwolf20-MC/BuildingGadgets2/issues/143
https://github.com/AztechMC/Modern-Industrialization/blob/a52a0913533ec3053d2b9187cc2c66a0eef09cb8/src/main/java/aztech/modern_industrialization/blocks/storage/AbstractStorageBlock.java#L72-L74

Fixing this will likely need a check to see if the block's block entity is null, and if so returns an empty barrel/tank/appropriate storage unit.

**Comment by Technici4n** [comment]
This should be fixed in BG2. I don't want to add a null check in MI because it would then silently void items.

**Comment by Technici4n** [comment]
Well for barrels it might be fine to return an empty one.

**Comment by Technici4n** [comment]
Fixed by https://github.com/AztechMC/Modern-Industrialization/pull/963
