### ISSUE TITLE
Wire Tags

### ISSUE THREAD

**Issue by TheBedrockMaster** [AztechMC/Modern-Industrialization#933]
Please add the `c:wires` and `c:wires/{material}` item tags to wires for unification purposes.

**Comment by Swedz** [comment]
Added in #943

**Comment by Swedz** [comment]
What mod are you trying to unify with that uses c:wires?

**Comment by TheBedrockMaster** [comment]
Immersive Engineering uses those tags, I'm not necessarily going to unify them for progression reasons, but someone else might want to.

**Comment by Swedz** [comment]
Immersive Engineering's wires are 1 ingot to 1 wire whereas MI's are 1 ingot to 2 wire, I don't think it makes sense to unify these.

**Comment by TheBedrockMaster** [comment]
Whoever can close this, feel free to, it was just an idea.
