### ISSUE TITLE
[COMPAT] Picking up the wires with the CarryOn mod creates a ghostblock for the wire

### ISSUE THREAD

**Issue by olebol** [AztechMC/Modern-Industrialization#934]
Picking it up works, but when you place it somewhere else (maybe modify it by extending the pipe?) it creates a ghost block in the original position. This makes you unable to use this block for anything

**Comment by olebol** [comment]
In this case it was a fluid pipe containing steam...

**Comment by Swedz** [comment]
There is not much we can do about this aside from preventing the pipes from being picked up.

To fix your issue, make sure debug commands are enabled, and then you can use the `/mi pipes <pos> clear` command to remove the ghost pipes.

Looks like CarryOn uses tags now so the `carryon:block_blacklist` tag could be added to the pipe block to prevent this issue in the future.

**Comment by Technici4n** [comment]
CarryOn should add `c:relocation_not_supported` to its blacklist by default.
