### ISSUE TITLE
[BUG] When placing the Bronze Tank, the chunk fails to load and the game crashes upon joining. Help!

### ISSUE THREAD

**Issue by PEZ500** [AztechMC/Modern-Industrialization#94]
My friends and I play on a server running All Of Fabric 3, I placed a bronze tank and the game crashed as well as the server. I have gone into the console and noticed this:

"Illegal classload request for badasintended.megane.impl.mixin.modern_industrialization.ATankBlockEntity."

We has this issue the other day and had to restore a backup, as you can imagine with a game like this that relies heavily on progress that can be made an awful lot in one day it gets quite infuriating. Any help would really be appreciated and maybe the devs can look into this???

**Comment by Azercoco** [comment]
Apparently, the problem comes from megane. Disable it and try again.

**Comment by Technici4n** [comment]
Update MI and megane.
