### ISSUE TITLE
Nuclear Reactor does not update it's placement grid in 1.21.1

### ISSUE THREAD

**Issue by Rothlan284** [AztechMC/Modern-Industrialization#942]
![image](https://github.com/user-attachments/assets/ecb579ab-5ba7-40ad-b7e6-9454f54dab49)

The Nuclear Reactor multiblock does not work at all in 1.21.1.

I've placed a "Nuclear Fluid Hatch on the right, a "Nuclear Item Hatch" on the left, and the rest of the 3x3 is using the "Nuclear Alloy Casing". However, the multiblock structure does not update, and there are no visible changes to the structure's helping placement grid.

I've read the book numerous times and it's told me to experiment in creative and find the right design for me, however this is just not possible at the moment.

**Comment by Swedz** [comment]
The green grid you are looking at where hatches can be placed. The green boxes remain even though you have hatches there for consistency sake. Hold a wrench to see where the rest of the multiblock needs to be built.
