### ISSUE TITLE
crash with new version

### ISSUE THREAD

**Issue by VaporeonScripts** [AztechMC/Modern-Industrialization#946]
https://mclo.gs/RwCErVl
neoforge 1.21.1 .83

**Comment by Swedz** [comment]
This is not an issue with MI. EI cannot run with the latest version of MI due to breaking changes in the API. This will be addressed when the rest of the changes I have submitted are merged. For now, just downgrade MI one version.

**Comment by Swedz** [comment]
Just released the update for EI, MI Tweaks, and Tesseract API. Should be fully resolved now
