### ISSUE TITLE
Severe FPS loss while holding MI hatches with many MI multiblocks built

### ISSUE THREAD

**Issue by James103** [AztechMC/Modern-Industrialization#957]
### Version info

Modern Industrialization 2.2.25
Minecraft 1.21.1
NeoForge 21.1.79
Modpack: Craftoria 1.9.0

### Expected result

Reasonably smooth performance, even with dozens or hundreds of multiblocks.

### Actual result

When there are a large number of MI multiblocks present in one area, holding an MI hatch in either hand causes a severe FPS drop due to trying to render a large number (thousands) of possible locations for hatches within the multiblock structures.

The linked and attached Spark profile shows this issue with approximately 142 MI multiblocks within the area and holding an MI item input hatch. 
https://spark.lucko.me/5XnqRehlIZ or [5XnqRehlIZ.zip](https://github.com/user-attachments/files/18088846/5XnqRehlIZ.zip)

A large amount of the additional time is spent calling this function repeatedly (once per possible hatch location per frame totaling tens of thousands of calls per second).
https://github.com/AztechMC/Modern-Industrialization/blob/51faadc0acbe73e1414d0d5e3fbabe8d82406050/src/client/java/aztech/modern_industrialization/machines/multiblocks/MultiblockMachineBER.java#L69

### Steps to reproduce

1. Build a few dozen MI multiblock structures in one area (ideally in a superflat world or void dimension).
2. Hold an MI hatch in your hand.
3. Notice the loss in FPS.

The actual performance impact is proportional to the number of possible hatch locations (green overlay boxes), which depends on the number and type of multiblock structures present – multiblocks with more flexible hatch placement have a bigger FPS impact while the player is holding a hatch.

**Comment by Swedz** [comment]
Not a fix to the issue per se, but there is a config option to disable this hatch overlay rendering.

**Comment by Kazuhiko-Gushiken** [comment]
@Swedz what about a config option called... `showHatchOverlayOnValid`

`true` : it will show all hatch overlays
`false` : if a hatch or hatch placements are a part of a valid completed multiblock, it just doesnt render them. the multiblock needs to be invalid for hatch overlays to show

**Comment by Technici4n** [comment]
I implemented https://github.com/AztechMC/Modern-Industrialization/pull/982 which should already help quite a bit. Please let me know if you still notice severe FPS loss after that.

**Comment by James103** [comment]
I tested with 3,000 Implosion Compressors in one area, while holding an item input or item output hatch. This renders 24,000 hatch overlays (8 per multiblock) every frame, stress-testing the hatch overlay rendering code.

Base: 4 ms/frame
Modern Industrialization 2.2.29: 165 ms/frame (6 frames/second) - rendering the overlays costs an additional ≈ 160 ms/frame.
Modern Industrialization 2.2.30: 112 ms/frame (9 frames/second) - rendering the overlays costs an additional ≈ 110 ms/frame.
Thus, the optimization you made in #982 speeds up rendering the hatch overlays by about 30%.

Large bases with hundreds of multiblocks will still see potentially severe FPS loss when constructing new multiblock structures, even when all existing multiblocks are formed and active. The config option proposed in #983 should help with that case to a greater extent.

**Comment by Technici4n** [comment]
https://github.com/AztechMC/Modern-Industrialization/pull/994 should roughly x4 the performance of rendering the overlay.

**Comment by James103** [comment]
I updated my mods and recreated the same test setup as above, which gave me this result:

Modern Industrialization 2.2.31: 47 ms/frame (21 frames/second) - rendering the overlays costs an additional ≈ 43 ms/frame.
Thus, the optimization you made in #994 speeds up rendering the hatch overlays by about 150%, on top of the 30% speedup from #982. In total, your optimizations sped up hatch overlay rendering by approximately 3.7 times between MI versions 2.2.29 and 2.2.31.

**Comment by Technici4n** [comment]
Okay, not bad. ^^
