### ISSUE TITLE
[QUESTION] How is the air intake used?

### ISSUE THREAD

**Issue by duncanwebb** [AztechMC/Modern-Industrialization#96]
How is the air intake used to capture air? I'm guessing that it attached to a machine.

**Comment by Technici4n** [comment]
It's used as an input for the pressurizer IIRC.

**Comment by Technici4n** [comment]
(Just put it in an item input hatch like other recipe inputs).

**Comment by duncanwebb** [comment]
The pressurizer captures air and the vacuum freezer extracts it, makes sense. Many thanks

**Comment by duncanwebb** [comment]
I forgot to install a fluid output hatch on the vacuum freezer.
