### ISSUE TITLE
Please dont randomly add Exceptions to vanilla methods without a singature

### ISSUE THREAD

**Issue by Smartin-b** [AztechMC/Modern-Industrialization#961]
https://github.com/AztechMC/Modern-Industrialization/blob/5847e5813e16e525932ebb84e07c4375d5eebb2d/src/main/java/aztech/modern_industrialization/items/armor/MIArmorMaterials.java#L49
Ingredient.Empty is fully valid way of declaring this item cant be repaired. Throwing an Exception here can cause issues in other mods.

**Comment by Technici4n** [comment]
This code was written a long time ago, so I don't remember the details. I think there were other issues with returning an empty ingredient (maybe because an empty ingredient will accept empty stacks?). I think the reasoning was that because of the durability being 0, nothing should ever even attempt to repair this armor.

**Comment by Technici4n** [comment]
@Smartin-b Can you link the code that attempted to call this method?

**Comment by unilock** [comment]
This was the line of code in question (I helped diagnose the issue):

https://github.com/Truly-Modular/Modular-Item-API/blob/ee751e63b14e1ab8a7fd1437a8c24f95dd50c5fb/common/src/main/java/smartin/miapi/material/generated/GeneratedMaterial.java#L164

**Comment by Swedz** [comment]
This can be avoided by checking if the item has the `MAX_DAMAGE` or `DAMAGE` component before trying to get a non-existent repair ingredient. For example:
```java
item.components().has(DataComponents.DAMAGE)
```

**Comment by unilock** [comment]
`ArmorMaterial#repairIngredient` still shouldn't throw an exception...

**Comment by Technici4n** [comment]
It throws an exception because even calling the method indicates that a check is missing, as @Swedz pointed out. Not amazing I agree but a good way to detect logic errors in other mods IMO.
