### ISSUE TITLE
Client crash when setting a Modern Industrialization steel barrel to use as replace-with item in an Exchange Gadget (from Building Gadgets 2)

### ISSUE THREAD

**Issue by SubordinalBlue** [AztechMC/Modern-Industrialization#962]
Modern Industrialization Version
2.2.25, NeoForge 21.1.82

Building Gadgets Version
1.3.4

Describe the bug
Client crash when setting Exchange Gadget to use a Modern Industrialization steel barrel as replace-with item. The barrel was empty and unlocked at the time.
This was with a local server; server process itself was fine.
Client crashes repeated on entering world--solved by editing player data to delete the exchange gadget.

Crash reports at end of this post.

This report is meant as a cross-report of the issue on Building Gadgets 2's repo: https://github.com/Direwolf20-MC/BuildingGadgets2/issues/152

I have no idea--which, both, or neither--mod(s) are 'at fault' in this case.

Cheers, and thanks again for _MI_. Love having it in my worlds.

Crash Reports:
Initial crash:
[crash-2024-12-17_11.47.07-client.txt](https://github.com/user-attachments/files/18159600/crash-2024-12-17_11.47.07-client.txt)

2nd crash on restarting client and rejoining server:
[crash-2024-12-17_11.50.36-client.txt](https://github.com/user-attachments/files/18159603/crash-2024-12-17_11.50.36-client.txt)

**Comment by Swedz** [comment]
This should be easy enough to fix, but I question whether the building gadget being used with block entities is intentional or not.

**Comment by Technici4n** [comment]
Yes it is. Checking for BE != null is enough to fix this.
