### ISSUE TITLE
[QUESTION] Using MV to LV transformers

### ISSUE THREAD

**Issue by duncanwebb** [AztechMC/Modern-Industrialization#97]
Does the MV to LV transformer output 128 EU/t, or does it require four transformers to use the full energy from a diesel generator or an advanced steam turbine?

With overclocking upgrades, the energy requirements can be higher than the power of a steam turbine. So using an advanced steam turbine with a transformer would give more energy units for overclocked machines.

I realize that an LV machine can be upgraded to use MV energy units.

**Comment by Technici4n** [comment]
The only thing tiers do is limit the total amount of EU/t in cable networks. Everything has unlimited input/output rates (well, actually the max rate is what can fit in their energy buffer). Hopefully you can figure it out with this information.

**Comment by duncanwebb** [comment]
Thanks, not quite sure what you mean. I've noticed that the cables don't limit the EU/t to the machine, otherwise the machines could not be overclocked, the centrifuge is an example. I'll see if I can figure it out. Many thanks.
