### ISSUE TITLE
(BUG - 1.20.4) Water dupe during electric mixer automatization with me pattern provider

### ISSUE THREAD

**Issue by ArtpokeBr** [AztechMC/Modern-Industrialization#970]
MC Version: 1.20.4
Mod Version: 2.0.25-all

Reposting this Issue from [here](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6213) as I've confirmed and this issue is still present on the mod, tested on FTB NeoTech.

**Comment by Swedz** [comment]
Can you confirm that the FTB NeoTech recipe for that is configured to consume the water? That doesn't happen with any MI recipes.

**Comment by truepurpledino** [comment]
The water isn't duped though, from the video on your issue the water goes in the mixer and stays there, which is the expected outcome. It doesn't get consumed because the fluix crystal recipe's water is a non consumed ingredient.

**Comment by Swedz** [comment]
Sounds like this is working as intended :)
