### ISSUE TITLE
Boilers and Item Input Hatches with lava buckets as fuel cant extract bucket

### ISSUE THREAD

**Issue by coyo-t** [AztechMC/Modern-Industrialization#971]
if you use a lave bucket for fuel in a bronze or steam boiler, or the large boiler with an item input hatch, you can't extract the bucket. AE2 storage busses donesnt recognise there being any slots in it, item pipes (either from MI or modern dynamics) cant extract them, hoppers cant
Curiously, Computercraft computers *can* recognise item hatches as being an inventory (though I havent tested whether they can transfer it to another container because ive forgotten how to do that)

unless im missing something, as best as i can tell there is no way to extract the bucket that doesnt require the player doing it by hand

**Comment by Swedz** [comment]
That is intentional. You are not meant to be able to use lava as a fuel for boilers aside from manually.

**Comment by coyo-t** [comment]
this should be stated somewhere in the guidebook then
