### ISSUE TITLE
Coke oven not shutting down when creosote fluid output is full 

### ISSUE THREAD

**Issue by jfmoots** [AztechMC/Modern-Industrialization#972]
Running version 2.2.27 in the ATM 10 modpack. When burning coal to make coke in the Coke Oven, I'm used to the oven shutting down if the fluid output port is full of creosote. But mine is still burning.

**Comment by Technici4n** [comment]
This happens because creosote is a chanced output, working as intended. :smile:

**Comment by jfmoots** [comment]
Gotcha. Thanks for the quick response. I thought I was going crazy. In previous builds I had always put a liquid trash can to catch overflow. I guess I assumed it would stop if full and probably never actually witnessed it stopping. Or... maybe the recipe in that other mod pack didn't have it a chance output. Anyway, thanks so much for the response on Christmas! Love the mod!

**Comment by Technici4n** [comment]
Thanks for the kind words!
