### ISSUE TITLE
Machines efficiency/overclocking math issue

### ISSUE THREAD

**Issue by neoncyber1** [AztechMC/Modern-Industrialization#973]
The overclocking math works fine without any and with max upgrades, but I've noticed other weird things happening. My x200 (1/t) overclocked macerator speed match the math perfectly but x96 processes iron ore like it's x68 while x16(no upgrades) is fine again, which is kinda weird. I've also noticed that quarries placed next to each other reduce the efficiency of both by ~15% less than if they were single so if one gives 0.35/t ore then both give 0.61/t . Is this how it's supposed to work?

**Comment by Swedz** [comment]
Not sure I understand the issue. It sounds like you're capped out on power. Machines will simply reduce efficiency when out of power instead of shut off unless it's completely out of power.

**Comment by neoncyber1** [comment]
Definitely not power issue bc ive tested this several times with creative energy/drill sources and high machine hulls. Machines just constantly provide less production than the overclock says. So to be more specific:
1 iron ore processing takes 2eu/t and 10s = 1ore/200t = 0.005ore/t and actual speed matches perfectly 
with no upgrades max overclock is x16 = 0.08ore/t and actual speed matches perfectly 
when i put 5 turbo upgrades overclock is x96 = 0.48ore/t but the actual speed is 0.33ore/t
and finally max upgrade x200 = 1ore/t matches perfectly 
![2024-12-26_02 09 42](https://github.com/user-attachments/assets/b7bf1388-e6eb-47b6-85df-fd0e8c9d7d52)
![2024-12-26_02 33 15](https://github.com/user-attachments/assets/027fe544-9edc-4cb8-9c99-2608665f3df0)
![2024-12-26_02 27 04](https://github.com/user-attachments/assets/07e302ec-bec6-4f76-bfd7-1f6191984fe7)

**Comment by James103** [comment]
Can you please try overclocking an electric furnace and checking both the power consumption and smelting rate when smelting cobblestone into stone (recipe cost: 400 EU)?

The results I got were (at max efficiency):
* With 11 Advanced Upgrades (208 EU/t), the furnace uses 208 EU/t to smelt 1 cobblestone every 2 ticks, In the first tick, 208 EU is consumed; in the second tick, 192 EU is consumed to bring the total to 400 and finish the recipe.
* With 22 Advanced Upgrades (384 EU/t), the furnace still smelts one cobblestone every two ticks, at a power draw of 384 EU/t. 384 EU is consumed in the first tick while 16 EU is consumed in the second tick, for a total energy consumption of 400 EU per two-tick cycle.
* With 23 Advanced Upgrades or greater (400+ EU/t), the furnace smelts one item per tick and uses 400 EU/t to do so.

Modpack: Craftoria 1.9.0
Extended Industrialization `1.9.4-beta-1.21.1`
Modern Industrialization `2.2.25`
MI Tweaks `1.5.3-beta-1.21.1`
Tesseract API `1.5.4-beta-1.21.1`
EMI `1.1.18+1.21.1+neoforge`
Minecraft 1.21.1
NeoForge 21.1.79

**Comment by Swedz** [comment]
With regard to your second bullet point James, it should only consume 384 the first tick and 16 the second tick to craft the cobblestone if the total cost is indeed 400. Can you confirm this by not supplying the machine with constant power and seeing that the difference in power stored is -400?

**Comment by James103** [comment]
> With regard to your second bullet point James, it should only consume 384 the first tick and 16 the second tick to craft the cobblestone if the total cost is indeed 400. Can you confirm this by not supplying the machine with constant power and seeing that the difference in power stored is -400?

I can confirm this in a fresh instance with only MI and dependencies. I've edited my earlier comment to reflect this.

**Comment by neoncyber1** [comment]
> Can you please try overclocking an electric furnace and checking both the power consumption and smelting rate when smelting cobblestone into stone (recipe cost: 400 EU)?

I got same results, but thanks to your detailed answer I now realize that I had a misconception about how game actually works and i guess my quarry results issue is simillar so no questions anymore and thanks :3

**Comment by neoncyber1** [comment]
It would be nice if machines somehow could use excess consumption for the next cycle so that overclock would show the actual outcome rate
