### ISSUE TITLE
[Textures] All textures break if you install a third-party resource pack

### ISSUE THREAD

**Issue by katelinlis** [AztechMC/Modern-Industrialization#98]
![image](https://user-images.githubusercontent.com/56870191/129527163-adab8e7e-0c39-4f0f-9308-07d472ef7de6.png)

Hello, i`m trying use resource pack faithful , but i get this error, 
i trying used other resource packs, but meet the same problem

**Comment by Technici4n** [comment]
Install indium.

**Comment by katelinlis** [comment]
after installing 
sodium-fabric-mc1.16.5-0.2.0+build4 and indium-1.0.0+mc1.16.5
the problem persists

**Comment by Azercoco** [comment]
Can you provide the full error log ?

**Comment by katelinlis** [comment]
@Azercoco 
`
11:34:41.473
net.minecraft.class_1059
Worker-Main-12
Using missing texture, unable to load modern_industrialization:textures/items/cupronickel_double_ingot.png : java.io.FileNotFoundException: modern_industrialization:textures/items/cupronickel_double_ingot.png
11:34:41.474
net.minecraft.class_1059
Worker-Main-13
Using missing texture, unable to load modern_industrialization:textures/items/coal_crushed_dust.png : java.io.FileNotFoundException: modern_industrialization:textures/items/coal_crushed_dust.png
11:34:41.474
net.minecraft.class_1059
Worker-Main-13
Using missing texture, unable to load modern_industrialization:textures/items/nuclear_alloy_plate.png : java.io.FileNotFoundException: modern_industrialization:textures/items/nuclear_alloy_plate.png
11:34:41.478
net.minecraft.class_1059
Worker-Main-13
Using missing texture, unable to load modern_industrialization:textures/blocks/casings/supraconductor/bottom.png : java.io.FileNotFoundException: modern_industrialization:textures/blocks/casings/supraconductor/bottom.png
11:34:41.478
net.minecraft.class_1059
Worker-Main-13
Using missing texture, unable to load modern_industrialization:textures/items/aluminum_double_ingot.png : java.io.FileNotFoundException: modern_industrialization:textures/items/aluminum_double_ingot.png
11:34:41.480
net.minecraft.class_1059
Worker-Main-13
Using missing texture, unable to load modern_industrialization:textures/items/mozanite_crushed_dust.png : java.io.FileNotFoundException: modern_industrialization:textures/items/mozanite_crushed_dust.png
11:34:41.482
net.minecraft.class_1059
Worker-Main-17
Using missing texture, unable to load modern_industrialization:textures/blocks/platinum_block.png : java.io.FileNotFoundException: modern_industrialization:textures/blocks/platinum_block.png
11:34:41.482
net.minecraft.class_1059
Worker-Main-13
Using missing texture, unable to load modern_industrialization:textures/items/copper_blade.png : java.io.FileNotFoundException: modern_industrialization:textures/items/copper_blade.png
11:34:41.483
net.minecraft.class_1059
Worker-Main-13
Using missing texture, unable to load modern_industrialization:textures/items/plutonium_fuel_rod_double.png : java.io.FileNotFoundException: modern_industrialization:textures/items/plutonium_fuel_rod_double.png
11:34:41.485
net.minecraft.class_1059
Worker-Main-13
Using missing texture, unable to load modern_industrialization:textures/blocks/titanium_ore.png : java.io.FileNotFoundException: modern_industrialization:textures/blocks/titanium_ore.png
11:34:41.485
net.minecraft.class_1059
Worker-Main-13
Using missing texture, unable to load modern_industrialization:textures/items/beryllium_rod.png : java.io.FileNotFoundException: modern_industrialization:textures/items/beryllium_rod.png
11:34:41.487
net.minecraft.class_1059
Worker-Main-13
Using missing texture, unable to load modern_industrialization:textures/blocks/casings/firebricks/top.png : java.io.FileNotFoundException: modern_industrialization:textures/blocks/casings/firebricks/top.png
11:34:41.488
net.minecraft.class_1059
Worker-Main-13
Using missing texture, unable to load modern_industrialization:textures/items/steel_ingot.png : java.io.FileNotFoundException: modern_industrialization:textures/items/steel_ingot.png
11:34:41.491
net.minecraft.class_1059
Worker-Main-12
Using missing texture, unable to load modern_industrialization:textures/items/uranium_238_tiny_dust.png : java.io.FileNotFoundException: modern_industrialization:textures/items/uranium_238_tiny_dust.png
11:34:41.490
net.minecraft.class_1059
Worker-Main-11
Using missing texture, unable to load modern_industrialization:textures/items/steel_tiny_dust.png : java.io.FileNotFoundException: modern_industrialization:textures/items/steel_tiny_dust.png
11:34:41.489
net.minecraft.class_1059
Worker-Main-16
Using missing texture, unable to load modern_industrialization:textures/items/gold_dust.png : java.io.FileNotFoundException: modern_industrialization:textures/items/gold_dust.png
11:34:41.493
net.minecraft.class_1059
Worker-Main-16
Using missing texture, unable to load modern_industrialization:textures/items/tin_rotor.png : java.io.FileNotFoundException: modern_industrialization:textures/items/tin_rotor.png
11:34:41.493
net.minecraft.class_1059
Worker-Main-17
Using missing texture, unable to load modern_industrialization:textures/items/carbon_tiny_dust.png : java.io.FileNotFoundException: modern_industrialization:textures/items/carbon_tiny_dust.png
11:34:41.488
net.minecraft.class_1059
Worker-Main-15
Using missing texture, unable to load modern_industrialization:textures/items/invar_gear.png : java.io.FileNotFoundException: modern_industrialization:textures/items/invar_gear.png
`

**Comment by Technici4n** [comment]
Actually, only x16 resource packs are supported on 1.16.5. This issue was fixed for 1.17.

**Comment by katelinlis** [comment]
Texture on others mods on 1.16.5 not broken, on this mod broken

**Comment by Technici4n** [comment]
Yes, I meant that MI 1.16 doesn't support resource packs.
