### ISSUE TITLE
Steam boiler not explodes, when in pour water

### ISSUE THREAD

**Issue by katelinlis** [AztechMC/Modern-Industrialization#99]
![image](https://user-images.githubusercontent.com/56870191/129544156-f3e06c03-b768-4662-a027-452e62a3533d.png)
If you fill in water before warming up, the boiler should not explode if a large amount of steam is generated after and boiler explode

**Comment by katelinlis** [comment]
And in game endless source of water
need to be able to disable

**Comment by katelinlis** [comment]
![image](https://user-images.githubusercontent.com/56870191/129545867-275b6eb3-62f4-436e-a2fb-3fb4e7b0139b.png)
if electic machines under rain, then they do not burn

**Comment by Technici4n** [comment]
No, we have no plans to implement such annoying GT-imported gameplay "features".
